local L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers_GUI", "zhCN")
if not L then return end

L["Air"] = "空气图腾"
L["Automatic"] = "自动"
L["Bottom"] = "底部"
L["Cast Button 1"] = "施法按钮1"
L["Cast Button 2"] = "施法按钮2"
L["Clickthrough"] = "点击"
L["Clickthrough Desc"] = "禁用任何点击功能的定时器按钮"
L["Crowd Control"] = "控制技能"
L["Down"] = "向下"
L["Earth"] = "大地图腾"
L["Enable"] = "启用"
L["Fire"] = "火焰图腾"
L["Left"] = "左侧"
L["none"] = "无"
L["Right"] = "右侧"
L["Top"] = "顶部"
L["Totems"] = "图腾设置"
L["TotemTimers"] = "图腾计时器"
L["Up"] = "向上"
L["Version"] = "版本"
L["vertical"] = "垂直排列"
L["Water"] = "水之图腾"

L["Blizz Style"] = "暴雪样式"
L["Color Timer Bars"] = "着色计时条"
L["Color Timer Bars according to their elements."] = "根据元素计时条上色."
L["Debug"] = "调试"
L["Displays timer bars underneath times"] = "显示计时条在时间下方"
L["Fulmination Aura"] = "撼天雷电光环"
L["Fulmination Aura Desc"] = "如果使用魔兽世界内置的 PowerAuras 并且闪电盾堆叠到9层时则显示了一个光环围绕你的角色"
L["Fulmination Glow"] = "撼天雷电光环"
L["Fulmination Glow Desc"] = "如果闪电盾堆叠到9层时,让大地震击冷却计时器与动作列按钮显示大地震击辉光"
L["General"] = "综合"
L["Hide Blizzard Timers"] = "隐藏暴雪计时器"
L["Hide Default Totem Bar"] = "隐藏默认的图腾条"
L["Hide Default Totem Bar Desc"] = "如果你取消这个你应该重新载入你的界面."
L["Hide In Vehicles"] = "在载具中时隐藏"
L["Hide In Vehicles Desc"] = "当在载具中时隐藏 TotemTimers. 在驾驶时请不要改动此设置"
L["Lock"] = "锁定"
L["Locks the position of TotemTimers"] = "锁定 TotemTimers 的位置"
L["RaidTotems"] = "团队图腾"
L["RaidTotems Desc"] = "设置图腾组法术根据团队图腾插件发送的图腾来分配."
L["Red Flash Color"] = "红光闪烁"
L["RedFlash Desc"] = "如果启用到期时间红光闪烁,否则淡入或淡出."
L["Reset All"] = "重置全部"
L["Reset Positions"] = "重置位置"
L["Show Key Bindings"] = "显示快捷键"
L["Shows key bindings on totem timers"] = "在图腾计时上显示快捷键"
L["Shows tooltips on timer and totem buttons"] = "在计时跟图腾按钮上显示提示"
L["Show Timer Bars"] = "在时间下方显示计时条"
L["Show Tooltips"] = "显示提示信息"
L["Stop Pulse"] = "停止脉冲"
L["Stop Pulse Desc"] = " \"如果一个计时器停止其图标会出现一个可见的大脉冲效果\""
L["Time Color"] = "时间颜色"
L["Time Font"] = "时间字体"
L["Timer Bar Color"] = "计时条颜色"
L["Timer Bar Texture"] = "计时条材质"
L["Timers On Buttons"] = "按钮上显示时间"
L["Tooltips At Buttons"] = "显示提示信息"
L["Tooltips At Buttons Desc"] = "在图腾按钮的右侧显示提示信息."

L["Advanced Options"] = "进阶设置"
L["Always Visible Desc"] = "图腾选单总是可见像动作条一样四处拖动."
L["Arrangement"] = "排列方式"
L["Basic layout of the four timer buttons, loose lets you move them individually"] = "4个计时按钮的基本样式, 自由排列让你单独移动"
L["box"] = "方格排列"
L["Button Size"] = "按钮大小"
L["Cast Button Position"] = "施法按钮位置"
L["Cast Button Position Desc"] = "设置图腾额外自订的按钮位置与旁边的图腾计时"
L["Cast Button Size"] = "施法按钮大小"
L["Cast Button Size Desc"] = "设置图腾额外自订的按钮大小与旁边的图腾计时关联大小"
L["Enable Pulse Bar"] = "启用脉动条"
L["Enables the four totem timer buttons and menus"] = "启用4个图腾计时器按钮和菜单"
L["horizontal"] = "水平排列"
L["Keybindings desc"] = "如果启用, 如果图腾选单显示图腾按钮将会有按键1-9|n你必须重登设置才会生效."
L["loose"] = "自由排列"
L["Mini Icons Desc"] = "在标示图腾分配的计时按钮右下显示小图示来启动多施法法术和计时按钮将会施放."
L["Open On Rightclick"] = "鼠标右键点击打开选单"
L["Player Range"] = "玩家距离提示"
L["Player Range Desc"] = "如果玩家超出距离时在图腾计时器上显示一个红点"
L["Pulse desc"] = "在计时里面显示绿色状态条直到充满图腾脉动."
L["Raid Member Range"] = "团队成员距离提示"
L["Raid Range Tooltip"] = "显示团队成员距离列表"
L["Range Desc"] = "在左下角显示有多少团队成员没有获得你的图腾增益"
L["Reverse Key Bindings"] = "反转图腾选单快捷键"
L["Reverse Key Desc"] = "锁定按键9-1而不是1-9|n你必须重登这个设置才会生效."
L["Rightclick Desc"] = "右键开启图腾选单而不是经过计时按钮. 用滑鼠中键按钮可以图腾解散而不是右键点击."
L["RR Tooltip Desc"] = "滑鼠经过时显示团队成员清单没有在你图腾范围内"
L["Scales the timer buttons"] = "缩放图腾按钮"
L["Scaling"] = "縮放"
L["Sets the font size of time strings"] = "设置计时字串的字型大小"
L["Sets the format in which times are displayed"] = "设置按钮之间的间隔"
L["Sets the space between timer buttons"] = "设置按钮之间的间隔"
L["Sets the space between timer buttons and timer bars"] = "设置按钮和计时条之间的间隔"
L["Sets the width of timer bars."] = "设置计时条的宽度."
L["Show Mini Icons"] = "显示小图标"
L["Show Totem Cooldowns"] = "显示图腾冷却"
L["Spacing"] = "图标间距"
L["Timer Bar Position"] = "计时条位置"
L["Timer Bar Position Desc"] = "设置在哪一方的图示计时器显示的时间"
L["Timer Bar Width"] = "计时条宽度"
L["Timer Bar Width Desc"] = "设置计时条宽度."
L["Timer Button 1"] = "计时按钮1"
L["Timer Button 2"] = "计时按钮2"
L["Timer Button 3"] = "计时按钮3"
L["Timer Button 4"] = "计时按钮4"
L["Timers"] = "按钮设置"
L["Timers On Buttons Desc"] = "计时显示在按钮上而不是在他们旁边. 如果启用, 武器追踪只会显示时间当双持时只有主手武器."
L["Time Size"] = "字体大小"
L["Time Spacing"] = "计时条与图标间距"
L["Time Style"] = "时间格式"
L["Totem Cooldowns desc"] = "所有图腾显示冷却就像额外的计时条不再冷却."
L["Totem menu direction"] = "图腾选单方向"
L["Totem menu direction desc"] = "设置图腾选单开启方向. 自动确定方向基于计时的位置."
L["Totem Menu Key Bindings"] = "显示图腾选单快捷键"
L["Totem Menus Always Visible"] = "图腾选单总是显示"
L["Totem Menu Spacing"] = "图腾选单内图标间隔"
L["Totem Menu Spacing Desc"] = "在图腾选单设置按钮间隔. 只允许如果选单总是可见."

L["Ankh Tracker"] = "复生"
L["Ankh Tracker Desc"] = "显示复生技能的剩余冷却时间以及你的背包内十字章的数量. 也可以用来保存和加载图腾设置."
L["Button 4"] = "鼠标按钮4点击"
L["EarthShieldDesc"] = "显示大地之盾的剩余时间和次数. 可以用来施放大地之盾."
L["EarthShieldOptionsDesc"] = "如果为了滑鼠按钮改写像设置一样被选择, 当离开战斗盾被施放在最后一人或是被团队图腾插件分配. 预设用法: 离开战斗指向你大地之盾目标之后用右键点击按钮施放法术. 那么你可以指向任何一人, 然而用右键点击大地之盾仍然会施放在相同的人身上, 甚至在战斗中."
L["Earth Shield Tracker"] = "大地之盾"
L["ES Charges only"] = "只显示剩余次数"
L["ES Charges only desc"] = "关闭时间显示,在其位置上显示大地之盾的层数|n在你下一次施放大地之盾时生效"
L["ES Main Tank Desc"] = "滑鼠停留时显示了一个选单里面包含多达4个你队伍/团队中的主坦克"
L["ES Main Tank menu"] = "坦克选单"
L["esrecast"] = "重新施放 (最后一个目标/团队图腾)"
L["Leftclick"] = "鼠标左键点击"
L["Middle Button"] = "鼠标中键点击"
L["Rightclick"] = "鼠标右键点击"
L["Shield Tracker"] = "萨满护盾"
L["Trackers"] = "追踪器设置"
L["Weapon Buff Tracker"] = "武器增益"
L["WeaponDesc"] = "显示武器剩余增益时间.左键点击施放选择的武器增益. 右键点击开启选单选择增益, 一个图示显示两个增益. 第一个左键点击施放左边增益和第二个左键点击右边增益."

L["Color"] = "颜色"
L["disabled warnings desc"] = "即使追踪禁用, 到期增益警告还是会显示"
L["EarthShield warnings"] = "大地之盾警告"
L["Maelstrom notification"] = "漩涡武器提醒"
L["Messages"] = "信息"
L["Shield expiration warnings"] = "护盾到期警告"
L["Show warnings of disabled trackers"] = "禁用追踪显示警告"
L["Sound"] = "声音"
L["Totem Desctruction Desc"] = "警告如果图腾在到期前被销毁."
L["Totem Destruction Message"] = "图腾销毁信息"
L["Totem Expiration Desc"] = "图腾到期之后警告."
L["Totem Expiration Message"] = "图腾到期信息"
L["Totem Expiration Warning"] = "图腾到期警告"
L["Totem Warning Desc"] = "在图腾10秒到期前警告."
L["Warnings"] = "警告设置"
L["Weapon buff warnings"] = "武器增益警告"

L["Menu Direction"] = "选单方向"
L["Menu Key Bindings"] = "选单快捷键"
L["Multicast Button"] = "图腾组设置"
L["MultiCast Keybinds Desc"] = "从1-3分配快捷键按钮在图腾组选单上.|n你必须重登设置才会生效."
L["MultiCast Reverse Keybinds Desc"] = "从9-6分配快捷键而不是1-3.|n你必须重登设置才会生效."
L["Same as totem menus"] = "跟图腾选单相同"
L["Same as weapon buff menu"] = "跟武器增溢选单相同"

L["Duration"] = "期间"
L["ECD Button Size"] = "冷却图标大小"
L["ECD Font Size"] = "冷却字体大小"
L["EnhanceCDs"] = "冷却设置"
L["Flame Shock on top"] = "设置烈焰震击在顶部"
L["Flame Shock on top desc"] = "显示烈焰震击时间与气旋武器条在冷却计时器上方"
L["Hide OOC Desc"] = "改变这个设置下一次战斗才会生效"
L["Hide out of combat"] = "离开战斗隐藏"
L["Lava Surge Aura"] = "熔岩奔腾光环"
L["Lava Surge Aura Desc"] = "如果使用魔兽世界内置的熔岩奔腾特效 PowerAuras 则显示了一个光环围绕你的角色"
L["Lava Surge Glow"] = "熔岩奔腾辉光"
L["Lava Surge Glow Desc"] = "当熔岩奔腾特效发动时让熔岩爆发的冷却时间计时器和动作列按钮发出熔岩爆发的辉光"
L["Maelstrom Bar Height"] = "漩涡武器条高度"
L["OOC Alpha"] = "离开战斗透明度"
L["OOC Alpha Desc"] = "离开战斗控制不透明的按钮, 0 = 透明, 1 = 不透明"
L["Show OmniCC counters"] = "显示OmniCC计数"



if( GetLocale() == "zhCN" ) then

TT_GUI_HEADER = "TotemTimers"
TT_GUI_TAB_GENERAL = "基本设置"
TT_GUI_TAB_TIMERS = "计时器设置"
TT_GUI_TAB_TIMERS2 = "快捷键设置"
TT_GUI_TAB_TRACKERS = "追踪器设置"
TT_GUI_TAB_TRACKERS2 = "追踪器设置2"
TT_GUI_TAB_SHOUTS = "随身呼"
TT_GUI_TAB_MESSAGES = "消息提示"

TT_GUI_CHECKSHOW = "显示计时器"
TT_GUI_CHECKLOCK = "锁定计时器位置"
TT_GUI_CHECKTOTEMWARNINGMSG = "到期警报"
TT_GUI_CHECKTOTEMEXPIRATIONMSG = "到期提示"
TT_GUI_CHECKTOTEMDESTROYEDMSG = "被摧毁提示"
TT_GUI_CHECKRECAST = "再次施放"
TT_GUI_CHECKFLASHRED = "红色闪动效果"
TT_GUI_CHECKPROCFLASH = "进度条"
TT_GUI_CHECKTOOLTIPS = "提示信息"
TT_GUI_CHECKMINIICONS = "微型图标"
TT_GUI_CHECKMOUSEOVER = "鼠标停留展开"
TT_GUI_CHECKEARTHSHOUT = "召唤土元素的随身呼"
TT_GUI_CHECKFIRESHOUT = "召唤火元素的随身呼"
TT_GUI_CHECKMANASHOUT = "施放法力之潮的随身呼"
TT_GUI_CHECKSHOWTOTEMSASBUFFS = "在BUFF位置显示图腾计时"
TT_GUI_CHECKSHOWEARTHELEMENTALBUTTON = "显示土元素图腾"
TT_GUI_CHECKSHOWFIREELEMENTALBUTTON = "显示火元素图腾"
TT_GUI_CHECKSHOWMANATIDEBUTTON = "显示法力之潮图腾"
TT_GUI_CHECKTOTEMTWISTING = "显示风怒图腾作用计时"
TT_GUI_CHECKSWITCHAGIWF = "优雅与风怒图腾循环切换"
TT_GUI_CHECKDISABLEMENUDELAY = "禁止菜单延迟"
TT_GUI_CHECKFOCUSELEMENTALS = "元素集中"
TT_GUI_CHECKCOLORTIMERBARS = "彩色时间条"
TT_GUI_CHECKHIDEBLIZZTIMERS = "隐藏游戏自身图腾框体"
TT_GUI_CHECKSHOWCOOLDOWNS = "显示图腾冷却时间"

TT_GUI_CHECKSETCASTTOTEMS = "重新施放上次的图腾"

TT_GUI_TOOLTIPMOUSEOVER = "|cffffd100鼠标停留展开|r|n启用时，图腾按钮当鼠标移到计时器上就会展开(右键摧毁)，否则右键点击计时器时展开(中键摧毁)。" 
TT_GUI_TOOLTIPREINCARNATION = "|cffffd100复生冷却时间|r|n显示复生的技能冷却时间和携带的十字章数量。"
TT_GUI_TOOLTIPMINIICONS = "|cffffd100微型图标|r|n在图腾图标的右下角显示可以再次施放的图腾微型图标。"
TT_GUI_TOOLTIPTOOLTIPS = "|cffffd100提示信息|r|n当鼠标移到计时器或图标上时显示提示信息。"
TT_GUI_TOOLTIPPROCFLASH = "|cffffd100进度条|r|n在计时器中显示绿色的进度条。"
TT_GUI_TOOLTIPFLASHRED = "|cffffd100红色闪动效果|r|n启用的时候图腾即将过期时有红色闪动效果，否则是淡入淡出效果。"
TT_GUI_TOOLTIPRECAST = "|cffffd100再次施放|r|n启用再次施放机制。"
TT_GUI_TOOLTIPEARTHSHOUT = "|cffffd100召唤土元素的随身呼|r|n召唤土元素时发送一条通知， 如果在团队中就向整个团队发送,如果在队伍里就向队伍发送。"
TT_GUI_TOOLTIPFIRESHOUT = "|cffffd100召唤火元素的随身呼|r|n召唤火元素时发送一条通知， 如果在团队中就向整个团队发送,如果在队伍里就向队伍发送。"
TT_GUI_TOOLTIPMANASHOUT = "|cffffd100施放法力之潮的随身呼|r|n施放法力之潮是向队伍发送一条通知"
TT_GUI_TOOLTIPSHOWTOTEMSASBUFFS = "|cffffd100在BUFF位置显示图腾计时|r|n在BUFF框架上显示图腾计时。本功能需要重新载入UI。|n也许会由于你的某些插件导致这个功能不正常."
TT_GUI_TOOLTIPDISABLEMENUDELAY = "禁止当鼠标移开图腾按钮后菜单自动关闭的延迟"
TT_GUI_TOOLTIPFOCUSELEMENTALS = "|cffffd100元素集中|r|n如果开启，双击会施放元素集中。|n需要重载插件使设置生效。（该项目翻译可能有错）"
TT_GUI_TOOLTIPCOLORTIMERBARS = "|cffffd100彩色计时条|r|n根据元素种类进行染色。"
TT_GUI_TOOLTIPSHOWCOOLDOWNS = "|cffffd100显示图腾冷却时间|r|n为冷却时间较长的图腾添加一个冷却计时条。"

TT_GUI_TOOLTIPSETCASTTOTEMS = "|cffffd100重新施放上次的图腾|r|n如果开启，非战斗时使用某图腾后，该图腾将被设为这个系默认使用的图腾，点击图腾条上相应位置即可施放。|n(战斗中使用该系其他图腾不会使得默认设置发生变化!)"

TT_GUI_TIMEFONT = "时间字体"
TT_GUI_TIMERBARTEXTURE = "计时条材质"

TT_GUI_CHECKSHOWTIMERBARS = "显示计时条背景"
TT_GUI_CHECKREVERSEBARBINDINGS = "反转图腾快捷键"
TT_GUI_CHECKBARBINDINGS = "启用图腾快捷键"
TT_GUI_CHECKSHOWPARTYBUFFS = "显示图腾作用到的小队成员"
TT_GUI_CHECKSHOWPLAYERBUFFDOT = "在图腾图标上显示自己是否被作用到"

TT_GUI_CHECKENHANCECDS = "显示增强萨满冷却计时器"
TT_GUI_ECDSIZE = "图标大小"
TT_GUI_ECDTIMEHEIGHT = "计时器高度"
TT_GUI_ECDMAELSTROMHEIGHT = "漩涡武器计时条高度"

TT_GUI_TOOLTIPSHOWBAR = "在计时器时间下显示计时条背景"
TT_GUI_TOOLTIPREVERSEBARBINDINGS = "使快捷键顺序改为9-1|n"
	.."你必须重新登陆以使设置生效。"
TT_GUI_TOOLTIPBARBINDINGS = "如果启用，你可以在展开的图腾动作条上使用1-9快捷键|n"
	.."你必须重新登陆以使设置生效。" 

TT_GUI_DROPDOWN_ARRANGE = "排列"
TT_GUI_VERTICAL = "纵向"
TT_GUI_HORIZONTAL = "横向"
TT_GUI_BOX = "正方"
TT_GUI_FREE = "自由"

TT_GUI_DROPDOWN_STYLE = "样式"
TT_GUI_BUFF = "Buff"
TT_GUI_FIXED = "Fixed"
TT_GUI_ELEMENT = "Element"
TT_GUI_STICKY = "Sticky"

TT_GUI_SPACING = "间距"
TT_GUI_TIMESPACING = "时间间距"
TT_GUI_TRACKERSPACING = TT_GUI_SPACING
TT_GUI_TRACKERTIMESPACING = TT_GUI_TIMESPACING

TT_GUI_DROPDOWN_TIME = "时间样式"
TT_GUI_CT = "ct"
TT_GUI_BLIZZARD = "blizz"

TT_GUI_DROPDOWN_TIMEPOS = "计时条位置"
TT_GUI_DROPDOWN_TRACKERTIMEPOS = TT_GUI_DROPDOWN_TIMEPOS

TT_GUI_DROPDOWN_MSG = "消息样式"
TT_GUI_TT = "TotemTimers"
TT_GUI_SCT = "sct"
TT_GUI_SCT2 = "sct 暴击"
TT_GUI_SCTMSG = "sct静态信息框"
TT_GUI_MSBT = "MSBT"
TT_GUI_PARROT = "Parrot"
TT_GUI_PARROTCRIT = "Parrot 暴击"
TT_GUI_CHAT = "聊天窗口"

TT_GUI_ORDER1 = "计时器1"
TT_GUI_ORDER2 = "计时器2"
TT_GUI_ORDER3 = "计时器3"
TT_GUI_ORDER4 = "计时器4"
TT_GUI_CHECKINMACRO1 = "宏"
TT_GUI_CHECKINMACRO2 = "宏"
TT_GUI_CHECKINMACRO3 = "宏"
TT_GUI_CHECKINMACRO4 = "宏"
TT_GUI_TIMERSIZE = "图标大小"
TT_GUI_TIMEHEIGHT = "时间大小"
TT_GUI_TRACKERSIZE = "图标大小"
TT_GUI_TRACKERTIMEHEIGHT = "时间大小"
TT_GUI_BARDIRECTION = "图腾动作条方向"
TT_GUI_OPENMENU = "展开图腾"

TT_GUI_AUTO = "自动"
TT_GUI_LEFT = "左侧"
TT_GUI_RIGHT = "右侧"
TT_GUI_UP = "上方"
TT_GUI_DOWN = "下方"
TT_GUI_TOP = "顶部"
TT_GUI_BOTTOM = "底部"

TT_GUI_DEBUG = "调试"
TT_GUI_RESET = "重置设置"
TT_GUI_RESETPOS = "缺省位置"

TT_GUI_CHECKANKHTRACKER = "复生计时器"
TT_GUI_CHECKSHIELDTRACKER = "显示盾追踪器"
TT_GUI_CHECKEARTHSHIELDTRACKER = "显示大地之盾追踪器"
TT_GUI_CHECKWEAPONTRACKER = "显示武器特效追踪器"
TT_GUI_CHECKSHIELDMSG = "盾特效到期提示"
TT_GUI_CHECKEARTHSHIELDMSG = "大地之盾提示"
TT_GUI_CHECKWEAPONMSG = "武器特效提示"
TT_GUI_CHECKMAELSTROMMSG = "漩涡武器特效提示"

TT_GUI_WEAPONBUFFLEFTCLICK = "主手([组合键]左键)"
TT_GUI_WEAPONBUFFRIGHTCLICK = "副手([组合键]右键)"
TT_GUI_WEAPONBUFFMODIFIER = "组合键"

TT_GUI_LEFTCLICK = "左键点击"
TT_GUI_RIGHTCLICK = "右键点击"
TT_GUI_MIDDLECLICK = "中键点击"
TT_GUI_BUTTON4CLICK = "鼠标按键4"
TT_GUI_MOUSEOVER = "鼠标指向"
TT_GUI_ALWAYS = "始终显示"

TT_GUI_SHIELDTRACKER = "盾追踪器"
TT_GUI_EARTHSHIELDTRACKER = "大地之盾追踪器"

TT_GUI_HIDE = "隐藏"

TT_GUI_TIMERBARWIDTH = "计时条长度"
TT_GUI_TOTEMMENUSPACING = "图腾菜单间距"

TT_GUI_CHECKCHECKPLAYERRANGE = "玩家距离"
TT_GUI_CHECKCHECKRAIDRANGE = "团队成员距离"
TT_GUI_CHECKSHOWRAIDRANGETOOLTIP = "团队成员距离鼠标提示"
TT_GUI_TOOLTIPCHECKPLAYERRANGE = "|cffffd100玩家距离|r|n如果玩家超出图腾有效范围，在图腾上显示一个红色圆点。"
TT_GUI_TOOLTIPCHECKRAIDRANGE = "|cffffd100团队成员距离|r|n在图腾的左下角显示有多少团队成员未获得该图腾效果。"
TT_GUI_TOOLTIPSHOWRAIDRANGETOOLTIP = "|cffffd100团队成员距离鼠标提示|r|n当你鼠标指向图腾时，在鼠标提示上显示未在该图腾有效范围内的玩家名单。"
TT_GUI_CHECKACTIVATEHIDDENTIMERS = "为已被关闭的追踪项目显示提示信息"
TT_GUI_TOOLTIPACTIVATEHIDDENTIMERS = "|cffffd100为已被关闭的追踪项目显示提示信息|r|n即使追踪已经被关闭，依旧会显示其到期提示信息。"

TT_GUI_ROLE_NAMES = {
		[0]="未知",
		[1]="近战",
		[2]="远程",
		[3]="施法者",
		[4]="治疗",
		[5]="增强"
	}
end