local L = LibStub("AceLocale-3.0"):NewLocale("SimpleILevel", "frFR");

if not L then return end

L.core = {
	ageDays = "%s jours",
	ageHours = "%s heures",
	ageMinutes = "%s minutes",
	ageSeconds = "%s secondes",
	desc = "Ajoute l'iLevel moyen (AiL) à l'infobulle des autres joueurs",
	load = "Chargement v%s",
	minimapClick = "Simple iLevel - cliquer pour les détails.",
	minimapClickDrag = "Cliquer pour déplacer l’icône.",
	name = "Simple iLevel",
	purgeNotification = "Efface %s personnages du cache",
	purgeNotificationFalse = "Vous n'avez pas de purge auto configurée",
	scoreDesc = "Ceci est l'iLevel moyen de votre équipement actuel.",
	scoreYour = "Votre AiL est %s",
	slashClear = "Effacement des paramètres",
	slashGetScore = "%s a un AiL de %s et l'information est agé de %s",
	slashGetScoreFalse = "Désolé, il y a eu une erreur lors de l'obtention du score de %s",
	slashTargetScore = "%s a un AiL de %s",
	slashTargetScoreFalse = "Désolé, il y a eu une erreur lors de la détermination du score de votre cible",
	ttAdvanced = "vieux de %s",
	ttLeft = "iLevel moyen :",
	options = {
		autoscan = "Scan automatique",
		autoscanDesc = "Scan automatiquement les membres du groupe lorsque leur équipement semble changer",
		clear = "Effacer les paramètres",
		clearDesc = "Effacer tous les paramètres et le cache",
		color = "Colorer le score",
		colorDesc = "Colorer l'AiL quand approprié. Désactivé ceci si vous ne voulez voir que des scores blanc et gris",
		get = "Obtenir le score",
		getDesc = "Obtenir l'AiL à partir d'un nom si présent dans le cache",
		ldb = "Options LDB",
		ldbRefresh = "Taux de rafraîchissement",
		ldbRefreshDesc = "A quelle fréquence LDB doit être mis à jour en secondes",
		ldbSource = "Libellé de la source LDB",
		ldbSourceDesc = "Affiche le libellé de la source de données pour le score LDB",
		ldbText = "Texte LDB",
		ldbTextDesc = "Active/désactive LDB, cela va économiser quelques ressources",
		maxAge = "Intervalle maximum de rafraîchissement (minutes)",
		maxAgeDesc = "Définit le laps de temps entre 2 inspection en minutes",
		minimap = "Afficher le bouton sur la minimap",
		minimapDesc = "Active/désactive l'affichage du bouton sur la minimap",
		modules = "Charger les modules",
		modulesDesc = "Pour que ces changements prennent effet vous devez recharger votre interface avec /rl ou /console reloadui",
		name = "Options de Simple iLevel",
		open = "Ouvrir l'interface des options",
		options = "Options de SiL",
		paperdoll = "Afficher sur la feuille de personnage",
		paperdollDesc = "Affiche votre AiL sur la feuille de personnage dans le panneau des stats",
		purge = "Effacer le cache",
		purgeAuto = "Purger automatiquement le cache",
		purgeAutoDesc = "Purge automatiquement les informations se trouvant dans le cache datant de plus de # jours. 0 pour jamais",
		purgeDesc = "Effacer du cache tous les personnages vieux de plus de %s jours",
		purgeError = "Veuillez entrer le nombre de jours",
		round = "Arrondir iLevel",
		roundDesc = "Arrondir le iLevel à la plus proche valeur entière",
		target = "Obtenir le score de votre cible",
		targetDesc = "Obtenir l'AiL de votre cible",
		ttAdvanced = "Infobulle avancée",
		ttAdvancedDesc = "Active/désactive les infobulles avancés, dont l'âge du score",
		ttCombat = "Infobulle en combat",
		ttCombatDesc = "Affiche les informations SiL dans l'info-bulle durant un combat",
	},
}
L.group = {
	addonName = "Simple iLevel - Groupe",
	desc = "Voir l'AiL de chacun dans votre groupe",
	load = "Module Groupe chargé",
	name = "SiL Group",
	nameShort = "Groupe",
	outputHeader = "Simple iLevel : iLevel moyen du groupe = %s",
	outputNoScore = "%s n'est pas disponible",
	outputRough = "* indique un score aproximatif",
	options = {
		group = "Score du groupe",
		groupDesc = "Affiche le score de votre groupe dans <%s>",
	},
}
L.resil = {
	addonName = "Simple iLevel - Résilience",
	desc = "Indique la quantité d'équipement PvP équipé par les autres joueurs dans l'info-bulle",
	load = "Module Résilience chargé",
	name = "SiL Résilience",
	nameShort = "Résilience",
	outputHeader = "Simple iLevel: Equipement PvP moyen du groupe %s",
	outputNoScore = "%s n'est pas disponible",
	outputRough = "* indique un score approximatif",
	ttPaperdoll = "Vous avez %s/%s articles avec un score de résilience de %s",
	ttPaperdollFalse = "Vous n'avez pour l'instant aucun objet JCJ équipé",
	options = {
		cinfo = "Afficher sur la feuille de personnage",
		cinfoDesc = "Affiche votre score de résilience SimpleiLevel dans le volet de statistique.",
		group = "Score PvP par équipe",
		groupDesc = "Indique le score PvP de ton groupe à <%s>",
		name = "SiL Résilience Options",
		pvpDesc = "Afficher l'équipement JCJ de chacun dans votre groupe",
		ttType = "Type d'infobulle",
		ttZero = "Infobulle Zero",
		ttZeroDesc = "Montre l'information dans l'infobulle même s'ils n'ont pas d'équipement JCJ",
	},
}
L.social = {
	addonName = "Simple iLevel - Social",
	desc = "Ajouté le AiL dans le Tchat pour les différents canaux",
	load = "Module social chargé",
	name = "SiL Sociale",
	nameShort = "Sociale",
	options = {
		chatEvents = "Afficher score sur:",
		color = "Colorer le score",
		colorDesc = "Colorer le score dans le fenêtre de discussion",
		enabled = "Activé",
		enabledDesc = "Active toutes les fonctionnalités ou SIL sociaux.",
		name = "SiL Sociale Options",
	},
}


