local L = LibStub("AceLocale-3.0"):NewLocale("SimpleILevel", "koKR");

if not L then return end

L.core = {
	ageDays = "%s 일",
	ageHours = "%s 시간",
	ageMinutes = "%s 분",
	ageSeconds = "%s 초",
	desc = "다른 플레이어의 툴팁에 평균 아이템 레벨(AiL)을 추가합니다.",
	load = "그룹 모듈 로딩",
	minimapClick = "Simple iLevel - 클릭으로 세부사항 표시",
	minimapClickDrag = "클릭 드래그로 아이콘 이동",
	name = "Simple iLevel",
	purgeNotification = "당신의 캐시에서 %s 명 정리",
	purgeNotificationFalse = "자종 정리 설정을 할 필요는 없습니다.",
	scoreDesc = "이것은 당신이 착용한 아이템에 대한 평균 아이템 레벨 값입니다.",
	scoreYour = "당신의 평균 아이템 레벨은 %s 입니다.",
	slashClear = "설정 초기화",
	slashGetScore = "%s님은 %s의 평균 아이템 레벨을 가지고 있으며 이는 %s 의 전의 정보입니다.",
	slashGetScoreFalse = "죄송합니다. %s님의 아이템 레벨을 가져오는 중에 오류가 발생했습니다.",
	slashTargetScore = "%s 님의 평균 아이템레벨은 %s 입니다.",
	slashTargetScoreFalse = "죄송합니다. 대상에 대한 점수 계산 중에 오류가 발생했습니다.",
	ttAdvanced = "%s 지남",
	ttLeft = "평균 아이템 레벨:",
	options = {
		autoscan = "변경 시 자동 스캔",
		autoscanDesc = "장비 변경이 검색될 경우 자동으로 그룹 구성원을 검색합니다.",
		clear = "설정 초기화",
		clearDesc = "모든 설정 및 캐시 초기화",
		color = "스코어 색상화",
		colorDesc = "평균 아이템 색상을 그 위치에 맞게 책정합니다. 만일 흰색 ＆ 회색으로 표시하길 원하시면 이 설정을 끄세요.",
		get = "레벨 가져오기",
		getDesc = "만약 캐시에 저장되어 있다면 해당 이름의 평균 아이템 레벨을 얻을 수 있습니다.",
		ldb = "LDB 설정",
		ldbRefresh = "새로고침 빈도",
		ldbRefreshDesc = "얼마나 자주 LDB의 정보를 업데이트 할 것인지를 초 단위로 설정합니다.",
		ldbSource = "LDB 소스 라벨",
		ldbSourceDesc = "LDB 레벨에 대한 소스 데이터를 LDB 라벨에 표시합니다.\"",
		ldbText = "LDB 문자",
		ldbTextDesc = "LDB를 키거나 끄는 것을 토글합니다.",
		maxAge = "최대 새로고침 간격 (분)",
		maxAgeDesc = "새로고침 사이의 간격을 분 단위로 설정합니다.",
		minimap = "미니맵 버튼 표시",
		minimapDesc = "미니맵 버튼 표시를 토글합니다.",
		modules = "모듈 불러오기",
		modulesDesc = "변경된 사항을 적용하려면 /rl 또는 /console reloadui 명령어로 UI를 재시작해야 합니다.",
		name = "Simple iLevel 설정",
		open = "SiL 설정 UI를 엽니다.",
		options = "SiL 설정",
		paperdoll = "캐릭터 정보 표시",
		paperdollDesc = "캐릭터 창에 평균 아이템 레벨을 표시합니다.",
		purge = "캐시 정리",
		purgeAuto = "자동 캐시 정리",
		purgeAutoDesc = "#일 마다 자동으로 캐시를 정리하도록 설정합니다. 0으로 하면 동작하지 않습니다.",
		purgeDesc = "%s일 마다 캐릭터의 모든 캐시 데이터를 초기화합니다.",
		purgeError = "일 수를 숫자로 입력해주세요.",
		round = "Round iLevel", -- Requires localization
		roundDesc = "Round the iLevel to the nearest whole number", -- Requires localization
		target = "대상 레벨 가져오기",
		targetDesc = "현재 대상의 평균 아이템 레벨을 가져옵니다.",
		ttAdvanced = "확장 툴팁",
		ttAdvancedDesc = "레벨의 기간 정보를 포함하는 툴팁 확장을 토글합니다.",
		ttCombat = "전투중 툴팁 표시",
		ttCombatDesc = "전투 중에도 툴팁에 SiL 정보를 표시합니다.",
	},
}
L.group = {
	addonName = "Simple iLevel - 그룹",
	desc = "모든 그룹원의 평균 아이템레벨 표시",
	load = "그룹 모듈 로딩됨 ",
	name = "SiL 그룹",
	nameShort = "그룹",
	outputHeader = "Simple iLevel: 그룹 평균 %s",
	outputNoScore = "%s|1은;는; 사용할 수 없습니다.",
	outputRough = "* 는 대략적인 레벨을 나타냅니다.",
	options = {
		group = "그룹 레벨",
		groupDesc = "<%s>에 그룹의 레벨을 표시합니다.",
	},
}
L.resil = {
	addonName = "Simple iLevel - 탄력",
	desc = "툴팁에 다른 플레이어가 장착한 PvP 장비에 대한 내용를 표시",
	load = "탄력도 모듈 로딩됨 ",
	name = "SiL 탄력도",
	nameShort = "탄력도",
	outputHeader = "Simple iLevel: 그룹 평균 PvP 장비 %s",
	outputNoScore = "%s|1은;는; 사용할 수 없습니다.",
	outputRough = "* 은 대략적인 점수를 나타냅니다.",
	ttPaperdoll = "당신은 현재 %s/%s 아이템에 탄력도 %s 입니다.",
	ttPaperdollFalse = "당신은 현재 어떤 PvP 아이템도 착용하고 있지 않습니다.",
	options = {
		cinfo = "캐릭터 정보 표시",
		cinfoDesc = "캐릭터 창에 당신의 SimpleiLevel 탄력도 점수를 표시합니다.",
		group = "그룹 PvP 스코어",
		groupDesc = "<%s>에 당신 그룹의 PvP 스코어를 출력합니다.",
		name = "SiL 탄력도 설정",
		pvpDesc = "모든 그룹 구성원의 PvP 장비를 표시합니다.",
		ttType = "툴팁 형식",
		ttZero = "제로 툴팁",
		ttZeroDesc = "PvP 장비가 없을 경우에도 툴팁 정보를 표시합니다.\"",
	},
}
L.social = {
	addonName = "Simple iLevel - 소셜",
	desc = "다양한 채널의 대화창에 평균 아이템 레벨 표시",
	load = "소셜 모듈 로딩됨 ",
	name = "SiL 소셜",
	nameShort = "소셜",
	options = {
		chatEvents = "정보 표시 킴:",
		color = "색상화 표시",
		colorDesc = "대화창에 색상화된 정보를 표시합니다.",
		enabled = "킴",
		enabledDesc = "SiL 소셜 또는 모든 기능을 킵니다.",
		name = "SiL 소셜 설정",
	},
}


