local L = LibStub("AceLocale-3.0"):NewLocale("SimpleILevel", "zhTW");

if not L then return end

L.core = {
	ageDays = "%s天",
	ageHours = "%s小時",
	ageMinutes = "%s分鐘",
	ageSeconds = "%s秒",
	desc = "提示欄顯示其他玩家的平均物品等級",
	load = "載入版本 %s",
	minimapClick = "Simple iLevel - 點擊取得細節",
	minimapClickDrag = "拖曳以移動圖示",
	name = "Simple iLevel",
	purgeNotification = "清除快取內的%s人",
	purgeNotificationFalse = "您未設定自動清除",
	scoreDesc = "這是您所有已裝備物品的平均物品等級。",
	scoreYour = "您的數值 %s",
	slashClear = "清除設定",
	slashGetScore = "%s的平均物品等級為%s（%s前）",
	slashGetScoreFalse = "抱歉，獲取%s的數值時發生錯誤",
	slashTargetScore = "%s的平均物品等級為%s",
	slashTargetScoreFalse = "抱歉，建構數值時發生錯誤",
	ttAdvanced = "%s前",
	ttLeft = "平均物品等級：",
	options = {
		autoscan = "自動掃描",
		autoscanDesc = "切換自動掃描隊伍、團隊變化",
		clear = "清除設定",
		clearDesc = "清除所有設定跟快取",
		color = "上色數值",
		colorDesc = "適時上色平均物品等級，若您只想看到白色或灰色的數值請禁用。",
		get = "獲取數值",
		getDesc = "獲取已記錄玩家的平均物品等級",
		ldb = "LDB選項",
		ldbRefresh = "更新頻率",
		ldbRefreshDesc = "LDB將幾秒更新一次",
		ldbSource = "LDB來源標籤",
		ldbSourceDesc = "顯示LDB數值來源的標籤",
		ldbText = "LDB文字",
		ldbTextDesc = "切換啟用LDB，或可節省些資源",
		maxAge = "最長快取時間",
		maxAgeDesc = "設定檢查間隔時間（分鐘）",
		minimap = "顯示小地圖按鈕",
		minimapDesc = "切換顯示小地圖按鈕",
		modules = "載入模組",
		modulesDesc = "您需重載插件使改動生效，以/rl或/console reloadui指令。",
		name = "SiL選項",
		open = "開啟選項頁面",
		options = "選項",
		paperdoll = "顯示於角色資訊",
		paperdollDesc = "於角色資訊視窗屬性欄顯示平均物品等級。",
		purge = "清除快取",
		purgeAuto = "自動清除快取",
		purgeAutoDesc = "自動清除#天前的快取，0為從不清除",
		purgeDesc = "清除所有超過%s天的角色快取",
		purgeError = "請輸入天數",
		round = "四捨五入",
		roundDesc = "四捨五入數值到整數",
		target = "獲取目標數值",
		targetDesc = "獲取目標的平均物品等級",
		ttAdvanced = "進階提示欄",
		ttAdvancedDesc = "切換顯示檢查間隔時間",
		ttCombat = "戰鬥時顯示",
		ttCombatDesc = "戰鬥時於提示欄顯示SiL資訊",
	},
}
L.group = {
	addonName = "Simple iLevel - 團體",
	desc = "觀看團體所有人的平均物品等級",
	load = "團體模組已載入",
	name = "SiL團體",
	nameShort = "團體",
	outputHeader = "團體平均%s",
	outputNoScore = "%s（未能取得）",
	outputRough = "*表示約略的數值",
	options = {
		group = "團體數值",
		groupDesc = "發佈團體數值到<%s>",
	},
}
L.resil = {
	addonName = "Simple iLevel - 韌性",
	desc = "於提示欄顯示其他玩家裝備幾件PvP裝備",
	load = "韌性模組已載入",
	name = "SiL韌性",
	nameShort = "韌性",
	outputHeader = "團體平均PvP裝備%s",
	outputNoScore = "%s不可用",
	outputRough = "*表示約略的數值",
	ttPaperdoll = "您%s/%s件裝備加總韌性為%s。",
	ttPaperdollFalse = "您目前未裝備任何PvP物品。",
	options = {
		cinfo = "顯示於角色資訊",
		cinfoDesc = "於屬性欄顯示您的SiL韌性數值",
		group = "團體PvP數值",
		groupDesc = "發佈團體PvP數值到<%s>",
		name = "SiL韌性選項",
		pvpDesc = "在您的團體顯示任何有PvP裝備的人。",
		ttType = "提示類型",
		ttZero = "無PvP裝備也顯示",
		ttZeroDesc = "即使無PvP裝備也於提示欄顯示資訊。",
	},
}
L.social = {
	addonName = "Simple iLevel - 社交",
	desc = "於聊天視窗各頻道加入平均物品等級",
	load = "社交模組已載入",
	name = "SiL社交",
	nameShort = "社交",
	options = {
		chatEvents = "顯示數值於：",
		color = "上色數值",
		colorDesc = "於聊天視窗上色數值",
		enabled = "啟用",
		enabledDesc = "啟用所有SiL社交功能",
		name = "SiL社交選項",
	},
}


