if( GetLocale() ~= "esES" ) then return end
local L = {}
L["2D"] = "2D"
L["3D"] = "3D"
L["A"] = "A"
L["Abbreviates unit names above 10 characters, \"Dark Rune Champion\" becomes \"D.R.Champion\" and \"Dark Rune Commoner\" becomes \"D.R.Commoner\"."] = "Abrevia nombres de las unidades de más de 10 carácteres, \"Dark Runa Champion\" se convierte en \"DRChampion\" y \"Dark Runa Commoner\" se convierte en \"DRCommoner\"." -- Needs review
L["Absolute incoming heal value, if 10,000 healing is incoming it will show 10,000."] = "Valor absoluto cura entrante, si la curación es de entrada 10000 se mostrará 10.000." -- Needs review
L["Add"] = "Añade"
L["Add aura"] = "Adicionar aura" -- Needs review
L["Add Aura"] = "Adicionar Aura" -- Needs review
L["Add Indicator"] = "Adicionar Indicador" -- Needs review
L["Add link"] = "Adicionar vinculo" -- Needs review
L["Add new indicator"] = "Adicionar nuevo indicador" -- Needs review
L["Add new tag"] = "Añadir nueva etiqueta"
L["Add new text"] = "Añade nuevo texto"
L["Adds a bar indicating how much time is left on your ghoul timer, only used if you do not have a permanent ghoul."] = "Agrega una barra que indica cuánto tiempo queda en el cronómetro de tu demonio, sólo se utiliza si no tiene un demonio permanente." -- Needs review
L["Adds a bar indicating how much time is left on your Rune of Power."] = "Adicionar una barra indicando cuanto tiempo le queda a su Runa de Poder" -- Needs review
L["Adds an empty bar that you can put text into as a way of uncluttering other bars."] = "Agrega una barra vacía que se puede poner texto, de forma que despeja otras barras." -- Needs review
L["Adds another mana bar to the player frame when you are in Bear or Cat form showing you how much mana you have."] = "Añade otra barra de maná al marco jugador cuando está en forma de oso o gato mostrando la cantidad de maná que tiene." -- Needs review
L["Adds %s to the list of units to be modified when you change values in this tab."] = "Añade %s a la lista de unidades para ser modificadas cuando cambias el valor en esta pestaña"
L["Add Tags"] = "Adicionar Marcador" -- Needs review
L["Advanced"] = "Avanzado"
L["AFK"] = "AUS"
L["AFK:%s"] = "AUS:%s"
L["AFK status"] = "Estado AUS"
L["AFK timer"] = "Tiempo AUS"
L["Aggro"] = "Amenaza"
L["All Auras"] = "Todas las Auras" -- Needs review
L["Ammo"] = "Munición"
L["Amount of power missing,  if none is missing nothing is shown. Uses a short format, -13850 is shown as 13.8k, values below 10000 are formatted as is."] = "Cantidad de energía que falta, si no hay ninguna falta no se muestra nada. Utiliza un formato corto, -13.850 se muestra como 13.8k, valores por debajo de 10.000 están en este formato." -- Needs review
L["Anchor point"] = "Punto de anclaje"
L["Anchor to"] = "Anclado a"
L["Anchor to another frame"] = "Anclado a otro marco"
L["Anchor to buffs"] = "Anclado a los buffs"
L["Anchor to debuffs"] = "Anclado a los debuff"
L["Aquatic"] = "Acuático"
L["Arena"] = "Arena"
L["Arenas"] = "Arenas"
L["Are you sure you want to delete this filter?"] = "¿Está seguro que desea eliminar este filtro?"
L["Are you sure you want to delete this tag?"] = "¿Está seguro que desea eliminar esta etiqueta?"
L["Are you sure you want to delete this text? All settings for it will be deleted."] = "¿Está seguro que desea eliminar este texto? Todos los ajustes de este serán eliminados" -- Needs review
L["Ascending"] = "Ascendente"
L["Assigned Role (DPS/Tank/etc)"] = "Rol Asignado (Rango/tanque/etc.)" -- Needs review
L["Aura borders"] = "Bordes de Aura" -- Needs review
L["Aura border style"] = "Estilo del borde del Aura"
L["Aura Combo Points"] = "Puntos de Combo de Aura" -- Needs review
L["Aura filters"] = "Filtros de Auras"
L["Aura Filters"] = "Filtro de Aura" -- Needs review
L["Aura group"] = "Grupo de aura" -- Needs review
L["Aura groups"] = "Grupos de aura" -- Needs review
L["Aura Groups"] = "Grupos de Auras" -- Needs review
L["Aura indicators"] = "Indicadores de Auras" -- Needs review
L["Aura Indicators"] = "Indicadores de Auras" -- Needs review
L["Aura name"] = "Nombre del Aura"
L["Auras"] = "Auras"
L["Aura types to filter"] = "Filtro de tipo de Auras"
L["Automatic Auras"] = "Auras automaticas  " -- Needs review
L["B"] = "B"
L["Background"] = "Fondo"
L["Background alpha"] = "Trasparencia del fondo"
L["Background/border"] = "Fondo/contorno"
L["Background color"] = "Color del fondo"
L["Bag indicator for master looters."] = "Bolsa indicadora para Maestro despojador" -- Needs review
L["Bars"] = "Barras"
L["Bar spacing"] = "Espacio entre barras" -- Needs review
L["Bar texture"] = "Textura de barras"
L["Battlegrounds"] = "Campos de Batalla"
L["Bear"] = "Oso"
L["BG"] = "CB" -- Needs review
L["BG Pet"] = "Mascota CB" -- Needs review
L["Blacklist"] = "Lista negra"
L["Blacklist filters"] = "Filtro de Lista negra"
L["Blacklists"] = "Listas negras" -- Needs review
L["Blizzard"] = "Blizzard"
L["Border"] = "Contorno"
L["Border alpha"] = "trasparencia contorno "
L["Border color"] = "Color del contorno "
L["Border highlighting"] = "Resaltado contorno "
L["Border thickness"] = "Grosor contorno"
L["Boss"] = "Jefe"
L["Boss Auras"] = "Auras del Jefe" -- Needs review
L["Boss Debuffs"] = "Debufos del Jefe" -- Needs review
L["Boss units are for only certain fights, such as Blood Princes or the Gunship battle, you will not see them for every boss fight."] = "Unidades de Jefes son sólo para ciertas luchas, como los Princesa Sangrienta o de la batalla Gunship, no los vera para cada lucha del jefes."
L["Both"] = "Ambos"
L["Bottom"] = "Abajo"
L["Bottom Center"] = "Abajo centro"
L["Bottom Left"] = "Abajo izquierda"
L["Bottom Right"] = "Abajo derecha"
L["buff frames"] = "Marcos de Bufos" -- Needs review
L["Buffs"] = "Buffs"
L["C"] = "C"
L["Cast"] = "Lanzar" -- Needs review
L["Cast bar"] = "Barra de lanzar" -- Needs review
L["Cast icon"] = "Icono de lanzar" -- Needs review
L["Casting"] = "Lanzando" -- Needs review
L["Cast interrupted"] = "Lanzar Interrumpido" -- Needs review
L["Cast name"] = "Nombre de Hechizo" -- Needs review
L["Cast time"] = "Tiempo lanzar" -- Needs review
L["Cast uninterruptible"] = "Lanzar ininterrumpible" -- Needs review
L["Cat"] = "Gato"
L["Category"] = "Categoría"
L["Center"] = "Centro"
L["Changes the health bar to the set hostile color (Red by default) when the unit takes aggro."] = "Cambia la barra de salud para el juego de colores hostil (rojo por defecto) cuando la unidad tiene agresividad." -- Needs review
L["Changes this widget into a bar, you will be able to change the height and ordering like you can change health and power bars."] = "Cambia este aplicación en una barra, que será capaz de cambiar la altura y ordenar como se puede cambiar las barras de salud y poder." -- Needs review
L["Channelling"] = "Canalizando"
L["Child units cannot be dragged, you will have to reposition them through /shadowuf."] = "Unidades filiales no se puede arrastrar, que tendrá que cambiar la posición a través de / shadowuf." -- Needs review
L["Chi Points"] = "Puntos de Chi" -- Needs review
L["Class"] = "Clase"
L["Class color tag"] = "Etiqueta de color de clase"
L["Classes"] = "Clases"
L["Class icon"] = "Icono de clase"
L["Classification"] = "Classificación" -- Needs review
L["Classifications"] = "Clasificaciones"
L["Class name without coloring, use [classcolor][class][close] if you want the class name to be colored by class."] = "Nombre de la clase sin color, utilice [classcolor][class][close] si desea que el nombre de la clase que esté influido por la clase." -- Needs review
L["Class (Smart)"] = "Clase (inteligente)"
L["Clip"] = "sujetar" -- Needs review
L["Close color"] = "Cierra color" -- Needs review
L["Closes a color code, prevents colors from showing up on text that you do not want it to."] = "Cierra un código de color, evita que los colores a aparecer en el texto que usted no quiere que lo haga." -- Needs review
L["Code"] = "Código" -- Needs review
L["Color by class"] = "Color por clase" -- Needs review
L["Color by reaction on"] = "Color por reacción en" -- Needs review
L["Color code based on percentage of HP left on the unit, this works the same way as the color by health option. But for text instead of the entire bar."] = "Código de color en función del porcentaje de Salud a la izquierda en la unidad, esto funciona de la misma forma como el color de la opción de la salud. Pero para el texto en lugar de la barra entera." -- Needs review
L["Color code for general situation"] = "Código de color para situación general" -- Needs review
L["Color code for situation"] = "Código de color para situación" -- Needs review
L["Color code for the class, use [classcolor][class][close] if you want the class text to be colored by class"] = "Código de color por clase, utilice [classcolor][class][close] si desea que el texto de la clase esté influido por la clase" -- Needs review
L["Color code on aggro"] = "Codigo de color en agresivo" -- Needs review
L["Color health by"] = "Color de salud por" -- Needs review
L["Color on aggro"] = "Color en agresivo" -- Needs review
L["Colors"] = "Colores" -- Needs review
L["Color to use for health bars that are set to be colored by a static color."] = "Color a utilizar para las barras de salud que se establecen para ser coloreado con un color estático." -- Needs review
L["Color used when a cast cannot be interrupted, this is only used for PvE mobs."] = "Color que se utiliza cuando una lanzamiento no puede ser interrumpido, esta sólo se utiliza para las multitudes PvE." -- Needs review
L["Color used when a cast is a channel."] = "Color que se utiliza cuando un lanzamiento es una canalización." -- Needs review
L["Color used when an unit is casting a spell."] = "Color usado cuando una unidad esta casteando un hechizo" -- Needs review
L["Column growth"] = "Crecimiento de Columna" -- Needs review
L["Column spacing"] = "Separación de columna " -- Needs review
L["Combat alpha"] = "Trasparencia en Combate" -- Needs review
L["Combat fader"] = "Atenua en combate" -- Needs review
L["Combat fader will fade out all your frames while they are inactive and fade them back in once you are in combat or active."] = "Atenua en combate desvanecerá todos sus marcos, mientras que esta inactiva y desaparece de nuevo una vez que esté en combate o en activo." -- Needs review
L["Combat/resting status"] = "Combate/descanso estado" -- Needs review
L["Combat text"] = "Texto de combate" -- Needs review
L["Combo points"] = "Puntos de combo" -- Needs review
L["Combo Points"] = "Puntos de Combo" -- Needs review
L["Configuration to specific unit frames."] = "Configuración de unidades de marco especifico" -- Needs review
L["Create"] = "Crear" -- Needs review
L["Creature type"] = "Tipo de Criatura" -- Needs review
L["Curable Auras"] = "Auras Curables" -- Needs review
L["Cur/Max HP (Absolute)"] = "Actual/Máximo HP (Absoluto)" -- Needs review
L["Cur/Max HP (Short)"] = "Actual/Máximo HP (Corto)" -- Needs review
L["Cur/Max power (Druid)"] = "Actual/Máximo Mana (Druida)" -- Needs review
L["Cur/Max Power (Short)"] = "Actual/Máximo Mana (Corto)" -- Needs review
L["Current and maximum power, formatted as [curpp]/[maxpp]."] = "Actual y Máximo Mana, tienen el formato [curpp]/[maxpp]" -- Needs review
L["Current Eclipse, <0 is Lunar Energy and >0 is Solar Energy."] = "Eclipse activo, <0 es Eclipse Lunar y >0 es Energia Solar" -- Needs review
L["Current health (Druid/Absolute)"] = "Actual Salud (Druida/Absoluto)" -- Needs review
L["Current HP (Absolute)"] = "Actual HP (Absoluto)" -- Needs review
L["Current HP (Short)"] = "Actual HP (Corto)" -- Needs review
L["Currently modifying"] = "Actualmente modificando" -- Needs review
L["Current power (Absolute)"] = "Actual Mana (Absoluto)" -- Needs review
L["Current power (Druid)"] = "Actual Mana (Druida)" -- Needs review
L["Current power (Druid/Absolute)"] = "Actual Mana (Druida/Absoluto)" -- Needs review
L["Current Power (Short)"] = "Actual Mana (Corto)" -- Needs review
L["Damage absorption (Absolute)"] = "Absorción de Daño (Absoluto)" -- Needs review
L["Damage absorption/Name"] = "Absorción de Daño/Nombre" -- Needs review
L["Damage absorption (Short)"] = "Absorción de Daño (Corto)" -- Needs review
L["Dark"] = "Oscuro" -- Needs review
L["%d auras in group"] = "%s auras en el grupo" -- Needs review
L["Dead"] = "Muerto" -- Needs review
L["Debuffs"] = "Debufos" -- Needs review
L["Decimal percent HP"] = "Porcentaje decimal HP" -- Needs review
L["Delete"] = "Borrar" -- Needs review
L["Delete filter"] = "Borrar filtros " -- Needs review
L["Delete link"] = "Borrar unión " -- Needs review
L["Descending"] = "Descendiente" -- Needs review
L["Disable Auras by Class"] = "Desactivar Auras por Clases" -- Needs review
L["Disabled"] = "Desactivado" -- Needs review
L["Disabled for %s."] = "Desactivado para %s" -- Needs review
L["Disabled in %s"] = "Desactivado en %s" -- Needs review
L["Disable vehicle swap"] = "Intercambio de vehículos descativado" -- Needs review
L["Display"] = "Mostrar" -- Needs review
L["Documentation"] = "Documentación " -- Needs review
L["Don't hide when empty"] = "No mostrar cuando este vacio" -- Needs review
L["Don't use a filter"] = "No usar filtros" -- Needs review
L["Down"] = "Abajo" -- Needs review
L["Druid form"] = "Forma del Druida" -- Needs review
L["Druid form (Short)"] = "Forma del Druida (Corto)" -- Needs review
L["Druid mana bar"] = "Barra de Mana del Druida" -- Needs review
L["Eclipse bar"] = "Barra de Eclipse" -- Needs review
L["Eclipse (Druid)"] = "Eclipse (Druida)"
L["Eclipse (Sun)"] = "Eclipse (Solar)" -- Needs review
L["Editing %s"] = "Editando %s" -- Needs review
L["Edit tag"] = "Editar marca" -- Needs review
L["Empty bar"] = "Barra vacia" -- Needs review
L["Enable buffs"] = [=[Bufos activados
]=] -- Needs review
L["Enable debuffs"] = "Defubos activados" -- Needs review
L["Enabled for %s."] = "activados para %s" -- Needs review
L["Enabled in %s"] = "Activado en %s" -- Needs review
L["Enabled Units"] = "Unidades Activadas" -- Needs review
L["Enable for friendlies"] = "activados para amigables" -- Needs review
L["Enable for hostiles"] = "activados para hostiles" -- Needs review
L["Enable frequent updates"] = "Activado frecuencia de actualización " -- Needs review
L["Enable indicator"] = "Indicador de activado" -- Needs review
L["Enable Indicators"] = "Indicadores activados" -- Needs review
L["Enable %s"] = "Activado %s" -- Needs review
L["Enable temporary enchants"] = "Encantamientos temporarios activados" -- Needs review
L["Enable units"] = "Unidades activadas" -- Needs review
L["Energy"] = "Energía" -- Needs review
L["Error"] = "Error" -- Needs review
L["Events"] = "Eventos" -- Needs review
L["Export"] = "Exportar" -- Needs review
L["F"] = "F" -- Needs review
L["Failed to load ShadowedUF_Options, cannot open configuration. Error returned: %s"] = "Error intentando cargar ShadowedUF_Options, no se pudo abrir la configuración. Error recibido: %s" -- Needs review
L["Female"] = "Femenino" -- Needs review
L["Filtering buffs only"] = "Filtrando solo bufos" -- Needs review
L["Filtering debuffs only"] = "Filtrando solo debufos " -- Needs review
L["Filters"] = "Filtros" -- Needs review
L["Finished cast"] = "Casteo terminado" -- Needs review
L["Flight"] = "Volar" -- Needs review
L["Focus"] = "Focus" -- Needs review
L["Font"] = "Letra" -- Needs review
L["For target/focus"] = "Para objetivo/focus" -- Needs review
L["Frame"] = "Marco" -- Needs review
L["Frames"] = "Marcos" -- Needs review
L["Friendly"] = "Amigable" -- Needs review
L["Fuel"] = "Combustible" -- Needs review
L["Full size after"] = "Tamaño completo después " -- Needs review
L["Full size before"] = "Tamaño completo antes " -- Needs review
L["General"] = "General" -- Needs review
L["General configuration to all enabled units."] = "Configuración general a todas las unidades activadas" -- Needs review
L["Ghost"] = "Fantasma " -- Needs review
L["Global"] = "General" -- Needs review
L["Green (<30% HP)"] = "Verde (<30% HP)" -- Needs review
L["Group by"] = "Grupos por" -- Needs review
L["Group %d"] = "Grupo %d" -- Needs review
L["Group number"] = "Numero de grupo " -- Needs review
L["Groups"] = "Grupos" -- Needs review
L["Groups to show"] = "Grupos a mostrar" -- Needs review
L["Growth"] = "Crecimiento" -- Needs review
L["Guild name"] = "Nombre de Hermandad" -- Needs review
L["Half health"] = "Salud media" -- Needs review
L["Has Aggro"] = "Tiene Aggro"
L["Heal absorb"] = "Sanación Absorvida" -- Needs review
L["Heal Absorb (Absolute)"] = "Sanación Absorvida (Absoluta)" -- Needs review
L["Heal absorbs"] = "Sanaciones Absorvidas" -- Needs review
L["Heal Absorb (Short)"] = "Sanación Absorvida (Corto)" -- Needs review
L["Health"] = "Salud" -- Needs review
L["Health bar"] = "Barra de salud" -- Needs review
L["Health bar color for friendly units."] = "Color de barra de salud para unidades amigas" -- Needs review
L["Health bar color for hostile units."] = "Color de barra de salud para unidades hostiles" -- Needs review
L["Health bar color for neutral units."] = "Color de barra de salud para unidades neutrales" -- Needs review
L["Health color"] = "Color de Salud" -- Needs review
L["Health percent"] = "Porcentaje de Salud" -- Needs review
L["Help"] = "Ayuda" -- Needs review
L["Hide bar when empty"] = "Ocultar barra cuando esté vacía" -- Needs review
L["Hide Blizzard"] = "Ocultar Blizzard" -- Needs review
L["Hide in any raid"] = "Ocultar en cualquier raid" -- Needs review
L["Hide %s"] = "Ocultar %s" -- Needs review
L["Hide %s frames"] = "Ocultar %s marcos" -- Needs review
L["Hide tooltips in combat"] = "Ocultar tooltips en combate" -- Needs review
L["High"] = "Alta " -- Needs review
L["High health"] = "Salud alta" -- Needs review
L["Holy Power"] = "Poder SAgrado" -- Needs review
L["Icon Size"] = "Tamaño del icono" -- Needs review
L["Import"] = "Importar" -- Needs review
L["Import unit frame positions"] = "Importar posiciones de la unidad de marcos" -- Needs review
L["Inactive alpha"] = "Alpha inactivo" -- Needs review
L["Incoming absorb"] = "Absorciones entrantes" -- Needs review
L["Incoming absorbs"] = "Absorciones entrantes" -- Needs review
L["Incoming heal"] = "Sanación entrante" -- Needs review
L["Incoming heal (Absolute)"] = "Sanación Entrante (Absoluta)" -- Needs review
L["Incoming heal/Name"] = "Sanación entrante/Nombre" -- Needs review
L["Incoming heal (Percent)"] = "Sanación entrante (Porcentaje)" -- Needs review
L["Incoming heals"] = "Sanaciones entrantes" -- Needs review
L["Incoming heal (Short)"] = "Sanación entrante (Corto)" -- Needs review
L["Index"] = "Indice" -- Needs review
L["Indicator color"] = "Color del indicador" -- Needs review
L["Indicator name"] = "Nombre del indicador" -- Needs review
L["Indicators"] = "Indicadores" -- Needs review
L["In range alpha"] = "En rango alpha" -- Needs review
L["Interrupted"] = "Interrumpido" -- Needs review
L["Invalid interval entered, must be a number."] = "Carácter ingresado invalido, debe ser un numero " -- Needs review
L["Invalid spell \"%s\" entered."] = "Hechizo invalido %s ingresado" -- Needs review
L["Leader / Assist"] = "Lider/Asistente" -- Needs review
L["Left"] = "Izquierda" -- Needs review
L["Left Bottom"] = "Izquierda abajo" -- Needs review
L["Left Center"] = "Izquierda centro" -- Needs review
L["Left Top"] = "Izquierda arriba" -- Needs review
L["Level"] = "Nivel" -- Needs review
L["Level %s - %s: %s/%s (%.2f%% done)"] = "Nivel %s - %s: %s/%s (%.2f%% hecho)" -- Needs review
L["Level %s - %s: %s/%s (%.2f%% done), %s rested."] = "Nivel %s - %s: %s/%s (%.2f%% hecho) %s restante." -- Needs review
L["Light"] = "Luz" -- Needs review
L["Link"] = "Unir" -- Needs review
L["Linked spells"] = "Hechizos encadenados" -- Needs review
L["Link from"] = "Unir desde " -- Needs review
L["Link to"] = "Unir a " -- Needs review
L["Low health"] = "Salud baja" -- Needs review
L["M"] = "M" -- Needs review
L["Male"] = "Masculino" -- Needs review
L["Minion"] = "Subdito" -- Needs review
L["New aura group"] = "Nuevo grupo de auras" -- Needs review
L["None (Disabled)"] = "Ninguno (Desactivado)" -- Needs review
L["On %s units"] = "Sobre %s unidades" -- Needs review
L["Players will be colored by class."] = "Jugadores serán coloreados por clase" -- Needs review
L["Positioning"] = "Posicionamiento" -- Needs review
L["Priority"] = "Prioridad" -- Needs review
L["PvP Flag"] = "Bandera PVP" -- Needs review
L["PvP Flags"] = "Marcadores PVP" -- Needs review
L["Red (>70% HP)"] = "Rojo (>70% HP)" -- Needs review
L["Rune of Power"] = "Runa de Poder" -- Needs review
L["Rune of Power bar"] = "Barra de Runa de Poder" -- Needs review
L["%s aura groups disabled"] = "%s auras en el grupo desactivadas" -- Needs review
L["%s frames"] = "%s marcos"
L["Shadow Orbs"] = "Orbes de las Sombras" -- Needs review
L["Show any other auras"] = "Mostrar cualquier otras auras" -- Needs review
L["Show aura duration"] = "Mostrar duración del aura" -- Needs review
L["Show aura icon"] = "Mostrar icono del aura" -- Needs review
L["Show auras stack"] = "Mostrar acumulaciones de auras" -- Needs review
L["Show boss debuffs"] = "Mostrar debufos del Jefe" -- Needs review
L["Show casted by boss"] = "Mostrar casteos del Jefe" -- Needs review
L["Show consolidable auras"] = "Mostrar auras consolidadas" -- Needs review
L["Show curable debuffs"] = "Mostrar debufos curables" -- Needs review
L["Show curable/removable auras"] = "mostrar auras curables/removibles" -- Needs review
L["Show Heal Absorbs"] = "Mostrar Sanaciones absorvidas" -- Needs review
L["Show icon durations"] = "Mostrar duraciones en iconos" -- Needs review
L["Show incoming absorbs"] = "Mostrar absorciones entrantes" -- Needs review
L["Show incoming heals"] = "Mostrar sanaciones entrantes" -- Needs review
L["Shows debuffs cast by a boss."] = "Mostrar debufos casteados por el Jefe" -- Needs review
L["Shows debuffs that you can cure."] = "Mostrar los debufos que ud, puede curar" -- Needs review
L["Show your auras"] = "Mostrar auras propias" -- Needs review
L["Size"] = "TAmaño" -- Needs review
L["%s member"] = "%s miembro"
L["Spell ID %s"] = "ID hechizo %s" -- Needs review
L["Spell Name/ID"] = "Nombre de hechizo/ID" -- Needs review
L["%s (%s): %s/%s (%.2f%% done)"] = "%s (%s): %s/%s (%.2f%% hecho)"
L["Statue"] = "Estado" -- Needs review
L["Statue bar"] = "Barra de Estado" -- Needs review
L["Status"] = "Estado" -- Needs review
L["Top"] = "Arriba" -- Needs review
L["Unit Configuration"] = "Configuración de Unidades" -- Needs review
L["Unknown"] = "Desconocido" -- Needs review
L["Yellow (>30% HP)"] = "Amarillo (>30% HP)" -- Needs review
L["Your aura color"] = "Sus colores de auras" -- Needs review
L["Your Auras"] = "Sus auras" -- Needs review
L["Zone Configuration"] = "Configuración de Zonas" -- Needs review

local ShadowUF = select(2, ...)
ShadowUF.L = setmetatable(L, {__index = ShadowUF.L})
