if( GetLocale() ~= "esMX" ) then return end
local L = {}
L["2D"] = "2D" -- Needs review
L["3D"] = "3D" -- Needs review
L["A"] = "A"
L["Abbreviates unit names above 10 characters, \"Dark Rune Champion\" becomes \"D.R.Champion\" and \"Dark Rune Commoner\" becomes \"D.R.Commoner\"."] = "Abrevia nombres de unidades con mas que 10 letros.  \"Campeón Runa Oscura\" se convertirá a \"Campeón R.O.\" y \"Plebeyo Runa Oscura\" se convertirá a \"Plebeyo R.O.\""
L["Absolute incoming heal value, if 10,000 healing is incoming it will show 10,000."] = "Valor absoluto de curación entrante.  Si 10.000 curación llegará, mostrará 10.000."
L["Add"] = "Añadir"
L["Add new tag"] = "Añadir nueva etiqueta."
L["Add new text"] = "Añadir nuevo texto."
L["Adds a bar indicating how much time is left on your ghoul timer, only used if you do not have a permanent ghoul."] = "Añade una barra que indica cuanto tiempo aún permanece del temporizador del necrófago.  Solo se usa si no tienes un necrófago permanente"
L["Adds a bar indicating how much time is left on your mushrooms."] = "Agrega una barra indicando el tiempo restante de sus hongos" -- Needs review
L["Adds a bar indicating how much time is left on your Rune of Power."] = "Agrega una barra que indica cuánto tiempo queda en su runa de poder." -- Needs review
L["Adds a bar inside the health bar indicating how much damage will be absorbed."] = "Agrega una barra dentro de la barra de vida indicando cuanto daño será absorbido" -- Needs review
L["Adds a bar inside the health bar indicating how much healing someone will receive."] = "Agrega una barra dentro de la barra de vida indicando cuanta sanación recibirá alguien." -- Needs review
L["Adds an empty bar that you can put text into as a way of uncluttering other bars."] = "Añade una barra vacía en que puedes insertar mas texto sin hacer un lío de otras barras."
L["Adds another mana bar to the player frame when you are in Bear or Cat form showing you how much mana you have."] = "Añade otra barra de mana al retrato del jugador cuando estás en forma de oso o forma felina que te muestra cuanta mana tienes."
L["Adds rune bars and timers before runes refresh to the player frame."] = "Añade barras y temporizadores de runas al retrato del jugador antes se restaura las runas."
L["Adds %s to the list of units to be modified when you change values in this tab."] = "Añade %s a la lista de unidades para ser modificados cuando cambias los valores en esta etiqueta."
L["Adds temporary enchants to the buffs for the player."] = "Añade encantamientos temporarios a las bendiciones sobre el jugador."
L["Adds totem bars with timers before they expire to the player frame."] = "Añade barras y temporizadores del tótem al cuadro del jugadores antes de expirar."
L["Advanced"] = "Avanzado"
L["Advanced tag management, allows you to add your own custom tags."] = "Manejo avanzado de las etiquetas.  Te permite añadir tus propias etiquetas personalizadas."
L["AFK"] = "Ausente"
L["AFK:%s"] = "Ausente:%s"
L["AFK status"] = "Estado ausente"
L["AFK timer"] = "Temporizador de estar ausente"
L["After you hit export, you can give the below code to other Shadowed Unit Frames users and they will get your exact layout."] = "Una vez que le des Clic en Exportar, puedes dar el código abajo mostrado a otro Usuario de Shadowed Unit Frames y tendrán la misma configuración."
L["Aggro"] = "Aggro"
L["Alpha to use for bar backgrounds."] = "Opacidad en uso para el fondo de las barras." -- Needs review
L["Alt. Power bar"] = "Barra de Poder Alternativa" -- Needs review
L["Ammo"] = "Munición"
L["Amount of health missing, if none is missing nothing is shown. Uses a short format, -18500 is shown as -18.5k, values below 10000 are formatted as is."] = "Cantidad de salud que falta.  Si no falta salud, nada se muestra.  Usa un formato corto, -18500 se muestra como -18.5m(mil), valores menos que 10000 no cambian."
L["Amount of power missing,  if none is missing nothing is shown. Uses a short format, -13850 is shown as 13.8k, values below 10000 are formatted as is."] = "Cantidad de poder (mana, ira, poder rúnico, energía) que falta.  Si no falta poder, nada se muestra.  Usa un formato corto, -13850 se muestra como 13.8m(mil), valores menos que 10000 no cambian.  "
L["Anchor point"] = "Punto de fijar"
L["Anchor to"] = "fijar a"
L["Anchor to another frame"] = "fijar a otro cuadro"
L["Anchor to buffs"] = "fijar a bendiciones"
L["Anchor to debuffs"] = "fijar a maldiciones"
L["Aquatic"] = "Acuática "
L["Arena"] = "Arena"
L["Arenas"] = "Arenas"
L["Are you sure you want to delete this filter?"] = "¿Estás seguro(a) que quieres borrar este filtro?"
L["Are you sure you want to delete this tag?"] = "¿Estás seguro(a) que quieres borrar esta etiqueta?"
L["Are you sure you want to delete this text? All settings for it will be deleted."] = "¿Estás seguro(a) que quieres borrar este texto?  Todas sus configuraciones se borrará."
L["Ascending"] = "Ascendiendo"
L["Assigned Role (DPS/Tank/etc)"] = "Rol Asignado (Dps/Tanque/Sanador)" -- Needs review
L["Aura borders"] = "Bordes de aura" -- Needs review
L["Aura border style"] = "Estilo del borde de las auras."
L["Aura filters"] = "Filtros de las auras."
L["Aura name"] = "Nombre de la aura."
L["Auras"] = "Auras."
L["Aura types to filter"] = "Tipos de auras para filtrar."
L["B"] = "B"
L["Background"] = "Fondo"
L["Background alpha"] = "Opacidad del fondo" -- Needs review
L["Background/border"] = "Fondo/borde"
L["Background color"] = "Color del fondo"
L["Bag indicator for master looters."] = "indicador de bolsas para los maestros de despojas."
L["Bar color to use to show how much healing someone is about to receive."] = "Color de la barra que se utilizará para mostrar la cantidad de sanación que alguien está a punto de recibir." -- Needs review
L["Bars"] = "barras"
L["Bar spacing"] = "espaciamiento de las barras"
L["Bar texture"] = "textura de las barras"
L["Battlegrounds"] = "Campos de Batalla"
L["Bear"] = "Oso"
L["Blacklist"] = "Lista negra"
L["Blacklist filters"] = "Filtros de la lista negra"
L["Blacklists"] = "Listas negras"
L["Blizzard"] = "Blizzard"
L["Border"] = "Borde"
L["Border alpha"] = "Opacidad del borde" -- Needs review
L["Border color"] = "Color del borde"
L["Border highlighting"] = "Brillo del borde"
L["Border thickness"] = "Densidad del borde."
L["Boss"] = "Jefe"
L["Boss units are for only certain fights, such as Blood Princes or the Gunship battle, you will not see them for every boss fight."] = "Las unidades de jefe solo muestran durante luchas especificas, como los príncipes de sangre o Arsenal de la nave de guerra.  No las verás en cada lucha contra jefe."
L["Both"] = "Ambos(as)"
L["Bottom"] = "Bajo"
L["Bottom Center"] = "Bajo y centro"
L["Bottom Left"] = "Bajo y a la izquierda"
L["Bottom Right"] = "Bajo y a la derecha"
L["buff frames"] = "Marcos de beneficios" -- Needs review
L["Buffs"] = "Bendiciones"
L["C"] = "C"
L["Cannot find any profiles named \"%s\"."] = "No se encuentra ningún perfil llamado \"%s\"." -- Needs review
L["Cast"] = "Lanzar (verb) Lanzamiento (noun)"
L["Cast bar"] = "Barra de lanzamiento"
L["Cast icon"] = "Icono del lanzamiento"
L["Casting"] = "Lanzando"
L["Cast interrupted"] = "Lanzamiento interrumpido"
L["Cast name"] = "Nombre del lanzamiento"
L["Cast time"] = "Tiempo del lanzamiento"
L["Cast uninterruptible"] = "Lanzamiento ininterrumpible"
L["Cat"] = "Gato (Felino if druid)"
L["Category"] = "Categoría "
L["Center"] = "Centro"
L["|cff20ff20%s|r units enabled"] = "|cff20ff20%s|r unidades habilitados" -- Needs review
L["|cffff2020%s|r units disabled"] = "|cffff2020%s|r unidades deshabilitadas" -- Needs review
L["|cffff2020Warning!|r Some units have overrides set in zone configuration, and may show (or not show up) in certain zone. Regardless of the settings below."] = "|cffff2020Atención!|r Algunas unidades tienen anulaciones establecidas en la configuración por zona y pueden mostrarse (o no mostrarse) in ciertas zonas, Sin importar la configuración de abajo." -- Needs review
L["Changes the health bar to the set hostile color (Red by default) when the unit takes aggro."] = "Cambia el color de la barra de salud al color hostil (rojo por defecto) cuando un enemigo da aggro a la unidad."
L["Changes this widget into a bar, you will be able to change the height and ordering like you can change health and power bars."] = "Cambia este widget en una barra asi que podrás cambiar la altura y orden como puedes cambiar a las barras de salud y poder."
L["Channelling"] = "Canalizando"
L["Child units cannot be dragged, you will have to reposition them through /shadowuf."] = "Unidades hijas no se pueden arrastrar. Tendrás que posicionar los de nuevo a través de '/shadowuf'." -- Needs review
L["Class"] = "Clase"
L["Class color tag"] = "Etiqueta del color de la clase"
L["Classes"] = "Clases"
L["Class icon"] = "Icono de clase"
L["Classifications"] = "Clasificación "
L["Class/misc bars"] = "Barras de clase/miscelaneas" -- Needs review
L["Class name without coloring, use [classcolor][class][close] if you want the class name to be colored by class."] = "El nombre de la clase sin color, usa [classcolor][class][close] si quieres que el nombre de la clase tenga el color de la clase."
L["Class (Smart)"] = "Clase (Lista)"
L["Clip"] = "Presilla" -- Needs review
L["Close color"] = "Cerrar el color"
L["Closes a color code, prevents colors from showing up on text that you do not want it to."] = "Cierra un código de color para prohibir que se aparezca en texto en que no quiero verlo."
L["Code"] = "Código"
L["Color by class"] = "Pintar para representar la clase"
L["Color by reaction on"] = "Pintar para representar la disposición de la unidad"
L["Color code based on percentage of HP left on the unit, this works the same way as the color by health option. But for text instead of the entire bar."] = "Pintar el código para representar porcentaje de salud restante de la unidad.  Funciona en la misma manera como la opción de pintar para representar salud, pero se pinta el texto en lugar de la barra completa."
L["Color code for general situation"] = "Pintar el código para la situación general"
L["Color code for situation"] = "Pintar el código para la situación."
L["Color code for the class, use [classcolor][class][close] if you want the class text to be colored by class"] = "Pintar el código para la clase, usa [classcolor][class][close] si quieres que el texto de la clase sea colorado para representar la clase."
L["Color code on aggro"] = "Pintar el código cuando la unidad recibe aggro."
L["Color health by"] = "Pintar el salud para representar"
L["Color on aggro"] = "Pintar cuando se recibe aggro"
L["Colors"] = "Colores"
L["Color to use for health bars that are set to be colored by a static color."] = "El color que se usará para las barras de salud que están configuradas para ser colorado por un color inactivo."
L["Color to use to show how much damage will be absorbed."] = "Color que se utilizará para mostrar cuánto daño será absorbido." -- Needs review
L["Color used when a cast cannot be interrupted, this is only used for PvE mobs."] = "Color usado cuando un lanzamiento no puede ser interrumpido (Este color solo se usa para los enemigos de JcE)."
L["Color used when a cast is a channel."] = "Color usado cuando un lanzamiento es canalizado."
L["Color used when a cast is interrupted either by the caster themselves or by another unit."] = "Color usado cuando un lanzamiento se interrumpe por los propios hechiceros o por otra unidad."
L["Color used when a cast is successfully finished."] = "Color usado cuando un lanzamiento se completa con éxito. "
L["Color used when an unit is casting a spell."] = "Color usado cuando una unidad está lanzando un hechizo."
L["Column growth"] = "Expansión de la columna"
L["Column spacing"] = "Espacio entre columnas" -- Needs review
L["Combat alpha"] = "Opacidad en combate" -- Needs review
L["Combat fader"] = "Desvanecedor para el combate" -- Needs review
L["Combat fader will fade out all your frames while they are inactive and fade them back in once you are in combat or active."] = "Desvanecedor para el combate desvanecerá todos sus marcos mientras se encuentren inactivos y aparecerán de vuelta una vez que el combate inicie o se activen." -- Needs review
L["Combat/resting status"] = "Estado de combate y reposo"
L["Combat text"] = "Texto de combate"
L["Combo points"] = "Puntos de combinación "
L["Configuration to specific unit frames."] = "Configuración para los retratos específicos de las unidades."
L["Create"] = "Crear" -- Needs review
L["Creature type"] = "Tipo de Criatura" -- Needs review
L["Creature type, returns Felguard if the unit is a Felguard, Wolf if it's a Wolf and so on."] = "Tipo de criatura, regresa Guardia vil si la unidad es un Guardia vil, Lobo si es un Lobo y así sucesivamente." -- Needs review
L["Cur/Max HP (Absolute)"] = "Actual/Máxima PS (Absoluta)" -- Needs review
L["Cur/Max HP (Short)"] = "Actual/Máxima PS (Corto)" -- Needs review
L["Cur/Max HP (Smart)"] = "Actual/Máxima PS (Inteligente)" -- Needs review
L["Cur/Max power (Absolute)"] = "Actual/Máximo Poder (Absoluto)" -- Needs review
L["Cur/Max power (Druid)"] = "Actual/Máximo Poder (Druida)" -- Needs review
L["Cur/Max Power (Short)"] = "Actual/Máxima PP (Corto)" -- Needs review
L["Cur/Max PP (Smart)"] = "Actual/Máxima PP (Inteligente)" -- Needs review
L["Current and maximum health, formatted as [curhp]/[maxhp], if the unit is dead or offline then that is shown instead."] = "Salud actual y máxima, con el formato: [psact]/[psmax], si la unidad está muerta o desconectada se mostrará eso en su lugar." -- Needs review
L["Current and maximum power, formatted as [curpp]/[maxpp]."] = "Poder actual y máximo, con el formato: [ppact]/[ppmax]." -- Needs review
L["Current health (Druid/Absolute)"] = "Salud actual (Druida/Absoluta)" -- Needs review
L["Current health, uses a short format, 11500 is formatted as 11.5k, values below 10000 are formatted as is."] = "Salud actual, usa el formato corto, 11 500 es escrito como 11.5k, valores por debajo de 10 000 son escritos como son." -- Needs review
L["Current HP (Absolute)"] = "PS Actual (Absoluto)" -- Needs review
L["Current HP (Short)"] = "PS Actual (Corto)" -- Needs review
L["Currently modifying"] = "Actualmente modificando" -- Needs review
L["Current power (Absolute)"] = "Poder actual (Absoluto)" -- Needs review
L["Current power (Druid)"] = "Poder actual (Druida)" -- Needs review
L["Current power (Druid/Absolute)"] = "Poder actual (Druida/Absoluto)" -- Needs review
L["Current Power (Short)"] = "Poder Actual (Corto)" -- Needs review
L["Current power, uses a short format, 12750 is formatted as 12.7k, values below 10000 are formatted as is."] = "Poder Actual, usa el formato corto: 12 750 es escrito como 12.7k, valores por debajo de 10 000 se dejan como están." -- Needs review
L["Dark"] = "Oscuro" -- Needs review
L["Dead"] = "Cadaver" -- Needs review
L["Debuffs"] = "Perjuicios" -- Needs review
L["Decimal percent HP"] = "PS en porcentaje decimal" -- Needs review
L["Deficit/Unit Name"] = "Déficit/Nombre de unidad" -- Needs review
L["Delete"] = "Suprimir" -- Needs review
L["Delete filter"] = "Eliminar filtro" -- Needs review
L["Descending"] = "Descendiente" -- Needs review
L["Disabled"] = "Deshabiliitado" -- Needs review
L["Disabled in %s"] = "Deshabiliitado en %s" -- Needs review
L["Disable event discovery"] = "Deshabilitar descubrimiento de eventos" -- Needs review
L["Disables the unit frame from turning into a vehicle when the player enters one."] = "Deshabilita que el marco de unidad se convierta en vehículo cuando el jugador entra en uno." -- Needs review
L["Disable vehicle swap"] = "Deshabilitar intercambio de vehículo" -- Needs review
L["Disabling a module on this page disables it while inside %s. Do not disable a module here if you do not want this to happen!."] = "Deshabilitar un módulo en esta página lo deshabilita mientras esté dentro de %s. ¡No deshabilite un módulo aquí si no quiere que esto pase!." -- Needs review
L["Disabling unit modules in various instances."] = "Deshabilitando módulos de unidad en varias instancias." -- Needs review
L["DND"] = "No Molestar" -- Needs review
L["DND:%s"] = "NM: %s" -- Needs review
L["Documentation"] = "Documentación" -- Needs review
L["Don't hide when empty"] = "No ocultar cuando esté vacío" -- Needs review
L["Don't use a filter"] = "No usar filtro" -- Needs review
L["Down"] = "Abajo" -- Needs review
L["Druid form"] = "Forma de druida" -- Needs review
L["Druid form (Short)"] = "Forma de druida (Corto)" -- Needs review
L["Druid mana bar"] = "Barra de maná de druida" -- Needs review
L["Due to the nature of fake units, cast bars for %s are not super efficient and can take at most 0.10 seconds to notice a change in cast."] = "Debido a la naturaleza de las unidades falsas, las barras de lanzamiento para %s no son súper eficientes y pueden tardar hasta 0.1 segundos para tomar en cuenta cambios en el lanzamiento." -- Needs review
L["Eclipse bar"] = "Barra de eclipse" -- Needs review
L["Eclipse (Sun)"] = "Eclipse (Sol)" -- Needs review
L["Edge size"] = "Tamaño del borde" -- Needs review
L["Editing %s"] = "Editando %s" -- Needs review
L["Edit tag"] = "Editar etiqueta" -- Needs review
L["Elite"] = "Élite" -- Needs review
L["Empty bar"] = "Barra vacía" -- Needs review
L["Enable buffs"] = "Habilitar beneficios" -- Needs review
L["Enable debuffs"] = "Habilitar perjuicios" -- Needs review
L["Enabled in %s"] = "Habilitado en %s" -- Needs review
L["Enable frequent updates"] = "Habilitar actualizaciones frecuentes" -- Needs review
L["Enable indicator"] = "Habilitar indicador" -- Needs review
L["Enable %s"] = "Habilitar %s" -- Needs review
L["Enables configuration mode, letting you move and giving you example frames to setup."] = "Habilitar el modo de configuración, permitiéndote mover y dándote muestras de marcos a instalar." -- Needs review
L["Enable temporary enchants"] = "Habilitar encantamientos temporales" -- Needs review
L["Enable units"] = "Habilitar unidades" -- Needs review
L["Enabling advanced settings will give you access to more configuration options. This is meant for people who want to tweak every single thing, and should not be enabled by default as it increases the options."] = "Habilitar ajustes avanzados te dará acceso a más opciones de configuración. Esto está dirigido a personas que quieran modificar cada una de las configuraciones y no debería esta habilitado por defecto ya que incrementa las opciones." -- Needs review
L["Energy"] = "Energía" -- Needs review
L["Error"] = "Error" -- Needs review
L["Events"] = "Eventos" -- Needs review
L["Events that should be used to trigger an update of this tag. Separate each event with a single space."] = "Eventos que serán usados para disparar una actualización de esta etiqueta. Separa cada evento con un espacio indivual." -- Needs review
L["Everywhere else"] = "Cualquier otro lugar" -- Needs review
L["Export"] = "Exportar" -- Needs review
L["F"] = "F" -- Needs review
L["Fades out the unit frames of people who are not within range of you."] = "Desvanece los marcos de unidad de las personas que no están dentro de tu rango." -- Needs review
L["Failed to load ShadowedUF_Options, cannot open configuration. Error returned: %s"] = "Fallo al cargar 'ShadowedUF_Options', no se puede abrir la configuración, Error devuelto: %s" -- Needs review
L["Female"] = "Femenina" -- Needs review
L["Filtering both buffs and debuffs"] = "Filtrando tanto beneficios como perjuicios" -- Needs review
L["Filtering buffs only"] = "Filtrando solo beneficios" -- Needs review
L["Filtering debuffs only"] = "Filtrando solo perjuicios" -- Needs review
L["Filter type"] = "Tipo de filtro" -- Needs review
L["Finished cast"] = "Lanzamiento finalizado" -- Needs review
L["Flags the tag for frequent updating, it will update the tag on a timer regardless of any events firing."] = "Marca la etiqueta para actualización frecuente, actualizará la etiqueta basado en temporizador sin importar los eventos que sucedan." -- Needs review
L["Flight"] = "Vuelo" -- Needs review
L["Focus"] = "Foco" -- Needs review
L["Font"] = "Fuente" -- Needs review
L["Forces a static color to be used for the background of all bars"] = "Fuerza un color estático a ser usado como fondo en todas las barras" -- Needs review
L["For target/focus"] = "Para objetivo/foco" -- Needs review
L["Frame"] = "Marco" -- Needs review
L["Frame alpha when you are out of combat while having no target and 100% mana or energy."] = "Opacidad del marco cuando te encuentres fuera de combate mientras no haya objetivo y tengas 100% de maná o energía." -- Needs review
L["Frame alpha while this unit is in combat."] = "Opacidad del marco mientras esta unidad está en combate." -- Needs review
L["Frames"] = "Marcos" -- Needs review
L["Friendly"] = "Amistoso" -- Needs review
L["Fuel"] = "Combustible" -- Needs review
L["Full size after"] = "Tamaño completo después" -- Needs review
L["Full size before"] = "Tamaño completo antes" -- Needs review
L["General"] = "General" -- Needs review
L["General configuration to all enabled units."] = "Configuración general para todas las unidades habilitadas." -- Needs review
L["General threat situation"] = "Situación General de amenaza" -- Needs review
L["Ghost"] = "Fantasma" -- Needs review
L["Global"] = "Global" -- Needs review
L["Gold checkmark - Enabled in this zone / Grey checkmark - Disabled in this zone / No checkmark - Use the default unit settings"] = "Marca dorada - Habilitado en esta zona / Marca gris - Deshabilitado en esta zona / Sin marca - Usa los ajustes de unidad por defecto" -- Needs review
L["Group by"] = "Agrupar por" -- Needs review
L["Group %d"] = "Grupo %d" -- Needs review
L["Group number"] = "Número de Grupo" -- Needs review
L["Groups"] = "Grupos" -- Needs review
L["Groups to show"] = "Grupos a mostrar" -- Needs review
L["Growth"] = "Crecimiento" -- Needs review
L["Guild name"] = "Nombre de hermandad" -- Needs review
L["Half health"] = "Media Vida" -- Needs review
L["Health"] = "Vida" -- Needs review
L["Health bar"] = "Barra de vida" -- Needs review
L["Health bar color for friendly units."] = "Color de la barra de vida para unidades amistosas." -- Needs review
L["Health bar color for hostile units."] = "Color de la barra de vida para unidades hostiles." -- Needs review
L["Health bar color for neutral units."] = "Color de la barra de vida para unidades neutrales." -- Needs review
L["Health bar color to use for hostile units who you cannot attack, used for reaction coloring."] = "Color de la barra de vida a usar en unidades hostiles a las cuales no puedes atacar, utilizado para la coloración de reacción." -- Needs review
L["Health bar color used as the transitional color for 100% -> 0% on players, as well as when your pet is mildly unhappy."] = "Color de la barra de vida usado como el color de transición de 100% a 0% en jugadores, así también cuando tu mascota está ligeramente infeliz." -- Needs review
L["Health bar color used as the transitional color for 100% -> 50% on players, as well as when your pet is happy."] = "Color de la barra de vida usado como el color de transición de 100% a 50% en jugadores, así también cuando tu mascota está feliz." -- Needs review
L["Health bar color used as the transitional color for 50% -> 0% on players, as well as when your pet is very unhappy."] = "Color de la barra de vida usado como el color de transición de 50% a 0% en jugadores, así también cuando tu mascota está infeliz." -- Needs review
L["Health color"] = "Color de vida" -- Needs review
L["Health percent"] = "Porcentaje de vida" -- Needs review
L["Height"] = "Altura" -- Needs review
L["Help"] = "Ayuda" -- Needs review
L["Hide bar when empty"] = "Ocultar barra cuando esté vacía" -- Needs review
L["Hide Blizzard"] = "Ocultar 'Blizzard'" -- Needs review
L["Hide in any raid"] = "Ocultar en cualquier banda" -- Needs review
L["Hide %s"] = "Ocultar %s" -- Needs review
L["Hide %s frames"] = "Ocultar marcos %s" -- Needs review
L["Hides the cast bar if there is no cast active."] = "Oculta la barra de lanzamiento si no hay lanzamiento activo." -- Needs review
L["Hide tooltips in combat"] = "Ocultar descripciones en combate" -- Needs review
L["Hiding and showing various aspects of the default UI such as the player buff frames."] = "Ocultando y mostrando varios aspectos de la IU por defecto como los marcos de beneficios del jugador." -- Needs review
L["High"] = "Alto" -- Needs review
L["High health"] = "Vida alta" -- Needs review
L["Highlight"] = "Destacar" -- Needs review
L["Highlight units that are debuffed with something you can cure."] = "Señalar unidades que tienen perjuicios que puedes remover." -- Needs review
L["Highlight units that have aggro on any mob."] = "Destacar unidades que tienen 'aggro' de cualquier 'mob'." -- Needs review
L["Highlight units that you are targeting or have focused."] = "Destacar unidades que tienes como objetivo o foco." -- Needs review
L["Highlight units when you mouse over them."] = "Destacar unidades cuando posicione el ratón sobre ellos." -- Needs review
L["Holy Power"] = "Poder Sagrado" -- Needs review
L["Hostile"] = "Hostil" -- Needs review
L["How close the frame should clip with the border."] = "Que tan cerca el marco debe cortar el borde." -- Needs review
L["How far the background should be from the unit frame border."] = "Que tan lejos el fondo debe estar desde el borde del marco de la unidad." -- Needs review
L["How large the background should tile"] = "Que tanto debe cubrir el fondo." -- Needs review
L["How large the edges should be."] = "Que tan largos serán los bordes." -- Needs review
L["How many auras per a column for example, entering two her will create two rows that are filled up to whatever per row is set as."] = "Cuantas auras por columna, por ejemplo, ingresar dos creará dos filas que serán llenadas hasta el número configurado por fila." -- Needs review
L["How many auras to show in a single row."] = "Cuantas auras por fila se mostraran." -- Needs review
L["How many people are assisting the unit, for example if you put this on yourself it will show how many people are targeting your target. This includes you in the count!"] = "Cantidad de personas asistiendo a la unidad, por ejemplo si usted establece esto en usted mismo se mostrará cuantas personas tienen seleccionado a tu objetivo. Esto te incluye en el conteo." -- Needs review
L["How many people in your raid are targeting the unit, for example if you put this on yourself it will show how many people are targeting you. This includes you in the count!"] = "Cantidad de personas en la banda seleccionando la unidad, por ejemplo si usted establece esto en usted mismo se mostrará cuantas personas te tienen seleccionado. Esto te incluye en el conteo." -- Needs review
L["How many rows total should be used, rows will be however long the per row value is set at."] = "Cantidad total de filas a usarse, las filas serán tan largas como el valor por fila establecido." -- Needs review
L["Incoming absorb"] = "Absorción entrante" -- Needs review
L["Incoming absorbs"] = "Absorciones entrantes" -- Needs review
L["Incoming heal (Absolute)"] = "Sanación entrante (Absoluta)" -- Needs review
L["Incoming heal (Percent)"] = "Sanación entrante (Porcentaje)" -- Needs review
L["Invalid interval entered, must be a number."] = "Intervalo ingresado invalido, debe ser un número." -- Needs review
L["Left"] = "Izquierda" -- Needs review
L["Management"] = "Adminstración" -- Needs review
L["Percentage value of how far outside the unit frame the incoming absorb bar can go. 130% means it will go 30% outside the frame, 100% means it will not go outside."] = "Valor porcentual de hasta qué punto fuera del marco de la unidad la barra de absorción entrante puede llegar. 130% significa que va a ir el 30% fuera del marco, 100% significa que no salirse del marco." -- Needs review
L["player alt. power"] = "Poder alternativo de jugador" -- Needs review
L["Players will be colored by class."] = "Los jugadores serán coloreados por clase" -- Needs review
L["Programming in Lua"] = "Programación en LUA" -- Needs review
L["PvP Flag"] = "Emblema de JcJ" -- Needs review
L["Returns a scaled threat percent of your aggro on your current target, always 0 - 100%."] = "Regresa un porcentaje de amenaza escalado de su 'aggro' en su objetivo actual, siempre 0 - 100%." -- Needs review
L["Rune of Power"] = "Poder de runa" -- Needs review
L["Rune of Power bar"] = "Barra de Poder de runa" -- Needs review
L["%s frames"] = "%s retratos"
L["Show incoming absorbs"] = "Mostar absorciones entrantes" -- Needs review
L["Show incoming heals"] = "Mostrar sanaciones entrantes" -- Needs review
L["Shows a bar for alternate power info (used in some encounters)"] = "Muestra una barra para la información de poder alternativo (usada en algunos encuentros)" -- Needs review
L["Size"] = "Tamaño" -- Needs review
L["%s member"] = "%s miembro"
L["Soul shards"] = "Fragmentos de alma" -- Needs review
L["Soul Shards"] = "Fragmentos de alma" -- Needs review
L["%s (%s): %s/%s (%.2f%% done)"] = " %s (%s): %s/%s (%.2f%% hecho)"
L["Status"] = "Estado" -- Needs review
L["Top"] = "Arriba" -- Needs review
L["Total number of active holy power."] = "Número total de poder sagrado activo." -- Needs review
L["Total number of active soul shards."] = "Número total de fragmentos de almas activos." -- Needs review
L["Whitelist"] = "Lista blanca" -- Needs review
L["Zone configuration units"] = "Configuración de unidades por zona" -- Needs review

local ShadowUF = select(2, ...)
ShadowUF.L = setmetatable(L, {__index = ShadowUF.L})
