if( GetLocale() ~= "frFR" ) then return end
local L = {}
L["1 aura group disabled"] = "1 groupe d'auras désactivé" -- Needs review
L["2D"] = "2D"
L["3D"] = "3D"
L["A"] = "A"
L["Abbreviates unit names above 10 characters, \"Dark Rune Champion\" becomes \"D.R.Champion\" and \"Dark Rune Commoner\" becomes \"D.R.Commoner\"."] = "Raccourci les noms d'unité de plus de 10 caractères. Par exemple, \"Champion sombre-rune\" devient \"C. sombre-rune\" (les premiers mots sont raccourcis de la même façon qu'ils le sont en anglais)"
L["Absolute damage absorption value on the unit, if 10,000 damage will be absorbed, it will show 10,000."] = "Absorption de dégâts absolue sur l'unité. Si 10 000 dégâts vont être absorbés, 10 000 sera affiché." -- Needs review
L["Absolute heal absorb value, if 16,000 healing will be absorbed, it will show 16,000."] = "Valeur absolue de soins absorbés. Si 16 000 de soins seront absorbés, 16 000 sera affiché." -- Needs review
L["Absolute incoming heal value, if 10,000 healing is incoming it will show 10,000."] = "Valeur absolue des soins entrants. Si un soin à 10 000 arrive, 10 000 sera affiché."
L["Add"] = "Ajouter"
L["Add aura"] = "Ajouter aura" -- Needs review
L["Add Aura"] = "Ajouter aura" -- Needs review
L["Add Indicator"] = "Ajouter indicateur" -- Needs review
L["Add link"] = "Ajouter lien" -- Needs review
L["Add new indicator"] = "Ajouter nouvel indicateur" -- Needs review
L["Add new tag"] = "Ajout de nouveaux tags"
L["Add new text"] = "Ajout d'un nouveau texte"
L["Adds a bar indicating how much time is left on your ghoul timer, only used if you do not have a permanent ghoul."] = "Ajoute une barre indiquant combien de temps il reste à vivre à votre goules. Utilisée uniquement si votre goule n'est pas permanente."
L["Adds a bar indicating how much time is left on your mushrooms."] = "Ajoute une barre indiquant combien de temps il reste pour vos champignons." -- Needs review
L["Adds a bar indicating how much time is left on your Rune of Power."] = "Ajoute une barre indiquant le temps restant sur votre Rune de puissance." -- Needs review
L["Adds a bar inside the health bar indicating how much damage will be absorbed."] = "Ajoute une barre dans la barre de vie indiquant combien de dégâts seront absorbés." -- Needs review
L["Adds a bar inside the health bar indicating how much healing someone will receive."] = "Ajoute une barre à l'intérieur de la barre de vie indiquant combien de soins quelqu'un va recevoir." -- Needs review
L["Adds a bar inside the health bar indicating how much healing will be absorbed and not applied to the player."] = "Ajoute une barre dans la barre de vie indiquant combien de soins seront absorbés sans être appliqués au joueur." -- Needs review
L["Adds a Burning Embers bar for Destruction Warlocks."] = "Ajoute une barre des Braises enflammées pour les démonistes spécialisés en Destruction." -- Needs review
L["Adds a Demonic Fury bar for Demonology Warlocks."] = "Ajoute une barre de Fureur démoniaque pour les démonistes spécialisés en Démonologie." -- Needs review
L["Adds an empty bar that you can put text into as a way of uncluttering other bars."] = "Ajoute une barre vide dans laquelle vous pouvez placer du texte afin de soulager les autres barres."
L["Adds another mana bar to the player frame when you are in Bear or Cat form showing you how much mana you have."] = "Ajoute une autre barre de mana au cadre du joueur quand vous êtes en forme d'ours ou de félin."
L["Adds a Stagger bar for Brewmaster Monks."] = "Ajoute une barre de Report pour les Moines Maître brasseurs." -- Needs review
L["Adds eclipse bars and how far into sun or moon eclipse is."] = "Ajoute des barres d'éclipse et indique à quel point dans le soleil ou la lune éclipse se trouve." -- Needs review
L["Adds rune bars and timers before runes refresh to the player frame."] = "Ajoute une barre des runes avec les compteurs de recharge des runes au cadre du joueur."
L["Adds %s to the list of units to be modified when you change values in this tab."] = "Ajoute %s dans la liste des unités à modifier quand vous effectuez des changements dans cet onglet."
L["Adds temporary enchants to the buffs for the player."] = "Ajoute les enchantements temporaires aux buffs du joueur."
L["Adds totem bars with timers before they expire to the player frame."] = "Ajoute des barres de totem avec des compteurs d'expiration au cadre du joueur."
L["Add Tags"] = "Ajouter Tags" -- Needs review
L["Advanced"] = "Avancé"
L["Advanced tag management, allows you to add your own custom tags."] = "Gestion avancée des tags, permettant d'ajouter vos propres tags."
L["AFK"] = "ABS"
L["AFK:%s"] = "ABS:%s"
L["AFK status"] = "Statut ABS"
L["AFK timer"] = "Durée ABS"
L["After you hit export, you can give the below code to other Shadowed Unit Frames users and they will get your exact layout."] = "Une fois que vous avez appuyé sur Exporter, vous pouvez donner le code ci-dessous aux autres utilisateurs de Shadowed Unit Frames et ils obtiendront exactement votre disposition."
L["Aggro"] = "Aggro"
L["All aura groups enabled for unit."] = "Tous les groupes d'auras activés pour l'unité." -- Needs review
L["All Auras"] = "Toutes les auras" -- Needs review
L["Allows you to anchor the aura group to another, you can then choose where it will be anchored using the position.|n|nUse this if you want to duplicate the default ui style where buffs and debuffs are separate groups."] = "Vous permet d'ancrer le groupe d'auras sur un autre. Vous pouvez alors choisir où il sera ancré avec la position.|n|nUtilisez cela si vous voulez dupliquer le style d'UI par défaut où buffs et débuffs dont des groupes séparés." -- Needs review
L["Allows you to disable the totem by right clicking it.|n|nWarning: Inner bars for this unit will not resize in combat if you enable this."] = "Vous permet de désactiver le totem avec un clic-droit.|n|nAttention : les barres internes de cette unité ne se redimensionneront pas en combat si vous l'activez." -- Needs review
L["Allows you to enter a new aura group."] = "Permet d'entrer un nouveau groupe d'auras." -- Needs review
L["Alpha to use for bar."] = "La transparence à utiliser pour les barres."
L["Alpha to use for bar backgrounds."] = "Définit la transparence à utiliser pour les arrières-plan des barres."
L["Alternate power is used for things like quests and dungeons."] = "Puissance alternative utilisée par exemple dans les quêtes et donjons." -- Needs review
L["Alternate Spell Name"] = "Nom de sort alternatif" -- Needs review
L["Alternatively friendly spell to use to check range."] = "Sort amical alternativement à utiliser pour vérifier la portée." -- Needs review
L["Alt. Power"] = "Puissance alt." -- Needs review
L["Alt. Power bar"] = "Barre de puissance alt."
L["Ammo"] = "Munitions"
L["Amount of health missing, if none is missing nothing is shown. Uses a short format, -18500 is shown as -18.5k, values below 10000 are formatted as is."] = "Quantité de vie manquante. Si nul, rien n'est affiché. Utilise un format court : -18 500 est remplacé par -18.5k, et les valeurs inférieures à 10 000 sont affichées telles qu'elles."
L["Amount of power missing,  if none is missing nothing is shown. Uses a short format, -13850 is shown as 13.8k, values below 10000 are formatted as is."] = "Quantité de puissance manquante. Si nul, rien n'est affiché. Utilise un format court : -13 850 est remplacé par 13.8k, et les valeurs inférieures à 10 000 sont affichées telles qu'elles."
L["Anchor point"] = "Point d'ancrage"
L["Anchor to"] = "Ancrer à"
L["Anchor to another frame"] = "Ancrer à un autre cadre"
L["Anchor to buffs"] = "Ancrer aux buffs"
L["Anchor to debuffs"] = "Ancrer aux debuffs"
L["Ancient Kings bar"] = "Barre Anciens Rois" -- Needs review
L["Any auras shown in this indicator will have their total stack displayed."] = "Toute aura montrée dans cet indicateur affichera son stack total." -- Needs review
L["Aquatic"] = "Aquatique"
L["Arena"] = "Arène"
L["Arena Pet"] = "Fam. d'arène"
L["Arenas"] = "Arènes"
L["Arena Spec"] = "Spécialisation" -- Needs review
L["Arena Target"] = "Cibles d'arène"
L["Arena Target of Target"] = "Cible de la cible d'arène" -- Needs review
L["Arena ToT"] = "CdC Arène" -- Needs review
L["Are you sure you want to delete this aura?"] = "Êtes-vous sûr de vouloir supprimer cette aura ?" -- Needs review
L["Are you sure you want to delete this filter?"] = "Êtes-vous sûr de vouloir supprimer ce filtre ?"
L["Are you sure you want to delete this indicator?"] = "Êtes-vous sûr de vouloir supprimer cet indicateur  ?" -- Needs review
L["Are you sure you want to delete this tag?"] = "Êtes-vous sûr de vouloir supprimer ce tag ?"
L["Are you sure you want to delete this text? All settings for it will be deleted."] = "Êtes-vous sûr de vouloir supprimer ce texte ? Tous les paramètres seront supprimés."
L["Ascending"] = "Ascendant"
L["Assigned Role (DPS/Tank/etc)"] = "Rôle attribué (DPS/Tank/etc)" -- Needs review
L["Aura borders"] = "Bord des auras" -- Needs review
L["Aura border style"] = "Style de bordure des auras"
L["Aura Combo Points"] = "Points de combo Aura" -- Needs review
L["Aura filters"] = "Filtres d'auras"
L["Aura Filters"] = "Filtres d'aura" -- Needs review
L["Aura group"] = "Groupe d'aura" -- Needs review
L["Aura groups"] = "Groupes d'aura" -- Needs review
L["Aura Groups"] = "Groupes d'aura" -- Needs review
L["Aura indicators"] = "Indicateurs d'aura" -- Needs review
L["Aura Indicators"] = "Indicateurs d'aura" -- Needs review
L["Aura name"] = "Nom de l'aura"
L["Auras"] = "Auras"
L["Auras matching a criteria will automatically show up in the indicator when enabled."] = "Les auras correspondant à un critère apparaîtront automatiquement dans l'indicateur si activé." -- Needs review
L["Aura types to filter"] = "Types de filtre d'auras"
L["Automatic Auras"] = "Auras automatiques" -- Needs review
L["B"] = "B"
L["Background"] = "Arrière-plan"
L["Background alpha"] = "Transp. de l'arrière-plan"
L["Background/border"] = "Arrière-plan/bordure"
L["Background color"] = "Couleur d'arrière-plan"
L["Bag indicator for master looters."] = "Sac-indicateur des maîtres du butin."
L["Banked Holy Power"] = "Puissance sacrée emmagasinée" -- Needs review
L["Bar alpha"] = "Transparence des barres"
L["Bar coloring for the moon portion of the eclipse bar."] = "Coloration de barre pour la portion lune de la barre d'éclipse."
L["Bar color to use to show how much healing someone is about to receive."] = "Couleur de barre à utiliser pour montrer combien de soins quelqu'un va recevoir." -- Needs review
L["Bars"] = "Barres"
L["Bar spacing"] = "Espacement des barres"
L["Bars with an order higher or lower than the full size options will use the entire unit frame width.|n|nBar orders between those two numbers are shown next to the portrait."] = "Les barres avec un ordre plus ou moins élevé que les option \"Pleine taille\" utiliseront toute la largeur du cadre.|n|nLes barres entre ces deux nombres seront à côté du portrait." -- Needs review
L["Bar texture"] = "Texture des barres"
L["Battleground"] = "Champ de bataille" -- Needs review
L["Battleground Pet"] = "Familier du champ de bataille" -- Needs review
L["Battlegrounds"] = "Champs de bataille"
L["Battleground Target"] = "Cible du champ de bataille" -- Needs review
L["Battleground Target of Target"] = "Cible de la cible de champ de bataille" -- Needs review
L["Bear"] = "Ours"
L["BG"] = "CdB" -- Needs review
L["BG Pet"] = "Fam. CdB" -- Needs review
L["BG Target"] = "Cible CdB" -- Needs review
L["BG ToT"] = "CdC CdB" -- Needs review
L["Blacklist"] = "Liste noire"
L["Blacklist filters"] = "Filtres des listes noires"
L["Blacklists"] = "Listes noires"
L["Blizzard"] = "Blizzard"
L["Border"] = "Bordure"
L["Border alpha"] = "Transp. de la bordure"
L["Border color"] = "Couleur de la bordure"
L["Border coloring of stealable, curable and dispellable auras."] = "Couleur de bordure des auras volables, soignables, et dissipables." -- Needs review
L["Border highlighting"] = "Surbrillance de la bordure"
L["Border thickness"] = "Épaisseur de la bordure"
L["Boss"] = "Boss"
L["Boss Auras"] = "Auras de boss" -- Needs review
L["Boss Debuffs"] = "Débuffs de boss" -- Needs review
L["Boss Target"] = "Cible des boss"
L["Boss Target of Target"] = "Cible de la cible des boss" -- Needs review
L["Boss ToT"] = "CdC Boss" -- Needs review
L["Boss units are for only certain fights, such as Blood Princes or the Gunship battle, you will not see them for every boss fight."] = "Les unités boss ne sont utilisées que dans certains combats, tels que les princes de sang ou la bataille des canonnières. Vous ne les verrez pas à chaque rencontre de boss."
L["Both"] = "Les deux"
L["Bottom"] = "Bas"
L["Bottom Center"] = "Bas Centre"
L["Bottom Left"] = "Bas Gauche"
L["Bottom Right"] = "Bas Droite"
L["buff frames"] = "cadres des buffs"
L["Buffs"] = "Buffs"
L["Burning Embers"] = "Braises enflammées" -- Needs review
L["Burning Embers bar"] = "Barre Braises enflammées" -- Needs review
L["C"] = "C"
L["Cannot find any profiles named \"%s\"."] = "Impossible de trouver un profil nommé \"%s\"."
L["Cast"] = "Incantation"
L["Cast bar"] = "Barre d'incantation"
L["Cast icon"] = "Icône d'incantation"
L["Casting"] = "Incantation"
L["Cast interrupted"] = "Incantation interrompue"
L["Cast name"] = "Nom d'incantation"
L["Cast time"] = "Durée d'incantation"
L["Cast uninterruptible"] = "Incantation non-interruptible"
L["Cat"] = "Félin"
L["Category"] = "Catégorie"
L["Center"] = "Centre"
L["|cff20ff20%s|r units enabled"] = "|cff20ff20%s|r unités activées" -- Needs review
L["|cffff2020%s|r units disabled"] = "|cffff2020%s|r unités désactivées" -- Needs review
L["|cffff2020Warning!|r Some units have overrides set in zone configuration, and may show (or not show up) in certain zone. Regardless of the settings below."] = "|cffff2020Attention !|r Certaines unités ont des spécificités définies dans la config de zone, et peuvent apparaître (ou ne pas apparaître) dans certaines zones. Quel que soit le réglage ci-dessous." -- Needs review
L["Changed profile to %s."] = "Profil changé vers %s."
L["Changes the health bar to the set hostile color (Red by default) when the unit takes aggro."] = "Change la couleur de la barre de vie vers la couleur d'hostilité définie (rouge par défaut) quand l'unité prend l'aggro."
L["Changes this widget into a bar, you will be able to change the height and ordering like you can change health and power bars."] = "Change ce widget en barre. Vous pourrez changer la hauteur et l'ordre de la même façon que pour les barres de vie et de puissance."
L["Channelling"] = "Canalisation"
L["Checking this will show the indciator on hostile units."] = "Cocher pour afficher l'indicateur sur les unités hostiles." -- Needs review
L["Checking this will show the indicator on friendly units."] = "Cocher pour afficher l'indicateur sur les unités amicales." -- Needs review
L["Chi"] = "Chi" -- Needs review
L["Child units cannot be dragged, you will have to reposition them through /shadowuf."] = "Child units cannot be dragged, you will have to reposition them through /shadowuf."
L["Chi Points"] = "Points de chi" -- Needs review
L["Class"] = "Classe"
L["Class color tag"] = "Tag de couleur de classe"
L["Classes"] = "Classes"
L["Class icon"] = "Icône de classe"
L["Class Icon"] = "Icône de classe" -- Needs review
L["Class icon for players."] = "Icône de classe pour les joueurs." -- Needs review
L["Classification"] = "Classification" -- Needs review
L["Classifications"] = "Classifications"
L["Class/misc bars"] = "Barres de classe/diverses" -- Needs review
L["Class name without coloring, use [classcolor][class][close] if you want the class name to be colored by class."] = "Nom de la classe sans coloration. Utilisez [classcolor][class][close] si vous souhaitez que le nom de la classe soit coloré selon la classe."
L["Class Role"] = "Rôle de classe" -- Needs review
L["Class (Smart)"] = "Classe (intelligent)"
L["Class Specific"] = "Spécifique aux classes" -- Needs review
L["Class Timer"] = "Compteur de classe" -- Needs review
L["Clip"] = "Marge" -- Needs review
L["Close color"] = "Fin de couleur"
L["Closes a color code, prevents colors from showing up on text that you do not want it to."] = "Ferme un code couleur, empêche les couleurs de s'afficher jusqu'à une partie du texte alors que vous ne le souhaitez pas."
L["Code"] = "Code"
L["Color by class"] = "Colorer selon la classe"
L["Color by reaction on"] = "Colorer selon la réaction pour"
L["Color code based on percentage of HP left on the unit, this works the same way as the color by health option. But for text instead of the entire bar."] = "Code de couleur basé sur le pourcentage de vie restant de l'unité. Ceci fonctionne de la même manière que l'option de coloration selon la vie, mais pour le texte au lieu de toute la barre."
L["Color code for general situation"] = "Code couleur de situation générale"
L["Color code for situation"] = "Code couleur de situation"
L["Color code for the class, use [classcolor][class][close] if you want the class text to be colored by class"] = "Code couleur pour la classe, utilisez [classcolor][class][close] si vous souhaitez que le texte de classe soit coloré selon la classe."
L["Color code on aggro"] = "Code couleur à l'aggro"
L["Color health by"] = "Colorer la vie par"
L["Color on aggro"] = "Colorer à l'aggro"
L["Color power by"] = "Colorer puissance par" -- Needs review
L["Colors"] = "Couleurs"
L["Color to use for health bars that are set to be colored by a static color."] = "Couleur à utiliser pour les barres de vie définies pour être colorées par une couleur statique."
L["Color to use to show how much damage will be absorbed."] = "Couleur à utiliser pour montrer combien de dégâts seront absorbés." -- Needs review
L["Color to use to show how much healing will e absorbed."] = "Couleur à utiliser pour montrer combien de soins seront absorbés." -- Needs review
L["Color used when a cast cannot be interrupted, this is only used for PvE mobs."] = "Couleur utilisée quand une incantation ne peut être interrompue. Utilisé uniquement pour les monstres."
L["Color used when a cast is a channel."] = "Couleur utilisée quand une incantation est canalisée."
L["Color used when a cast is interrupted either by the caster themselves or by another unit."] = "Couleur utilisée quand une incantation est interrompue soit par l'incantateur lui-même, soit par une autre unité."
L["Color used when a cast is successfully finished."] = "Couleur utilisée quand une incantation s'est terminée avec succès."
L["Color used when an unit is casting a spell."] = "Couleur utilisée quand une unité est en train d'incanter un sort."
L["Column growth"] = "Sens d'ajout des colonnes"
L["Column spacing"] = "Espacement des colonnes"
L["Combat alpha"] = "Transp. en combat"
L["Combat fader"] = "Fondu de combat"
L["Combat fader will fade out all your frames while they are inactive and fade them back in once you are in combat or active."] = "Le fondu de combat estompera tous vos cadres quand ces dernières sont inactives et les remet au premier plan une fois que vous êtes en combat ou qu'elles sont actives."
L["Combat/resting status"] = "Statut combat/repos"
L["Combat Status"] = "Statut du combat" -- Needs review
L["Combat text"] = "Texte de combat"
L["Combo points"] = "Points de combo"
L["Combo Points"] = "Points de combo" -- Needs review
L["Configuration to specific unit frames."] = "Configuration de cadres d'unité spécifiques."
L["Cooldown rings for"] = "Spirale de recharge pour" -- Needs review
L["Create"] = "Créer"
L["Creature type"] = "Type de créature"
L["Creature type, returns Felguard if the unit is a Felguard, Wolf if it's a Wolf and so on."] = "Type de la créature. Renvoie Gangregarde si l'unité est un gangregarde, Loup si c'est un loup, etc."
L["Crown indicator for group leader or assistants."] = "Couronne - indicateur de chef de groupe et assistants." -- Needs review
L["Curable"] = "Soignable" -- Needs review
L["Curable Auras"] = "Auras dissipables" -- Needs review
L["Cur/Max HP (Absolute)"] = "Vie actu./max. (absolue)"
L["Cur/Max HP (Short)"] = "Vie actu./max. (courte)"
L["Cur/Max HP (Smart)"] = "Vie actu./max. (intelligent)"
L["Cur/Max power (Absolute)"] = "Puissance actu./max. (absolue)"
L["Cur/Max power (Druid)"] = "Puissance actu./max. (druide)"
L["Cur/Max power (Monk)"] = "Puissance act./max (moine)" -- Needs review
L["Cur/Max Power (Short)"] = "Puissance actu./max. (courte)"
L["Cur/Max PP (Smart)"] = "Puissance actu./max. (intelligent)"
L["Current and maximum health, formatted as [curhp]/[maxhp], if the unit is dead or offline then that is shown instead."] = "Vie actuelle et maximale, sous la forme [curhp]/[maxhp]. Si l'unité est morte ou hors ligne, ces derniers sont affichés à la place."
L["Current and maximum power, formatted as [curpp]/[maxpp]."] = "Puissance actuelle et maximale, sous la forme [curpp]/[maxpp]."
L["Current Demonic Fury (Short)"] = "Fureur démoniaque actuelle (court)" -- Needs review
L["Current Eclipse, <0 is Lunar Energy and >0 is Solar Energy."] = "Éclipse actuelle, <0 est l'Énergie Lunaire, >0 est l'Énergie Solaire." -- Needs review
L["Current health (Druid/Absolute)"] = "Vie actuelle (druide/absolue)"
L["Current health (Monk/Absolute)"] = "Vie actuelle (moine/absolu)" -- Needs review
L["Current health, uses a short format, 11500 is formatted as 11.5k, values below 10000 are formatted as is."] = "Vie actuelle dans un format court : 11 500 est remplacé par 11.5k, et les valeurs inférieures à 10 000 sont affichées telles qu'elles."
L["Current HP (Absolute)"] = "Vie actuelle (absolue)"
L["Current HP (Short)"] = "Vie actuelle (court)"
L["Currently modifying"] = "Modifie actuellement" -- Needs review
L["Currently used in battlegrounds for showing flag carriers."] = "Utilisé en champ de bataille pour montrer les porteurs de drapeaux." -- Needs review
L["Current pet used by a battleground unit."] = "Familier actuel d'une unité de champ-de-bataille." -- Needs review
L["Current power (Absolute)"] = "Puissance actuelle (absolue)"
L["Current power (Druid)"] = "Puissance actuelle (druide)"
L["Current power (Druid/Absolute)"] = "Puissance actuelle (druide/absolue)"
L["Current power (Monk)"] = "Puissance actuelle (moine)" -- Needs review
L["Current power (Monk/Absolute)"] = "Puissance actuelle (moine/absolu)" -- Needs review
L["Current Power (Short)"] = "Puissance actuelle (court)"
L["Current power, uses a short format, 12750 is formatted as 12.7k, values below 10000 are formatted as is."] = "Puissance actuelle dans un format court : 12 750 est remplacé par 12.7k, et les valeurs inférieures à 10 000 sont affichées telles qu'elles."
L["Current target of a battleground unit."] = "Cible actuelle d'une unité de champ-de-bataille." -- Needs review
L["Current target of target of a battleground unit."] = "Cible de la cible d'une unité de champ-de-bataille." -- Needs review
L["Damage absorption (Absolute)"] = "Absorption (absolue)" -- Needs review
L["Damage absorption/Name"] = "Absorption/Nom" -- Needs review
L["Damage absorption (Short)"] = "Absorption (court)" -- Needs review
L["Dark"] = "Sombre"
L["%d auras in group"] = "%d auras dans le groupe" -- Needs review
L["Dead"] = "Mort"
L["Debuffs"] = "Debuffs"
L["Decimal percent HP"] = "PV en pourcent décimal"
L["Default color"] = "Couleur par défaut"
L["Default font color, any color tags inside individual tag texts will override this."] = "Couleur de police par défaut. Les tags de couleurs dans les tag de texte individuels outrepasseront cela." -- Needs review
L["Deficit/Unit Name"] = "Déficit/Nom de l'unité"
L["Delete"] = "Supprimer"
L["Delete filter"] = "Supprimer le filtre"
L["Delete link"] = "Supprimer lien" -- Needs review
L["Demonic Fury"] = "Fureur démoniaque" -- Needs review
L["Demonic Fury bar"] = "Barre de Fureur démoniaque" -- Needs review
L["Descending"] = "Descendant"
L["Disable Auras by Class"] = "Désactiver les auras par classe." -- Needs review
L["Disabled"] = "Désactivé"
L["Disabled for %s."] = "Désactivé pour %s." -- Needs review
L["Disabled in %s"] = "Désactivé en %s"
L["Disable event discovery"] = "Désactiver la découverte d'évènement"
L["Disable OmniCC"] = "Désactiver OmniCC"
L["Disables showing OmniCC timers in all Shadowed Unit Frame auras."] = "Désactive l'affichage des compteurs OmniCC de toutes les auras de Shadowed Unit Frames." -- Needs review
L["Disables the unit frame from turning into a vehicle when the player enters one."] = "Empêche le cadre d'unité de se transformer en véhicule quand le joueur entre dans l'un d'eux."
L["Disable vehicle swap"] = "Désactiver l'échange avec le véhicule"
L["Disabling a module on this page disables it while inside %s. Do not disable a module here if you do not want this to happen!."] = "La désactivation d'un module sur cette page désactive ce dernier quand vous êtes en %s. Ne désactivez pas un module ici si vous ne voulez pas que cela arrive !"
L["Disabling unit modules in various instances."] = "Désactivation des modules d'unité dans diverses instances."
L["Dismissable Totem bars"] = "Totems renvoyables" -- Needs review
L["Dispellable/Stealable"] = "Dissipable/Volable" -- Needs review
L["Display"] = "Afficher" -- Needs review
L["DND"] = "NPD"
L["DND:%s"] = "NPD:%s"
L["Documentation"] = "Documentation"
L["Don't hide when empty"] = "Ne pas cacher si vide"
L["Don't use a filter"] = "Ne pas utiliser de filtre"
L["Down"] = "Bas"
L["Druid form"] = "Forme druidique"
L["Druid form (Short)"] = "Forme druidique (court)"
L["Druid mana bar"] = "Barre de mana druidique"
L["Due to the nature of fake units, cast bars for %s are not super efficient and can take at most 0.10 seconds to notice a change in cast."] = "Étant donnée la nature des fausses unités, les barres d'incantation |2 %s ne sont pas très efficaces et un délai d'au plus 0,10 seconde est nécessaire pour repérer un changement dans l'incantation."
L["Eclipse bar"] = "Barre d'éclipse"
L["Eclipse (Druid)"] = "Éclipse (Druide)" -- Needs review
L["Eclipse (Moon)"] = "Eclipse (lune)"
L["Eclipse (Sun)"] = "Eclipse (soleil)"
L["Edge size"] = "Taille de bord"
L["Editing %s"] = "Edition |2 %s"
L["Edit tag"] = "Édition de tag"
L["Elite"] = "Élite"
L["Empty bar"] = "Barre vide"
L["Enable buffs"] = "Activer les buffs"
L["Enable debuffs"] = "Activer les debuffs"
L["Enabled for %s."] = "Activé pour %s." -- Needs review
L["Enabled in %s"] = "Activé en %s"
L["Enabled Units"] = "Unités activées" -- Needs review
L["Enable for friendlies"] = "Activer pour les amis" -- Needs review
L["Enable for hostiles"] = "Activer pour les ennemis" -- Needs review
L["Enable frequent updates"] = "Activer les m. à j. fréquentes"
L["Enable indicator"] = "Activer l'indicateur"
L["Enable Indicators"] = "Activer indicateurs" -- Needs review
L["Enable %s"] = "Activer %s"
L["Enables configuration mode, letting you move and giving you example frames to setup."] = "Active le mode de configuration, vous permettant de déplacer les cadres et donnant également des cadres d'exemple à paramétrer."
L["Enable temporary enchants"] = "Activer les enchant. temporaires"
L["Enable units"] = "Activation d'unités"
L["Enabling advanced settings will give you access to more configuration options. This is meant for people who want to tweak every single thing, and should not be enabled by default as it increases the options."] = "L'activation des paramètres avancés vous donnera accès à plus d'options de configuration.  Conseillé pour les gens qui souhaitent peaufiner la moindre petite chose."
L["Energy"] = "Énergie"
L["Enlarge auras for"] = "Agrandir auras pour" -- Needs review
L["Error"] = "Erreur"
L["Events"] = "Événements"
L["Events that should be used to trigger an update of this tag. Separate each event with a single space."] = "Les événements qui doivent être utilisées pour déclencher une mise à jour de ce tag. Séparez chaque événement par une espace."
L["Everywhere else"] = "Partout ailleurs"
L["Export"] = "Exporter"
L["F"] = "F"
L["Fades out the unit frames of people who are not within range of you."] = "Estompe les cadres d'unité des gens qui ne sont pas à votre portée."
L["Failed to import layout, error:|n|n%s"] = "Échec de l'importation de la disposition, erreur : |n|n%s"
L["Failed to load ShadowedUF_Options, cannot open configuration. Error returned: %s"] = "Échec du chargement de ShadowedUF_Options car impossible de charger la configuration. Erreur renvoyée : %s"
L["Failed to save tag, error:|n %s"] = "Échec de la sauvegarde du tag, erreur : |n %s"
L["Fel Energy"] = "Energie gangrenée" -- Needs review
L["Female"] = "Femme"
L["Filtering both buffs and debuffs"] = "Filtrage des buffs et des debuffs"
L["Filtering buffs only"] = "Filtrage des buffs uniquement"
L["Filtering debuffs only"] = "Filtrage des debuffs uniquement"
L["Filters"] = "Filtres" -- Needs review
L["Filter type"] = "Type de filtre"
L["Finished cast"] = "Incantation terminée"
L["Flags the tag for frequent updating, it will update the tag on a timer regardless of any events firing."] = "Marque le tag pour mise à jour fréquente, cela mettra à jour le tag sur un timer, indépendamment des déclenchements d'événements."
L["Flight"] = "Vol"
L["Flips coloring so the bar color is shown as the background color and the background as the bar"] = "Inverse les couleurs. La barre prend l'aspect du fond, et le fond celui de la barre." -- Needs review
L["Focus"] = "Focalisation"
L["Focus Target"] = "Cible de la focalisation"
L["Font"] = "Police d'écriture"
L["Food"] = "Nourriture" -- Needs review
L["Forces a static color to be used for the background of all bars"] = "Force l'utilisation d'une couleur statique pour l'arrière-plan de toutes les barres."
L["For configuring aura indicators on unit frames."] = "Pour configurer les indicateurs d'auras sur les cadres d'unité." -- Needs review
L["For target/focus"] = "Pour cible/focal."
L["Frame"] = "Cadre"
L["Frame alpha when you are out of combat while having no target and 100% mana or energy."] = "Définit la transparence du cadre quand vous êtes hors combat, tout en ayant aucune cible et 100% de mana ou d'énergie."
L["Frame alpha while this unit is in combat."] = "Définit la transparence du cadre quand cette unité est en combat."
L["Frames"] = "Cadres"
L["Friendly"] = "Amical"
L["Fuel"] = "Carburant"
L["Full Burning Ember"] = "Braises ardentes pleines" -- Needs review
L["Full size after"] = "Pleine taille après" -- Needs review
L["Full size before"] = "Pleine taille avant" -- Needs review
L["General"] = "Général"
L["General configuration to all enabled units."] = "Configuration générale de toutes les unités activées."
L["General threat situation"] = "Situation générale de la menace"
L["Ghost"] = "Fantôme"
L["Global"] = "Global"
L["Global configurating will let you mass enable or disable aura groups for multiple units at once."] = "La configuration globale permet d'activer ou désactiver en masse des groupes d'auras pour plusieurs unités à la fois." -- Needs review
L["Gold checkmark - Enabled in this zone / Grey checkmark - Disabled in this zone / No checkmark - Use the default unit settings"] = "Coche dorée - activé dans cette zone / Coche grisée - Désactivée dans cette zone / Pas de coche - Utilise les paramètres par défaut de l'unité"
L["Green (<30% HP)"] = "Vert (<30% PV)" -- Needs review
L["Group by"] = "Grouper par"
L["Group %d"] = "Groupe %d"
L["Group number"] = "Numéro de groupe"
L["Group row spacing"] = "Ecart rangées de groupe" -- Needs review
L["Groups"] = "Groupes"
L["Groups per row"] = "Groupes par rangée"
L["Groups to show"] = "Groupes à afficher"
L["Growth"] = "Sens d'ajout"
L["Guild name"] = "Nom de guilde"
L["Half health"] = "Mi-vie"
L["Has Aggro"] = "A l'aggro" -- Needs review
L["Heal absorb"] = "Soins absorbés" -- Needs review
L["Heal Absorb (Absolute)"] = "Soins absorbés (absolu)" -- Needs review
L["Heal absorbs"] = "Soins absorbés" -- Needs review
L["Heal Absorb (Short)"] = "Soins absorbés (court)" -- Needs review
L["Healing absorb"] = "Soins absorbés" -- Needs review
L["Health"] = "Vie"
L["Health bar"] = "Barre de vie"
L["Health bar color for friendly units."] = "La couleur de la barre de vie pour les unités amicales."
L["Health bar color for hostile units."] = "La couleur de la barre de vie pour les unités hostiles."
L["Health bar color for neutral units."] = "La couleur de la barre de vie pour les unités neutres."
L["Health bar color for units with aggro."] = "Couleur de la barre de vie des unités ayant l'aggro." -- Needs review
L["Health bar color to use for hostile units who you cannot attack, used for reaction coloring."] = "La couleur de barre de vie à utiliser pour les unités hostiles que vous ne pouvez pas attaquer. Utilisée pour la coloration selon la réaction."
L["Health bar color used as the transitional color for 100% -> 0% on players, as well as when your pet is mildly unhappy."] = "La couleur de la barre de vie utilisée comme couleur de transition de 100% -> 0% sur les joueurs, ainsi que quand votre familier est un peu mécontent."
L["Health bar color used as the transitional color for 100% -> 50% on players, as well as when your pet is happy."] = "La couleur de la barre de vie utilisée comme couleur de transition de 100% -> 50% sur les joueurs, ainsi que quand votre familier est heureux."
L["Health bar color used as the transitional color for 50% -> 0% on players, as well as when your pet is very unhappy."] = "La couleur de la barre de vie utilisée comme couleur de transition de 50% -> 0% sur les joueurs, ainsi que quand votre familier est mécontent."
L["Health color"] = "Couleur de vie"
L["Health percent"] = "Pourcentage de vie"
L["Height"] = "Hauteur"
L["Help"] = "Aide"
L["Hide bar when empty"] = "Cacher barre si vide"
L["Hide Blizzard"] = "Cacher Blizzard"
L["Hide in <=5-man raids"] = "Masquer dans raids <= 5" -- Needs review
L["Hide in >5-man raids"] = "Masquer dans raids > 5" -- Needs review
L["Hide in any raid"] = "Cacher ds tous les raids"
L["Hide %s"] = "Cacher %s"
L["Hide %s frames"] = "Cacher cadres |2 %s"
L["Hides the cast bar if there is no cast active."] = "Cache la barre d'incantation si aucune incantation n'est en cours."
L["Hides the power bar unless the class has mana."] = "Cache la barre de puissance si la classe n'a pas de mana." -- Needs review
L["Hide tooltips in combat"] = "Cacher bulles en combat"
L["Hiding and showing various aspects of the default UI such as the player buff frames."] = "Masquage et affichage de divers aspects de l'IU par défaut tel que les cadres des buffs du joueur."
L["High"] = "Haut" -- Needs review
L["High health"] = "Vie élevée"
L["Highlight"] = "Surbrillance"
L["Highlight units that are "] = "Met en surbrillance les unités élites." -- Needs review
L["Highlight units that are debuffed with something you can cure."] = "Met en surbrillance les unités qui sont affectées par quelque chose que vous pouvez enlever."
L["Highlight units that are rare."] = "Met en surbrillance les unités rares." -- Needs review
L["Highlight units that have aggro on any mob."] = "Met en surbrillance les unités qui ont l'attention d'un monstre."
L["Highlight units that you are targeting or have focused."] = "Met en surbrillance les unités que vous avez en cible ou en focalisation."
L["Highlight units when you mouse over them."] = "Met en surbrillance les unités que vous survolez avec la souris."
L["Holy power"] = "Puissance sacrée" -- Needs review
L["Holy Power"] = "Puissance sacrée"
L["Hostile"] = "Hostile"
L["How close the frame should clip with the border."] = "Quelle marge laisser entre l'unité et le bord." -- Needs review
L["How far the background should be from the unit frame border."] = "La distance à laquelle l'arrière-plan  doit se trouver par rapport à la bordure du cadre d'unité."
L["How large the background should tile"] = "La largeur des carreaux d'arrière-plan." -- Needs review
L["How large the edges should be."] = "À quel point les bords doivent être."
L["How many auras per a column for example, entering two her will create two rows that are filled up to whatever per row is set as."] = "Le nombre d'auras par colonne. Par exemple, entrer 2 ici créera 2 rangées qui seront remplies indépendamment de la valeur par rangée."
L["How many auras to show in a single row."] = "Le nombre d'auras à afficher dans une seule rangée."
L["How many Chi points you currently have."] = "Combien de points de chi vous avez actuellement." -- Needs review
L["How many groups should be shown per row."] = "Définit le nombre de groupes à afficher par rangée."
L["How many people are assisting the unit, for example if you put this on yourself it will show how many people are targeting your target. This includes you in the count!"] = "Nombre de joueurs qui soutiennent l'unité. Par exemple, si vous placez ceci sur vous même, cela affichera le nombre de joueurs qui ciblent votre cible. Vous êtes inclus dans le compte !"
L["How many people in your raid are targeting the unit, for example if you put this on yourself it will show how many people are targeting you. This includes you in the count!"] = "Nombre de joueurs dans votre raid qui ciblent l'unité. Par exemple, si vous placez ceci sur vous même, cela affichera le nombre de joueurs qui vous ciblent. Vous êtes inclus dans le compte !"
L["How many rows total should be used, rows will be however long the per row value is set at."] = "Nombre total de rangées. Les rangées auront la longueur définie avec la valeur par rangée." -- Needs review
L["How many seconds a totem has left before disappearing."] = "Combien de secondes avant qu'un totem disparaisse." -- Needs review
L["How many seconds before a rune recharges."] = "Nombre de secondes avant la recharge d'une rune." -- Needs review
L["How many seconds between updates.|n[WARNING] By setting the frequency to 0 it will update every single frame redraw, if you want to disable frequent updating uncheck it don't set this to 0."] = "Le nombre de secondes entre les mises à jours.|n|n[ATTENTION] En paramétrant la fréquence à 0, la mise à jour s'effectuera à chaque retrace de trame. Si vous voulez désactiver les mises à jour fréquentes, ne définissez pas ceci à 0."
L["How many Shadow Orbs you have if you're Shadow"] = "Combien d'Orbes d'ombre vous avez si vous êtes en forme d'Ombre." -- Needs review
L["How much of the frames total height this bar should get, this is a weighted value, the higher it is the more it gets."] = "La partie de la hauteur totale du cadre cette barre doit utiliser. Il s'agit d'une valeur pondérée : plus elle est grande, plus la partie est importante."
L["How much spacing should be between each new row of groups."] = "Définit l'espacement entre chaque rangée de groupe."
L["How much spacing should be provided between all of the bars inside a unit frame, negative values move them farther apart, positive values bring them closer together. 0 for no spacing."] = "L'espacement entre toutes les barres d'un même cadre d'unité. Les valeurs négatives les éloignent les uns des autres, les valeurs positives les rapprochent. 0 pour n'avoir aucun espacement."
L["How much weight this should use when figuring out the total text width."] = "Le poids de ceci lors de la détermination de la largeur totale du texte."
L["How the frames should grow when a new column is added."] = "Définit la façon dont les cadres s'étendent quand une nouvelle colonne est ajoutée."
L["How the rows should grow when new group members are added."] = "La façon dont les rangées doivent s'étendre quand de nouveaux groupes sont ajoutés."
L["How you want this aura to be anchored to the unit frame."] = "La façon dont vous souhaitez que cet aura soit ancré au cadre d'unité."
L["Icon Size"] = "Taille d'icône" -- Needs review
L["If multiple auras are shown in the same indicator, the higher priority one is shown first."] = "Si plusieurs auras sont affichées dans le même indicateur, celle avec la priorité la plus élevée est montrée en premier." -- Needs review
L["If name is entered, it must be exact as it is case sensitive. Alternatively, you can use spell id instead."] = "Si un nom est entré, il doit être exact y compris les majuscules. Autrement, vous pouvez utiliser l'ID de sort à la place." -- Needs review
L["If the unit has a damage absorption shield on them, it will show the absolute absorb value, otherwise the units name."] = "Si l'unité a un bouclier d'absorption de dégâts, cela montrera la valeur absolue d’absorption, sinon le nom de l'unité." -- Needs review
L["If the unit has heals incoming, it will show the absolute incoming heal value, otherwise it will show the units name."] = "Si l'unité a des soins entrants, ceci affichera la valeur absolue des soins entrants. Le nom de l'unité sera affiché dans le cas contraire."
L["If the unit is a player then class is returned, if it's a NPC then the creature type."] = "Si l'unité est un joueur, sa classe est renvoyée. S'il s'agit d'un PNJ, son type de créature est renvoyé."
L["If the unit is a player then race is returned, if it's a NPC then the creature type."] = "Si l'unité est un joueur, sa race est renvoyée. S'il s'agit d'un PNJ, son type de créature est renvoyé."
L["If you don't, you will be unable to use any combo point features (Chi, Holy Power, Combo Points, Aura Points, etc) until you do so."] = "Sinon, vous ne pourrez pas utiliser les fonctions des points de combo (Chi, Puissance sacrée, Points de combo, Points d'aura, etc) jusqu'à ce que vous le fassiez." -- Needs review
L["Import"] = "Importer"
L["Import unit frame positions"] = "Importer les positions des cadres d'unité"
L["Import visibility settings"] = "Importer les paramètres de visibilité"
L["Inactive alpha"] = "Transp. qd inactif"
L["Incoming absorb"] = "Dégâts absorbés" -- Needs review
L["Incoming absorbs"] = "Dégâts absorbés" -- Needs review
L["Incoming heal"] = "Soin entrant"
L["Incoming heal (Absolute)"] = "Soins entrants (absolu)"
L["Incoming heal/Name"] = "Soins entrants/Nom"
L["Incoming heal (Percent)"] = "Soins entrants (pourcentage)" -- Needs review
L["Incoming heals"] = "Soins entrants"
L["Incoming heal (Short)"] = "Soins entrants (court)"
L["Index"] = "Index"
L["Indicator color"] = "Couleur de l'indicateur" -- Needs review
L["Indicator name"] = "Nom de l'indicateur" -- Needs review
L["Indicators"] = "Indicateurs"
L["Indicator this aura should be displayed in."] = "Indicateur dans lequel cette aura doit être affichée." -- Needs review
L["In range alpha"] = "Transp. si à portée"
L["Inset"] = "Encart"
L["Inside Bottom Left"] = "Intérieur Bas Gauche" -- Needs review
L["Inside Bottom Right"] = "Intérieur Bas Droite" -- Needs review
L["Inside Center"] = "Intérieur Centre" -- Needs review
L["Inside Center Left"] = "Intérieur Centre Gauche" -- Needs review
L["Inside Center Right"] = "Intérieur Milieu Droite" -- Needs review
L["Inside Top Left"] = "Intérieur Haut Gauche" -- Needs review
L["Inside Top Right"] = "Intérieur Haut Droite" -- Needs review
L["Instead of showing a solid color inside the indicator, the icon of the aura will be shown."] = "Au lieu d'afficher une couleur unie dans l'indicateur, l'icône de l'aura sera affichée" -- Needs review
L["Interrupted"] = "Interrompu"
L["Invalid interval entered, must be a number."] = "Intervalle entré invalide : doit être un nombre."
L["Invalid spell \"%s\" entered."] = "Sort entré \"%s\" invalide."
L["Invert colors"] = "Inverser les couleurs"
L["Layout manager"] = "Gestionnaire de disposition"
L["Leader / Assist"] = "Chef / Assistant" -- Needs review
L["Left"] = "Gauche"
L["Left Bottom"] = "Gauche Bas" -- Needs review
L["Left Center"] = "Gauche Centre" -- Needs review
L["Left text"] = "Texte de gauche"
L["Left Top"] = "Gauche Haut" -- Needs review
L["Let's you modify the base font size to either make it larger or smaller."] = "Vous permet de modifier la taille de police de base afin de la rendre plus grande ou plus petite."
L["Level"] = "Niveau"
L["Level (Colored)"] = "Niveau (coloré)"
L["Level %s - %s: %s/%s (%.2f%% done)"] = "Niveau %s - %s : %s/%s (%.2f%% terminé)"
L["Level %s - %s: %s/%s (%.2f%% done), %s rested."] = "Niveau %s - %s : %s/%s (%.2f%% terminé), %s reposé."
L["Level without any coloring."] = "Le niveau sans aucune coloration."
L["Light"] = "Léger"
L["Lightwell"] = "Puis de Lumière" -- Needs review
L["Lightwell bar"] = "Barre de Puis de Lumière" -- Needs review
L["Link"] = "Lien" -- Needs review
L["Linked spells"] = "Sorts liés" -- Needs review
L["Link from"] = "Lier depuis" -- Needs review
L["Link to"] = "Lier vers" -- Needs review
L["Lock frames"] = "Verr. cadres"
L["Locks the unit frame positionings hiding the mover boxes."] = "Verrouille la position du cadre d'unité, cachant les cadres de déplacement." -- Needs review
L["Low health"] = "Vie faible"
L["M"] = "M"
L["Main Assist"] = "Soutiens principaux"
L["Main Assists's are set by the Blizzard Main Assist system or mods that use it."] = "Les soutiens principaux sont définis par le système de soutiens de Blizzard ou les mods qui l'utilisent." -- Needs review
L["Main Assist Target"] = "Cibles des soutiens principaux"
L["Main Assist Target of Target"] = "Cible de la cible des soutiens principaux" -- Needs review
L["Main Tank"] = "Tanks principaux"
L["Main Tank's are set through the Raid frames, or through selecting the Tank role."] = "Les Tanks Principaux sont définis dans l'interface de raid, ou en choisissant le rôle de Tank." -- Needs review
L["Main Tank Target"] = "Cibles des tanks principaux"
L["Main Tank Target of Target"] = "Cible de la cible des tanks principaux" -- Needs review
L["Male"] = "Homme"
L["Mana"] = "Mana"
L["Manage Aura Filters"] = "Gérer filtres d'aura" -- Needs review
L["Management"] = "Gestion"
L["Manual position"] = "Position manuelle"
L["Master Looter"] = "Maître du butin" -- Needs review
L["MA ToT"] = "CdC Soutient" -- Needs review
L["Max columns"] = "Nbre max. de colonnes"
L["Max Demonic Fury (Short)"] = "Fureur démoniaque max. (court)" -- Needs review
L["Max health, uses a short format, 17750 is formatted as 17.7k, values below 10000 are formatted as is."] = "Vie maximale dans un format court : 17 750 est remplacé par 17.7k, et les valeurs inférieures à 10 000 sont affichées telles qu'elles."
L["Max HP (Absolute)"] = "Vie max. (absolue)"
L["Max HP (Short)"] = "Vie max. (court)"
L["Max power (Absolute)"] = "Puissance max. (absolue)"
L["Max power (Short)"] = "Puissance max. (court)"
L["Max power, uses a short format, 16000 is formatted as 16k, values below 10000 are formatted as is."] = "Puissance maximale dans un format court : 17 750 remplacé par 17.7k, et les valeurs inférieures à 10 000 sont affichées telles qu'elles."
L["Max rows"] = "Nbre max. de rangées"
L["Medium"] = "Moyen"
L["Minion"] = "Serviteur" -- Needs review
L["Miscellaneous"] = "Divers"
L["Missing HP (Short)"] = "Vie manquante (court)"
L["Missing power (Short)"] = "Puissance manquante (court)"
L["Monk mana bar"] = "Barre de mana de Moine" -- Needs review
L["Monochrome Outline"] = "Contour monochrome" -- Needs review
L["Moonkin"] = "Sélénien"
L["MT ToT"] = "CdC Tank" -- Needs review
L["Mushroom bar"] = "Barre des champignons" -- Needs review
L["Mushrooms"] = "Champignons" -- Needs review
L["Name"] = "Nom"
L["Name (Abbreviated)"] = "Nom (abbrévié)"
L["Name of a friendly spell to check range."] = "Nom d'un sort amical pour vérifier la portée." -- Needs review
L["Neutral"] = "Neutre"
L["Never (Disabled)"] = "Jamais (désactivé)"
L["New aura group"] = "Nouveau groupe d'aura" -- Needs review
L["New filter"] = "Nouveau filtre"
L["None"] = "Aucun"
L["None (Disabled)"] = "Aucun (désactivé)" -- Needs review
L["NPCs only"] = "PNJs uniquement"
L["Offline"] = "Hors ligne"
L["Offline timer"] = "Durée de déconnexion"
L["Off:%s"] = "Déco:%s"
L["Ok"] = "Ok" -- Needs review
L["On aggro"] = "À l'aggro"
L["On curable debuff"] = "Sur débuff dissipable" -- Needs review
L["On elite mobs"] = "Sur monstre élite" -- Needs review
L["On Friendly Units"] = "Sur Unités amies" -- Needs review
L["On Hostile Units"] = "Sur Unités hostiles" -- Needs review
L["Only active this aura inside an indicator if the group member does not have the aura."] = "Ne montre cette aura dans l'indicateur que si l’unité n'a pas cette aura." -- Needs review
L["Only auras you specifically cast will be shown."] = "Seules les auras lancées par vous seront affichées." -- Needs review
L["Only show if missing"] = "Seulement si manquant" -- Needs review
L["Only show self cast auras"] = "Seulement les siens" -- Needs review
L["Only show when mana"] = "Montrer seulement le mana" -- Needs review
L["On mouseover"] = "Au survol de la souris"
L["On rare mobs"] = "Sur monstre rare" -- Needs review
L["On %s units"] = "Sur %s unités" -- Needs review
L["Order"] = "Ordre"
L["Or you can set a position manually"] = "Ou vous pouvez définir une position manuellement"
L["Other Party/Phase Status"] = "Autre statut de Groupe/Phase" -- Needs review
L["Outline"] = "Contour"
L["Out of range alpha"] = "Transp. si hors de portée"
L["Outside bar limit"] = "Hors de la barre" -- Needs review
L["Override background"] = "Écraser l'arrière-plan" -- Needs review
L["Override color"] = "Outrepasser la couleur"
L["Party"] = "Groupe"
L["Party frames are hidden while in any sort of raid no matter how many people."] = "Les cadres du groupe sont cachés quelque soit le type de raid et le nombre de personne le composant."
L["Party frames are hidden while in a raid group with more than 5 people inside."] = "Cache les cadres du groupe quand vous vous trouvez dans un groupe de raid de plus de 5 personnes."
L["Party instances"] = "Instances de groupe"
L["Party Pet"] = "Fam. du groupe"
L["Party Target"] = "Cibles du groupe"
L["Party Target of Target"] = "Cible de la cible du groupe" -- Needs review
L["Party ToT"] = "CdC Groupe" -- Needs review
L["Percentage of width the portrait should use."] = "Définit le pourcentage de la largeur que le portrait doit utiliser."
L["Percentage value of how far outside the unit frame the absorbed health bar can go. 130% means it will go 30% outside the frame, 100% means it will not go outside."] = "Jusqu'où la barre des soins absorbés peut aller. 130% signifie qu'elle peut aller 30% hors du cadre, 100% signifie qu'elle n'en sortira pas." -- Needs review
L["Percentage value of how far outside the unit frame the incoming absorb bar can go. 130% means it will go 30% outside the frame, 100% means it will not go outside."] = "Jusqu'où la barre d'absorption peut aller. 130% signifie qu'elle peut aller 30% hors du cadre, 100% signifie qu’elle n'en sortira pas." -- Needs review
L["Percentage value of how far outside the unit frame the incoming heal bar can go. 130% means it will go 30% outside the frame, 100% means it will not go outside."] = "Jusqu'où la barre des soins entrant peut aller. 130% signifie qu'elle peut aller 30% hors du cadre, 100% signifie qu'elle n'en sortira pas." -- Needs review
L["Percent Demonic Fury"] = "Pourcentage de Fureur démoniaque" -- Needs review
L["Percent HP"] = "Pourcentage de vie"
L["Percent of the players current health that's being healed, if they have 100,000 total health and 15,000 is incoming then 15% is shown."] = "Pourcentage de la vie du joueur qui est soigné. S'il a 100,000 PV total et 15,000 arrivent, cela affichera 15%." -- Needs review
L["Percent power"] = "Pourcentage de puissance"
L["Per column"] = "Par colonne"
L["Per row"] = "Par rangée"
L["Pet"] = "Familier"
L["Pet Battle"] = "Combat de mascottes" -- Needs review
L["Pet Target"] = "Cible du familier"
L["Player"] = "Joueur"
L["player alt. power"] = "puissance alt. du joueur" -- Needs review
L["player cast bar"] = "barre d'incant. du joueur"
L["player power frames"] = "cadre de puissance du joueur" -- Needs review
L["Players only"] = "Joueurs uniquement"
L["Players will be colored by class."] = "Les joueurs seront coloriés selon la classe." -- Needs review
L["Player threat"] = "Menace du joueur"
L["Point"] = "Point"
L["Portrait"] = "Portrait"
L["Portrait type"] = "Type de portrait"
L["Position"] = "Position"
L["Positioning"] = "Positionnement" -- Needs review
L["Power"] = "Puissance"
L["Power bar"] = "Barre de puissance"
L["Power Type"] = "Type de puissance" -- Needs review
L["Prevents unit tooltips from showing while in combat."] = "Empêche les bulles d'aide des unités de s'afficher quand vous êtes en combat."
L["Primary means of coloring the health bar, color on aggro and color by reaction will override this if necessary."] = "Méthode principale pour colorer la barre de vie. Les couleur par aggro et couleur par réaction peuvent l'outrepasser si nécessaire." -- Needs review
L["Primary means of coloring the power bar. Coloring by class only applies to players, for non-players it will default to the power type."] = "Moyens principaux de colorier la barre de puissance. La coloration par classe s'applique uniquement aux joueurs, les non-joueurs utiliseront comme couleur le type de puissance par défaut." -- Needs review
L["Prioritize buffs"] = "Priorité aux buffs"
L["Priority"] = "Priorité" -- Needs review
L["Programming in Lua"] = "Programmer en Lua"
L["PvP Flag"] = "Marqueur JcJ"
L["PVP flag indicator, Horde for Horde flagged pvpers and Alliance for Alliance flagged pvpers."] = "Indicateur de marque JcJ. Horde pour les joueurs de la Horde marqués et Alliance pour ceux de l'Alliance."
L["PvP Flags"] = "Drapeaux PVP" -- Needs review
L["PVP:%s"] = "JcJ:%s"
L["PVP timer"] = "Durée JcJ" -- Needs review
L["Quest Boss"] = "Boss de quête" -- Needs review
L["Race"] = "Race"
L["Race (Smart)"] = "Race (intelligent)"
L["Rage"] = "Rage"
L["Raid"] = "Raid"
L["Raid assisting unit"] = "Soutien du raid sur l'unité"
L["Raid frames are hidden while in a raid group with 5 or less people inside."] = "Les cadres de raid sont masqués si vous vous trouvez dans un groupe de raid de 5 personnes ou moins." -- Needs review
L["Raid instances"] = "Instances de raid"
L["Raid Misc"] = "Raid divers" -- Needs review
L["Raid pet"] = "Fam. du raid"
L["Raid Role"] = "Rôle en raid" -- Needs review
L["Raid role indicator, adds a shield indicator for main tanks and a sword icon for main assists."] = "Indicateur de rôle de raid. Ajoute un bouclier pour les tanks principaux et une épée pour les soutiens principaux."
L["Raid Target"] = "Cible de raid" -- Needs review
L["Raid target indicator."] = "Indicateur de cible de raid"
L["Raid targeting unit"] = "Ciblage du raid sur l'unité"
L["Range Checker"] = "Vérification de portée" -- Needs review
L["Range indicator"] = "Indicateur de portée"
L["Rank 1"] = "Rang 1"
L["Rare"] = "Rare"
L["Rare Elite"] = "Élite rare"
L["Rare indicator"] = "Indicateur de rareté"
L["Rather than bars filling from left -> right, they will fill from bottom -> top."] = "Au lieu de se remplir de gauche à droite, les barres se rempliront de bas en haut." -- Needs review
L["Reaction color code, use [reactcolor][name][close] to color the units name by their reaction."] = "Code couleur de réaction utilisez [reactcolor][name][close] pour colorer les noms d'unité selon leur réaction."
L["Reaction color tag"] = "Tag couleur de réaction" -- Needs review
L["Ready Status"] = "Statut de l'appel" -- Needs review
L["Ready status of group members."] = "Résultats de l'appel des membres du groupe."
L["Red (>70% HP)"] = "Rouge (>70% PV)" -- Needs review
L["Relative point"] = "Point relatif"
L["Resources"] = "Ressources"
L["Resurrect Status"] = "Statut de résurrection" -- Needs review
L["Returns a color code of the threat situation with your target: Red for Aggro, Orange for High threat and Yellow to be careful."] = "Renvoie un code de couleur indiquant indiquant votre niveau de menace avec votre cible : rouge pour Aggro, orange pour Menace élevée et jaune pour Prudence."
L["Returns a color code of your general threat situation on all units: Red for Aggro, Orange for High threat and Yellow to watch out."] = "Renvoie un code de couleur indiquant votre niveau de menace envers toutes les unités : rouge pour Aggro, orange pour Menace élevée et jaune pour Prudence."
L["Returns a scaled threat percent of your aggro on your current target, always 0 - 100%."] = "Renvoie un pourcentage pondéré de la menace envers votre cible actuelle compris entre 0 et 100%."
L["Returns current health as a percentage, if the unit is dead or offline than that is shown instead."] = "Renvoie la vie actuelle sous forme de pourcentage, sauf si l'unité est morte ou déconnectée."
L["Returns current power as a percentage."] = "Renvoie la puissance actuelle sous forme de pourcentage."
L["Returns + if the unit is an elite or rare elite mob."] = "Renvoie + si l'unité est un monstre élite ou rare élite."
L["Returns Rare if the unit is a rare or rare elite mob."] = "Renvoie Rare si l'unité est un monstre rare ou rare élite."
L["Returns text based on the units general threat situation: Aggro for Aggro, High for being close to taking aggro, and Medium as a warning to be wary.|nThis cannot be used on target of target or focus target types of units."] = "Donne un texte selon la menace générale de l'unité : Aggro quand elle a l'aggro, High pour proche de prendre l'aggro, et Medium pour avertir d'être prudent.|nCela ne peut pas être utilisé sur des unités de type Cible de Cible ou Cible de Focus." -- Needs review
L["Returns text based on your general threat situation on all units: Aggro for Aggro, High for being near to pulling aggro and Medium as a general warning."] = "Renvoie un texte de indiquant votre niveau de menace envers toutes les unités : Aggro quand vous avez l'aggro, Élevé quand vous êtes sur le point de reprendre l'aggro et Moyen comme avertissement général."
L["Returns text based on your threat situation with your target: Aggro for Aggro, High for being close to taking aggro, and Medium as a general warning to be wary."] = "Renvoie un texte indiquant votre niveau de menace avec votre cible : Aggro quand vous avez l'aggro, Élevé quand vous êtes sur le point de reprendre l'aggro et Moyen comme avertissement général."
L["Returns the color code based off of the units level compared to yours. If you cannot attack them then no color is returned."] = "Renvoie un code de couleur basée sur la comparaison du niveau de l'unité par rapport à vous. Si vous ne pouvez pas l'attaquer, aucune code de couleur n'est renvoyé."
L["Returns the color code for the units threat situation in general: Red for Aggro, Orange for High threat and Yellow to watch out.|nThis cannot be used on target of target or focus target types of units."] = "Donne le code couleur selon la menace générale de l'unité : Rouge pour Aggro, Orange pour Menace élevée, Jaune pour faire attention.|nCela ne peut pas être utilisé sur des unités de type Cible de Cible ou Cible de Focus." -- Needs review
L["Returns the scaled threat percentage for the unit, if you put this on a party member you would see the percentage of how close they are to getting any from any hostile mobs. Always 0 - 100%.|nThis cannot be used on target of target or focus target types of units."] = "Donne le pourcentage de menace mis à l'échelle de l'unité. Si vous mettez cela sur un membre du groupe, vous verrez combien il est prêt d'en avoir de n'importe quel mob hostile. Toujours 0 - 100%.|nCela ne peut pas être utilisé sur des unités de type Cible de Cible ou Cible de Focus." -- Needs review
L["Returns the units current form if they are a druid, Cat for Cat Form, Moonkin for Moonkin and so on."] = "Renvoie la forme actuelle de l'unité s'il s'agit d'un druide (chat, sélénien, etc.)."
L["Returns the units sex."] = "Renvoie le sexe de l'unité."
L["Reverse fill"] = "Remplissage inversé" -- Needs review
L["Right"] = "Droite"
L["Right Bottom"] = "Droite Bas" -- Needs review
L["Right Center"] = "Droite Centre" -- Needs review
L["Right text"] = "Texte de droite"
L["Right Top"] = "Droite Haut" -- Needs review
L["Role the unit is playing."] = "Rôle joué par l'unité." -- Needs review
L["Row growth"] = "Sens d'ajout des rangées"
L["Row offset"] = "Décalage des rangées"
L["Rune bar"] = "Barre des runes"
L["Rune of Power"] = "Rune de puissance" -- Needs review
L["Rune of Power bar"] = "Barre de Rune de puissance" -- Needs review
L["Rune Timer"] = "Compteur de Runes" -- Needs review
L["Runic Power"] = "Puissance runique"
L["Same as [color:sit] except it only returns red if you have aggro, rather than transiting from yellow -> orange -> red."] = "Idem que [color:sit], à l'exception qu'il ne renvoie la couleur rouge que si vous avez l'aggro, au lieu d'effectuer la transition jaune -> orange -> rouge."
L["Same as [unit:color:sit] except it only returns red if the unit has aggro, rather than transiting from yellow -> orange -> red."] = "Idem que [unit:color:sit], à l'exception qu'il ne renvoie la couleur rouge que si l'unité a l'aggro, au lieu d'effectuer la transition jaune -> orange-> rouge."
L["%s aura groups disabled"] = "%s groupes d'auras désactivés" -- Needs review
L["Scale"] = "Échelle"
L["Scaled aura size"] = "Echelle d'aura spéciale" -- Needs review
L["Scaled threat percent"] = "Pourcentage de menace pondéré"
L["Scale for auras that you casted or can Spellsteal, any number above 100% is bigger than default, any number below 100% is smaller than default."] = "Echelle pour les auras que vous avez lancé ou pouvez volez. Plus de 100% sera plus grand que par défaut, moins de 100% sera plus petit." -- Needs review
L["Screen"] = "Écran"
L["Search"] = "Rechercher"
L["Search tags"] = "Recherche de tag"
L["See the documentation below for information and examples on creating tags, if you just want basic Lua or WoW API information then see the Programming in Lua and WoW Programming links."] = "Parcourez la documentation ci-dessous pour obtenir des informations et des exemples sur la création de tags. Si vous souhaitez des informations basiques concernant Lua ou l'API de WoW, reportez-vous aux liens vers Programming in Lua et WoW Programming."
L["Selecting a tag text from the left panel to change tags. Truncating width, sizing, and offsets can be done in the current panel."] = "Choisir un tag de texte du panneau de gauche pour changer les tags. La largeur, la taille, et le décalage peuvent être réglés dans le panneau actuel." -- Needs review
L["Select the units that you want to modify, any settings changed will change every unit you selected. If you want to anchor or change raid/party unit specific settings you will need to do that through their options.|n|nShift click a unit to select all/unselect all."] = "Sélectionnez les unités que vous voulez modifier. Tous les réglages modifiés changeront toutes les unités sélectionnées. Si vous voulez changer l'ancrage ou les réglages spéciaux de groupe/raid, vous devrez faire ça dans leurs options.|n|nShift-clic une unité pour les sélectionner/désélectionner toutes." -- Needs review
L["Separate raid frames"] = "Séparer les cadres"
L["Set Filter Zones"] = "Définir filtre par zone" -- Needs review
L["Sex"] = "Sexe"
L["%s frames"] = "cadres |2  %s"
L["Shadow Orbs"] = "Orbes d'ombre" -- Needs review
L["Short classification"] = "Classification courte"
L["Short classifications, R for Rare, R+ for Rare Elite, + for Elite, B for Boss or M for Minion nothing is shown if they aren't any of those."] = "Classification courte, R pour Rare, Rare+ pour Rare Élite, + pour Élite, B pour Boss, M pour Serviteur. Rien s'il ne sont d'aucune de ces catégories." -- Needs review
L["Short elite indicator"] = "Indicateur court d'élite"
L["Shorten damage absorption, if 13,000 damage will e absorbed, it will show 13k."] = "Absorption de dégâts courte. Si 13 000 dégâts seront absorbés, 13k sera affiché." -- Needs review
L["Shorten heal absorb value, if 17,000 healing will be absorbed, it will show 17k."] = "Valeur courte de soins absorbés. Si 17 000 de soins seront absorbés, 17k sera affiché." -- Needs review
L["Shorten incoming heal value, if 13,000 healing is incoming it will show 13k."] = "Raccourcit la valeur des soins entrants. Si 13 000 points de soins arrivent, 13k sera affiché." -- Needs review
L["Short version of [druidform], C = Cat, B = Bear, F = Flight and so on."] = "Version courte de [druidform], C = Félin, B = Ours , F = Vol et ainsi de suite."
L["Show a background behind the bars with the same texture/color but faded out."] = "Affiche un arrière-plan derrière les barres avec la même texture/couleur mais estompé."
L["Show any other auras"] = "Montrer toute autre aura" -- Needs review
L["Show as bar"] = "Afficher comme barre"
L["Show aura duration"] = "Montrer durée de l'aura" -- Needs review
L["Show aura icon"] = "Montrer icône de l'aura" -- Needs review
L["Show auras stack"] = "Montrer stacks de l'aura" -- Needs review
L["Show background"] = "Aff. l'arrière-plan"
L["Show boss debuffs"] = "Montrer débuffs de boss" -- Needs review
L["Show buffs before debuffs when sharing the same anchor point."] = "Affiche les buffs avant les débuffs quand ces deux types d'auras partagent le même point d'ancrage."
L["Show castable on other auras"] = "Montrer auras lancées par d'autres" -- Needs review
L["Show casted by boss"] = "Montrer auras lancées par les boss" -- Needs review
L["Show cast name"] = "Aff. nom de l'incant."
L["Show cast rank"] = "Aff. rang de l'incant."
L["Show cast time"] = "Aff. tps d'incantation"
L["Show consolidable auras"] = "Montrer auras regroupables" -- Needs review
L["Show curable debuffs"] = "Montrer auras dissipables" -- Needs review
L["Show curable/removable auras"] = "Montrer auras dissipables" -- Needs review
L["Show Heal Absorbs"] = "Montrer soins absorbés" -- Needs review
L["Show icon durations"] = "Durée sur l'icône." -- Needs review
L["Show incoming absorbs"] = "Montrer les absorption prévues" -- Needs review
L["Show incoming heals"] = "Afficher les soins entrants" -- Needs review
L["Show inside"] = "Montrer dedans" -- Needs review
L["Show party as raid"] = "Aff. groupe comme raid"
L["Show player in party"] = "Aff. joueur ds groupe"
L["Shows a bar for alternate power info (used in some encounters)"] = "Affiche une barre contenant les informations de la puissance alternative (utilisé dans certaines rencontres)."
L["Shows a cooldown wheel on the indicator with how much time is left on the aura."] = "Affiche une spirale de recharge sur l'indicateur qui montre le temps restant sur l'aura." -- Needs review
L["Shows AFK, DND or nothing depending on the units away status."] = "Affiche ABS, NPD ou rien du tout selon le statut de l'unité."
L["Shows combat feedback, last healing the unit received, last hit did it miss, resist, dodged and so on."] = "Affiche les retours de combat : dernier dégâts ou soins reçus par l'unité, esquive, etc."
L["Shows current and maximum health in absolute form, 17500 health will be showed as 17500 health."] = "Affiche la vie actuelle et maximale en valeur absolue."
L["Shows current and maximum power in absolute form, 18000 power will be showed as 18000 power."] = "Affiche la puissance actuelle et maximale en valeur absolue."
L["Shows current group number of the unit."] = "Affiche le numéro de groupe actuel de l'unité."
L["Shows current health value in absolute form meaning 15000 health is shown as 15000."] = "Affiche les points de vie actuels de la vie en valeur absolue."
L["Shows current power value in absolute form, 15000 power will be displayed as 1500 still."] = "Affiche les points de puissance actuels puissance en valeur absolue."
L["Shows debuffs cast by a boss."] = "Affiche les débuffs lancés par un boss." -- Needs review
L["Shows debuffs that you can cure."] = "Affiche les débuffs que vous pouvez dissiper." -- Needs review
L["Shows how long an unit has been AFK or DND."] = "Indique depuis combien de temps une unité est ABS ou en mode NPD."
L["Shows how long an unit has been offline."] = "Affiche depuis combien de temps une unité est hors ligne."
L["Shows how long until your PVP flag drops, will not show if the flag is manually on or you are in a hostile zone.|n|nThis will only work for yourself, you cannot use it to see the time left on your party or raid."] = "Affiche le temps avant que le mode PVP se désactive. N'apparaitra pas si le mode est activé manuellement ou dans une zone hostile.|n|nCela ne marchera que pour vous, vous ne pouvez pas voir le temps restant pour votre groupe ou raid." -- Needs review
L["Shows maximum health in absolute form, 14000 health is showed as 14000 health."] = "Affiche les points de vie maximaux en valeur absolue."
L["Shows maximum power in absolute form, 13000 power is showed as 13000 power."] = "Affiche les points de puissance maximaux en valeur absolue."
L["Shows Offline, Dead, Ghost or nothing depending on the units current status."] = "Affiche Hors-ligne, Mort, Fantôme ou rien du tout selon le statut de l'unité."
L["Shows that a NPC is a boss for a quest."] = "Indique qu'un PNJ est un boss lié à une quête." -- Needs review
L["Shows the absolute staggered damage, if 16,000 damage is staggered, shows 16,000."] = "Montre la valeur absolue des dégâts reportés. Si 16000 dégâts sont reportés, montre 16000." -- Needs review
L["Shows the current staggered damage, if 12,000 damage is staggered, shows 12k."] = "Montre les dégâts reportés. Si 12000 dégâts sont reportés, montre 12k." -- Needs review
L["Shows the mana power bar for Mistweaver Monks."] = "Montre la barre de mana pour les Moines Tisse-brume" -- Needs review
L["Show's the units guild name if they are in a guild."] = "Affiche le nom de la guilde de l'unité si elle en a une."
L["Shows the units health as a percentage rounded to the first decimal, meaning 61 out of 110 health is shown as 55.4%."] = "Affiche la vie de l'unité comme pourcentage arrondi à la première décimale."
L["Shows what kind of pet the unit is for pet battles."] = "Indique quel genre de mascotte est l'unité dans les combat de mascottes." -- Needs review
L["Shows when a party member is in a different phase or another group."] = "Indique quand un membre du groupe est dans une phase différente ou dans un autre groupe." -- Needs review
L["Show your auras"] = "Montrer vos auras" -- Needs review
L["Simple aura filtering by whitelists and blacklists."] = "Filtrage simple des auras à l'aide de listes blanches et noires."
L["Size"] = "Taille"
L["Smart level"] = "Niveau intelligent"
L["Smart level, returns Boss for bosses, +50 for a level 50 elite mob, or just 80 for a level 80."] = "Niveau intelligent : renvoie Boss pour les boss, +50 pour un monstre élite de niveau 50 ou juste 80 pour un niveau 80."
L["Smart number formating for [curmaxhp], numbers below 1,000,000 are left as is, numbers above 1,000,000 will use the short version such as 1m."] = "Affichage intelligent des nombres pour [curmaxhp]. Ceux inférieurs à 1 000 000 sont laissés tels quels, ceux supérieurs utiliseront la version courte du type 1m."
L["Smart number formating for [curmaxpp], numbers below 1,000,000 are left as is, numbers above 1,000,000 will use the short version such as 1m."] = "Affichage intelligent des nombres pour [curmaxpp]. Ceux inférieurs à 1 000 000 sont laissés tels quels, ceux supérieurs utiliseront la version courte du type 1m."
L["%s member"] = "membre |2 %s"
L["Solid color to use in the indicator, only used if you do not have use aura icon enabled."] = "Couleur unie à utiliser dans l'indicateur, utilisée seulement si vous n’utilisez pas l'icône de l'aura." -- Needs review
L["Sorting"] = "Tri"
L["Sort method"] = "Méthode de tri"
L["Sort order"] = "Ordre de tri"
L["Soul shards"] = "Fragments d'âme" -- Needs review
L["Soul Shards"] = "Fragments d'âme"
L["Spacing"] = "Espacement"
L["Spacing between each row"] = "Espacement entre chaque rangée"
L["Spell ID %s"] = "ID de sort %s" -- Needs review
L["Spell Name"] = "Nom de Sort" -- Needs review
L["Spell Name/ID"] = "Nom/ID du sort" -- Needs review
L["Spell you want to link to a primary aura, the casing must be exact."] = "Sort que vous voulez lier à une aura principale. Les majuscules doivent être exactes." -- Needs review
L["Splits raid frames into individual frames for each raid group instead of one single frame.|nNOTE! You cannot drag each group frame individualy, but how they grow is set through the column and row growth options."] = "Sépare les cadres de raid en cadres individuels pour chaque groupe au lieu d'un seul cadre.|nNOTE ! Vous ne pouvez pas déplacer chaque groupe individuellement, mais leur croissance est gérée par les options de croissance des colonnes et rangées." -- Needs review
L["%s (%s): %s/%s (%.2f%% done)"] = "%s (%s) : %s/%s (%.2f%% terminé)"
L["Stagger"] = "Report" -- Needs review
L["Stagger bar"] = "Barre de Report" -- Needs review
L["Stagger bar color when the staggered amount is <30% of your HP."] = "Couleur de la barre de Report quand le montant reporté est <30% de vos PV." -- Needs review
L["Stagger bar color when the staggered amount is >30% of your HP."] = "Couleur de la barre de Report quand le montant reporté est >30% de vos PV." -- Needs review
L["Stagger bar color when the staggered amount is >70% of your HP."] = "Couleur de la barre de Report quand le montant reporté est >70% de vos PV." -- Needs review
L["Stagger (Monk)"] = "Report (Moine)" -- Needs review
L["Stagger (Monk/Absolute)"] = "Report (Moine/Absolu)" -- Needs review
L["Static"] = "Statique"
L["Statue"] = "Statue" -- Needs review
L["Statue bar"] = "Barre de Statue" -- Needs review
L["Status"] = "Statut"
L["Status indicator, shows if the unit is currently in combat. For the player it will also show if you are rested."] = "Indicateur de statut, affiche si l'unité est actuellement en combat. Pour le joueur, il indique également si vous êtes en repos."
L["Stealable/Curable/Dispellable"] = "Volable/Soignable/Dissipable" -- Needs review
L["Style of borders to show for all auras."] = "Le style des bordures à afficher pour toutes les auras."
L["T"] = "T"
L["Tag list"] = "Liste des tags"
L["Tag name"] = "Nom du tag"
L["Tags"] = "Tags"
L["Tag that you will use to access this code, do not wrap it in brackets or parenthesis it's automatically done. For example, you would enter \"foobar\" and then access it with [foobar]."] = "Tag que vous utiliserez pour accéder à ce code. Ne le mettez pas entre crochets ou parenthèses, c'est automatique. Par exemple entrez \"foobar\" et utilisez-le ensuite avec [foobar]." -- Needs review
L["Talent spec of your arena opponents."] = "Spécialisation de vos adversaires d'arène." -- Needs review
L["Target"] = "Cible"
L["Target of Target"] = "Cible de la cible"
L["Target of Target of Target"] = "Cible de la cible de la cible"
L["Test Aura"] = "Aura de test"
L["Test spell"] = "Sort de test"
L["Text"] = "Texte"
L["Text Management"] = "Gestion de texte" -- Needs review
L["Text name"] = "Nom du texte"
L["Text name that you can use to identify this text from others when configuring."] = "Un nom de texte que vous pouvez utiliser pour identifier ce texte parmi d'autres lors de la configuration."
L["Text parent"] = "Texte parent"
L["Text/Tags"] = "Texte/Tags"
L["The blacklist \"%s\" already exists."] = "La liste noire \"%s\" existe déjà."
L["The check boxes below will allow you to enable or disable units.|n|n|cffff2020Warning!|r Target of Target units have a higher performance cost compared to other units. If you have performance issues, please disable those units or reduce the features enabled for those units."] = "Les cases ci-dessous permettent d'activer ou désactiver des unités.|n|n|cffff2020Attention !|r Les Cible de la Cible ont un plus grand impact sur les performances comparés aux autres unités. Si vous avez des problèmes de performances, désactivez ces unités ou réduisez le nombre d'éléments actifs pour ces unités." -- Needs review
L["The player frame will not be hidden regardless, you will have to manually disable it either entirely or per zone type."] = "Le cadre du joueur ne sera pas caché dans tous les cas, vous devrez manuellement le désactiver soit entièrement soit par type de zone."
L["The tag \"%s\" already exists."] = "Le tag \"%s\" existe déjà."
L["The unit frames you see are examples, they are not perfect and do not show all the data they normally would.|n|nYou can hide them by locking them through /shadowuf or clicking the button below."] = "Les cadres d'unité que vous voyez sont des exemples ; ils ne sont pas parfaits et n'affichent pas toutes les données qu'ils afficheraient en temps normal.|n|nVous pouvez les cacher en les verrouillant via /shadowuf ou en cliquant sur le bouton ci-dessous."
L["The whitelist \"%s\" already exists."] = "La liste blanche \"%s\" existe déjà."
L["Thick outline"] = "Contour épais"
L["Thin outline"] = "Contour fin" -- Needs review
L["This bar will automatically hide when you are at the level cap, or you do not have any reputations tracked."] = "Cette barre se cachera automatiquement quand vous atteindrez le niveau maximal, ou si vous ne suivez aucune réputation."
L[ [=[This color will be used if the indicator shown is your own, only applies if icons are not used.
Handy if you want to know if a target has a Rejuvenation on them, but you also want to know if you were the one who casted the Rejuvenation.]=] ] = [=[Cette couleur sera utilisée si l'indicateur affiché est le votre, si l'icône n'est pas utilisée.
Pratique si vous voulez savoir si une cible a Récupération sur elle, mais que vous voulez aussi savoir si vous êtes celui qui a lancé cette Récupération.]=] -- Needs review
L["This filter has no auras in it, you will have to add some using the dialog above."] = "Ce filtre ne contient aucune aura. Ajoutez en au moins une ci-dessus."
L["This filter has no aura types set to filter out."] = "Ce filtre n'a aucun type d'auras à filtrer."
L["This is a good guide on how to get started with programming in Lua, while you do not need to read the entire thing it is a helpful for understanding the basics of Lua syntax and API's."] = "Il s'agit d'un bon guide sur la façon de s'initier à la programmation en Lua. Bien que vous ne devez pas tout lire, il est très utile pour comprendre les bases de la syntaxe et des APIs Lua."
L["This unit depends on another to work, disabling %s will disable %s."] = "Cette unité dépend d'une autre pour fonctionner : désactiver %s désactivera %s."
L["This unit has child units that depend on it, you need to enable this unit before you can enable its children."] = "Cette unité possède des unités-filles qui dépendent d'elle :  vous devez activer cette unité avant de pouvoir activer ses filles."
L["This will be set for your current class only."] = "Ce sera défini pour votre classe actuelle uniquement." -- Needs review
L["This will disable the automatic detection of what events this tag will need, you should leave this unchecked unless you know what you are doing."] = "Ceci désactivera la détection automatique des événements que ce tag aura besoin. Il est vivement conseillé de laisser ceci décoché à moins que vous savez ce que vous faites."
L["This will override all background colorings for bars including custom set ones."] = "Ceci écrasera toutes les colorations d'arrière-plan des barres, y compris celles personnalisées."
L["Threat"] = "Menace"
L["Threat situation"] = "Situation de la menace"
L["Tile size"] = "Taille de carreau"
L["Timer Text"] = "Texte du compteur" -- Needs review
L["Top"] = "Haut" -- Needs review
L["Top Center"] = "Haut Centre" -- Needs review
L["Top Left"] = "Haut Gauche" -- Needs review
L["Top Right"] = "Haut Droite" -- Needs review
L["Total number of active holy power."] = "Nombre total de puissances sacrées actives." -- Needs review
L["Total number of active soul shards."] = "Nombre total de fragments d'âme actifs" -- Needs review
L["Total number of combo points you have on your target."] = "Nombre total de points de combo que vous avez sur votre cible."
L["Totem bar"] = "Barre des totems"
L["Totem Timer"] = "Compteur de totems" -- Needs review
L["Travel"] = "Voyage"
L["Tree"] = "Arbre"
L["Turns this widget into a bar that can be resized and ordered just like health and power bars."] = "Transforme ce widget en barre qui peut être redimensionnée et ordonnée de la même façon que les barres de vie et de puissance."
L["Unattackable hostile"] = "Hostile inattaquable"
L["Unchecking this will completely disable aura indicators for %s."] = "Décocher pour désactiver complètement les indicateurs d'auras pour %s." -- Needs review
L["Unit color code on aggro"] = "Code couleur d'unité si aggro" -- Needs review
L["Unit colored situation"] = "Couleur de situation d'unité" -- Needs review
L["Unit Configuration"] = "Configuration d'unités" -- Needs review
L["Unit faction"] = "Faction de l'unité"
L["Unit name"] = "Nom de l'unité"
L["Unit name (Class colored)"] = "Nom de l'unité (coloré selon la classe)"
L["Unit name colored by class."] = "Nom de l'unité coloré selon la classe."
L["Units"] = "Unités"
L["Units alignment, Thrall will return Horde, Magni Bronzebeard will return Alliance."] = "Faction de l'unité : Thrall renvoie Horde, tandis que Magni Barbe-de-bronze renvoie Alliance."
L["Unit scaled threat"] = "Menace pondérée de l'unité"
L["Units classification, Rare, Rare Elite, Elite, Boss or Minion nothing is shown if they aren't any of those."] = "Classification d'unités, Rare, Rare Élite, Élite,  Boss, Serviteur. Rien s'il ne sont d'aucune de ces catégories." -- Needs review
L["Unit server"] = "Serveur de l'unité"
L["Unit server, if they are from your server then nothing is shown."] = "Serveur de l'unité. Si l'unité provient de votre serveur, rien n'est affiché."
L["Unit situation name"] = "Nom de situation d'unité" -- Needs review
L["Units per column"] = "Unités par colonne"
L["Units race, Blood Elf, Tauren, Troll (unfortunately) and so on."] = "Race de l'unité : Elfe de sang, Tauren, etc."
L["Units that should have the aura groups settings changed below."] = "Les unités dont les réglages de groupe d'aura seront changés ci-dessous." -- Needs review
L["Units to change"] = "Unités à changer" -- Needs review
L["Unknown"] = "Inconnu" -- Needs review
L["Unlink frames"] = "Délier cadres" -- Needs review
L["Up"] = "Haut"
L["Update interval"] = "Intervalle de m. à j."
L["Uses the icon of the totem being shown instead of a status bar."] = "Utilise l'icône du totem au lieu d'une barre de statut." -- Needs review
L["Using unit settings"] = "Utilisation des paramètres d'unité"
L["Various units can be enabled through this page, such as raid or party targets."] = "De nombreuses unités peuvent être activés grâce à cette page, telles que les unités de raid ou les cibles du groupe."
L["Vehicle"] = "Véhicule"
L["Vehicles"] = "Véhicules"
L["Vertical growth"] = "Croissance verticale" -- Needs review
L["View"] = "Voir"
L["Visibility"] = "Visibilité"
L["WARNING! ShadowedUF_Indicators has been deprecated as v4 and is now built in. Please delete ShadowedUF_Indicators, your configuration will be saved."] = "ATTENTION ! ShadowedUF_Indicators est obsolète car il est intégré avec la v4. Veuillez supprimer ShadowedUF_Indicators, votre configuration sera sauvée." -- Needs review
L["WARNING: This will unlink all frames from each other so you can move them without another frame moving with it."] = "ATTENTION : ceci déliera tous les cadres des uns et des autres afin que vous puissiez les déplacer sans qu'un autre cadre bouge avec."
L["What group this aura belongs to, this is where you will find it when configuring."] = "Le groupe auquel cette aura appartient. C'est là que vous la trouverez pour la configurer." -- Needs review
L["What type of auras should be enlarged, use the scaled aura size option to change the size."] = "Quel type d'aura doit être agrandi. Utilisez l'option Echelle d'aura spéciale pour régler la taille." -- Needs review
L["When the unit is mising health, the [missinghp] tag is shown, when they are at full health then the [name] tag is shown. This lets you see -1000 when they are missing 1000 HP, but their name when they are not missing any."] = "Quand il manque de la vie à l'unité, le tag [missinghp] est affiché, quand sa vie est pleine le tag [name] est affiché. Cela vous permet de voir -1000 s'il leur manque 1000 PV, mais leur nom quand il ne leur manque rien." -- Needs review
L["When this filter is active, apply the filter to buffs."] = "Quand ce filtre est actif, applique le filtre aux buffs."
L["When this filter is active, apply the filter to debuffs."] = "Quand ce filtre est actif, applique le filtre aux debuffs."
L["When to color the empty bar by reaction, overriding the default color by option."] = "Quand colorer la barre vide selon la réaction, outrepassant la couleur par défaut." -- Needs review
L["When to color the health bar by the units reaction, overriding the color health by option."] = "Quand colorer la barre de vie selon la réaction de l'unité, outrepassant la couleur de barre de vie." -- Needs review
L["When to show cooldown rings on auras"] = "Quand afficher la spirale de recharge sur les auras." -- Needs review
L["Where inside the frame the text should be anchored to."] = "L'endroit à l'intérieur du cadre où le texte doit être ancré."
L["Where to anchor the cast name text."] = "L'endroit où ancrer le texte du nom de l'incantation."
L["Where to anchor the cast time text."] = "L'endroit où ancrer le texte de la durée d'incantation."
L["Whether auras you casted should be shown"] = "Afficher les auras que vous avez lancées." -- Needs review
L["Whether to show any auras casted by the boss"] = "Afficher les auras lancées par le boss." -- Needs review
L["Whether to show any auras that would be consolidated by the default UI."] = "Afficher les auras qui seraient regroupées dans l'interface de base." -- Needs review
L["Whether to show any debuffs you can remove, cure or steal."] = "Afficher les débuffs que vous pouvez enlever, soigner, ou voler." -- Needs review
L["Whether to show auras that do not fall into the above categories."] = "Afficher les auras qui n'appartiennent pas aux catégories précédentes." -- Needs review
L["Whether to show buffs that you cannot cast."] = "Afficher les buffs que vous ne pouvez pas lancer." -- Needs review
L["Whitelist"] = "Liste blanche"
L["Whitelist filters"] = "Filtres des listes blanches"
L["Whitelists"] = "Listes blanches"
L["Whitelists will hide any aura not in the filter group.|nBlacklists will hide auras that are in the filter group."] = "Les listes blanches cacheront toutes les auras qui ne sont pas présentes dans le groupe du filtre.|nLes listes noires cacheront toutes les auras qui sont présentes dans le groupe du filtre."
L["Widget Size"] = "Taille des éléments" -- Needs review
L["Width"] = "Largeur"
L["Width percent"] = "%tage de la largeur"
L["Width weight"] = "Poids en largeur"
L["Will fill right -> left when using horizontal growth, or top -> bottom when using vertical growth."] = "Se remplira de droite à gauche en croissance horizontale, ou de haut en bas en croissance verticale." -- Needs review
L["Wondering what all of the tabs for the unit configuration mean? Here's some information:|n|n|cfffed000General:|r Portrait, range checker, combat fader, border highlighting|n|cfffed000Frame:|r Unit positioning and frame anchoring|n|cfffed000Bars:|r Health, power, empty and cast bar, and combo point configuration|n|cfffed000Widget size:|r All bar and portrait sizing and ordering options|n|cfffed000Auras:|r All aura configuration for enabling/disabling/enlarging self/etc|n|cfffed000Indicators:|r All indicator configuration|n|cfffed000Text/Tags:|r Tag management as well as text positioning and width settings.|n|n|n*** Frequently looked for options ***|n|n|cfffed000Raid frames by group|r - Unit configuration -> Raid -> Raid -> Separate raid frames|n|cfffed000Class coloring:|r Bars -> Color health by|n|cfffed000Timers on auras:|r You need OmniCC for that|n|cfffed000Showing/Hiding default buff frames:|r Hide Blizzard -> Hide buff frames|n|cfffed000Percentage HP/MP text:|r Tags/Text tab, use the [percenthp] or [percentpp] tags|n|cfffed000Hiding party based on raid|r - Unit configuration -> Party -> Party -> Hide in 6-man raid/Hide in any raid"] = "Vous vous demandez ce que tous les onglets de la configuration d'unité signifient ? Voici quelques informations :|n|n|cfffed000Général :|r Portrait, vérification des portées, fondu de combat, surbrillance de la bordure|n|cfffed000Cadre:|r Positionnement de l'unité et ancrage du cadre|n|cfffed000Barres :|r Vie, puissance, barre d'incantation et vide, configuration des points de combo|n|cfffed000Taille de widget :|r options de taille et d'ordre de toutes les barres et du portrait|n|cfffed000Auras :|r Config. de toutes les auras (activation/désactivation/élargissement des siens/etc.)|n|cfffed000Indicateurs :|r Configuration de tous les indicateurs|n|cfffed000Texte/Tags :|r Gestion des tags ainsi que paramètres de positionnement et de largeur du texte|n|n|n*** Options fréquemment recherchées ***|n|n|cfffed000Cadres de raid par groupe :|r Configuration d'unité -> Raid -> Raid -> Séparer les cadres de raid|n|cfffed000Coloration selon la classe :|r Barres -> Colorer la vie par|n|cfffed000Durée sur les auras :|r Il vous faut OmniCC pour cela|n|cfffed000Afficher/cacher le cadre des buffs par défaut :|r Cacher Blizzard -> Cacher cadre des buffs|n|cfffed000Texte de pourcentage des PVs/PMs :|r Onglet Tags/Texte, utilisez le tag [percenthp] ou [percentpp]|n|cfffed000Cacher le groupe selon le raid|r - Configuration d'unité -> Groupe -> Groupe -> Cacher si raid > 5 joueurs/Cacher dans tous les raids"
L["Works the same as [%s], but this is only shown if the unit is in Cat or Bear form."] = "Fonctionne de la même manière que [%s], mais s'affiche uniquement si l'unité est en forme de félin ou d'ours." -- Needs review
L["Works the same as [%s], but this is only shown if you are a Mistweaver Monk."] = "Fonctionne comme [%s], mais n'est montré que si vous êtes un Moine Tisse-brume." -- Needs review
L["Works the same as [%s], but this is usedd to show Demonic Fury power for Demonology Warlocks."] = "Fonctionne de la même manière que [%s], mais utilisé pour afficher la puissance de Fureur démoniaque pour les démonistes spécialisés en Démonologie." -- Needs review
L["WoW Programming"] = "Programmation WoW"
L["WoW Programming is a good resource for finding out what difference API's do and how to call them."] = "WoW Programming est un bon outil pour trouver ce que font les différentes API et comment y faire appel."
L["X Offset"] = "Décalage en X"
L["XP/Rep bar"] = "Barre d'EXP/de réput."
L["Yellow (>30% HP)"] = "Jaune (>30% PV)" -- Needs review
L["Y Offset"] = "Décalage en Y"
L["You can add additional text with tags enabled using this configuration, note that any additional text added (or removed) effects all units, removing text will reset their settings as well.|n|nKeep in mind, you cannot delete the default text included with the units."] = "Vous pouvez ajouter des textes additionnels avec les tags activés avec cette config. Notez que tout texte ajouté (ou enlevé) affecte toutes les unités. Enlever un texte réinitialisera également leurs réglages.|n|nNoubliez pas, vous ne pouvez pas supprimer les textes par défaut inclus avec les unités." -- Needs review
L["You can add new custom tags through this page, if you're looking to change what tags are used in text look under the Text tab for an Units configuration."] = "Vous pouvez ajouter de nouveaux tags personnalisés sur cette page. Si vous cherchez à changer quels tags sont utilisés en texte, regardez dans l'onglet Texte d'une configuration d'unité." -- Needs review
L["You can disable aura filters and groups for units here. For example, you could set an aura group that shows DPS debuffs to only show on the target."] = "Vous pouvez désactiver les filtres et groupes d'auras pour des unités ici. Par exemple, vous pourriez faire un groupe d'auras qui montre les débuffs pour DPS qui ne s'affiche que sur la cible." -- Needs review
L["You can find more information on creating your own custom tags in the \"Help\" tab above."] = "Vous pouvez trouver plus d'informations sur la façon de créer vos propres tags dans l'onglet \"Aide\" ci-dessus."
L["You can find more information on creating your own custom tags in the \"Help\" tab above.|nSUF will attempt to automatically detect what events your tag will need, so you do not generally need to fill out the events field."] = "Vous trouverez plus d'informations sur la création de vos propres tags dans l'onglet \"Aide\" ci-dessus.|nSUF essaiera de détecter automatiquement quels évènements votre tag utilise, vous n'aurez donc généralement pas besoin de remplir ces champs." -- Needs review
L["You can import another Shadowed Unit Frame users configuration by entering the export code they gave you below. This will backup your old layout to \"Import Backup\".|n|nIt will take 30-60 seconds for it to load your layout when you paste it in, please by patient."] = "Vous pouvez importer la configuration d'autres utilisateurs de Shadowed Unit Frames en entrant ci-dessous le code d'exportation qu'ils vous donnent. Cela aura pour effet de sauvegarder votre ancienne disposition dans \"Sauvegarde d'importation\".|n|nIl faudra entre 30 et 60 secondes pour importer la disposition que vous aurez collé, soyez donc patient."
L["You can link auras together using this, for example you can link Mark of the Wild to Gift of the Wild so if the player has Mark of the Wild but not Gift of the Wild, it will still show Mark of the Wild as if they had Gift of the Wild."] = "Vous pouvez lier des auras ensemble avec ça. Par exemple vous pouvez lier Marque du fauve à Don du fauve, pour qu'un joueur qui a Marque du fauve mais pas Don du fauve apparaisse comme s'il l'avait." -- Needs review
L["You cannot edit this tag because it is one of the default ones included in this mod. This function is here to provide an example for your own custom tags."] = "Vous ne pouvez pas éditer ce tag car il s'agit d'un des tags par défaut de cet addon. Cette fonction est présente afin de fournir un exemple pour vos propres tags."
L["You cannot name a tag \"%s\", tag names should contain no brackets or parenthesis."] = "Vous ne pouvez pas nommer un tag \"%s\" : les noms de tag ne peuvent contenir de crochets ou de parenthèses."
L["You can override what aura is enabled on a per-class basis, note that if the aura is disabled through the main listing, then your class settings here will not matter."] = "Vous pouvez décider quelle aura est activée classe par classe. Notez que si l'aura est désactivée dans la liste principale, le réglage par classe ne changera rien." -- Needs review
L["You can set what unit frame should use what filter group and in what zone type here, if you want to change what auras goes into what group then see the \"Manage aura groups\" option."] = "Vous pouvez définir quel cadre d'unité utilise quel groupe de filtres dans quelles zones ici. Si vous voulez changer quelle aura va dans quel groupe, voyez les options \"Gérer les filtres d'aura\"." -- Needs review
L["You do not have any filters of this type added yet, you will have to create one in the management panel before this page is useful."] = "Vous n'avez pas encore ajouté de filtre de ce type, vous devez en créer un dans le panneau de gestion avant que cette page ne soit utile."
L["You have entered combat, unit frames have been locked. Once you leave combat you will need to unlock them again through /shadowuf."] = "Vous venez d'entrer en combat, les cadres d'unité ont été verrouillées. Une fois que vous êtes sorti de combat, vous devrez les déverrouiller à nouveau via la commande /shadowuf"
L["You have to set the events to fire, you can only enter letters and underscores, \"FOO_BAR\" for example is valid, \"APPLE_5_ORANGE\" is not because it contains a number."] = "Vous devez définir les événements à déclencher en utilisant uniquement des lettres et des tirets bas. Par exemple, \"FOO_BAR\" est valide, tandis que \"APPLE_5_ORANGE\" ne l'est pas car il contient un nombre."
L["You must enter a number that is 0 or higher, negative numbers are not allowed."] = "Vous devez entrer un nombre supérieur à 0 : les nombres négatifs ne sont pas autorisés."
L["You must enter a tag name."] = "Vous devez entrer un nom de tag."
L["You must restart Shadowed Unit Frames."] = "Vous devez redémarrer Shadowed Unit Frames." -- Needs review
L["You must wrap your code in a function."] = "Vous devez placer votre code dans une fonction."
L["Your active layout is the profile used for import backup, this cannot be overwritten by an import. Change your profiles to something else and try again."] = "Votre disposition active est le profil utilisé pour la sauvegarde d'importation, ceci ne peut pas être écrasé par un import. Changez vos profils vers quelque chose d'autre et essayez à nouveau."
L["Your aura color"] = "Couleur de votre aura" -- Needs review
L["Your Auras"] = "Vos auras" -- Needs review
L["Your code must be wrapped in a function, for example, if you were to make a tag to return the units name you would do:|n|nfunction(unit, unitOwner)|nreturn UnitName(unitOwner)|nend"] = "Votre code doit être contenu dans une fonction. Par exemple, si vous voulez créer un tag qui renvoie le nom de l'unité, le code doit ressembler à ceci :|n|nfunction(unit, unitOwner)|nreturn UnitName(unitOwner)|nend"
L["You will need to create an aura filter before you can set which unit to enable aura filtering on."] = "Vous aurez besoin de créer un filtre d'aura avant de pouvoir définir sur quelle unité activer le filtrage d'aura."
L["You will need to do a /console reloadui before a hidden frame becomes visible again.|nPlayer and other unit frames are automatically hidden depending on if you enable the unit in Shadowed Unit Frames."] = "Vous aurez besoin d'effectuer un /console reloadui avant qu'un cadre caché ne puisse être visible à nouveau.|nLe joueur ainsi que d'autres cadres d'unité sont automatiquement cachés si ces derniers ont été activés dans Shadowed Unit Frames."
L["Zone Configuration"] = "Configuration de zone" -- Needs review
L["Zone configuration units"] = "Unités de Config. de zone" -- Needs review

local ShadowUF = select(2, ...)
ShadowUF.L = setmetatable(L, {__index = ShadowUF.L})
