local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Hermes-LegacyUI", "deDE", false)
if not L then return end

L["Add"] = "hinzufügen" -- Needs review
L["Alive"] = "Am Leben"
-- L["Anchor Point"] = "Anchor Point"
L["Available Bar Color"] = "'verfügbar' Leistenfarbe"
L["Available Font Color"] = "'verfügbar' Schriftfarbe"
L["Background"] = "Hintergrund"
L["Bar Direction"] = "Leistenausrichtung"
L["Bars"] = "Leisten"
L["Bars to Show"] = "Leistenanzahl"
-- L["Behavior"] = "Behavior"
L["Bottom Left"] = "Unten Links" -- Needs review
L["Bottom Right"] = "Unten Rechts" -- Needs review
L["Bottom to Top"] = "von unten nach oben"
-- L["Cell Padding"] = "Cell Padding"
L["Class Colored Borders"] = "Umrandungen in Klassenfarbe"
L["Color"] = "Farbe"
-- L["Configure"] = "Configure"
L["Conn"] = true
L["Container"] = true -- Needs review
-- L["Cooldown Style"] = "Cooldown Style"
L["Default"] = "Standart"
L["Delete"] = "Löschen" -- Needs review
-- L["Drop Shadow"] = "Drop Shadow"
-- L["Enabled"] = "Enabled"
L["Font"] = "Schrift"
L["Font Size"] = "Schriftgröße"
-- L["Foreground"] = "Foreground"
L["Gap Between Bars"] = "Abstand zwischen den Leisten"
L["Height"] = "Höhe"
-- L["Hide"] = "Hide"
L["Hide Abilities without Senders"] = "Verstecke Fähigkeiten ohne Sender"
L["Hide Self"] = "Selbst Verstecken" -- Needs review
-- L["Icon"] = "Icon"
-- L["Inner Padding"] = "Inner Padding"
-- L["Layout"] = "Layout"
-- L["Left"] = "Left"
L["Left to Right"] = "von links nach rechts"
L["Lock Window"] = "Sperre Fenster" -- Needs review
-- L["Merge Spells"] = "Merge Spells"
-- L["Name on Right"] = "Name on Right"
-- L["None"] = "None"
L["None found"] = "nicht gefunden" -- Needs review
L["On Cooldown Bar Color"] = "'auf Cooldown' Leistenfarbe"
L["On Cooldown Font Color"] = "'auf Cooldown' Schriftfarbe"
L["Only show bar when spell is on cooldown"] = "Zeige leiste nur wenn der Zauber auf Cooldown ist"
L["Outline"] = "Umriss"
L["Padding"] = true -- Needs review
L["Player/Duration Width Ratio (%)"] = "Spieler/Dauer breiten Verhältnis (%)" -- Needs review
L["Range"] = "Reichweite"
L["Ready"] = "Bereit"
-- L["Requires spell metadata key duration. If such a key exists, an additional timer bar will be displayed based on it's value. For example. you could supply a duration key with a value of 6 for Divine Guardian's 6 second duration."] = "Requires spell metadata key duration. If such a key exists, an additional timer bar will be displayed based on it's value. For example. you could supply a duration key with a value of 6 for Divine Guardian's 6 second duration."
L["Reset Position"] = "Position zurücksetzen"
-- L["Reverse Direction"] = "Reverse Direction"
-- L["Right"] = "Right"
L["Right to Left"] = "von rechts nach links"
L["Scale"] = "Skalierung" -- Needs review
-- L["Show"] = "Show"
L["Show Icon"] = "Zeige Icon"
L["Show Nameplate"] = "Zeige Namensplakete"
L["Size"] = "Größe"
-- L["Spell Metadata"] = "Spell Metadata"
L["Spells"] = "Zauber"
-- L["Starts Empty"] = "Starts Empty"
-- L["Starts Full"] = "Starts Full"
-- L["Swap Name and Duration"] = "Swap Name and Duration"
L["Texture"] = "Textur"
L["Time"] = "Zeit"
-- L["Tooltip"] = "Tooltip"
L["Top Left"] = "Oben Links"
L["Top Right"] = "Oben Rechts"
L["Top to Bottom"] = "von oben nach unten"
L["Unavailable Bar Color"] = "'nicht verfügbar' Leistenfarbe"
L["Unavailable Font Color"] = "'Nicht verfügbar' Schriftfarbe"
L["Use Class Color"] = "In Klassenfarbe"
L["Width"] = "Breite"
L["Window"] = "Fenster" -- Needs review
L["dead"] = "tot"
L["offline"] = true
L["range"] = "Reichweite"

L["Apply Theme"] = "Theme anwenden"
L["Bars Style"] = "Leisten Style"
L["Buttons"] = true
L["Buttons Style"] = true
L["Cell Anchor"] = "Zellenausrichtung"
L["Cells"] = "Zellen"
L["Container will be deleted and its abilities placed into the Default container. Continue?"] = "Container wird gelöscht und die Fähigkeiten werden im den Standart Container verschoben. Fortfahren?"
L["Display Style"] = "Anzeigemodus"
L["From"] = "Von"
L["Hide Abilities without available Senders"] = "Verstecke Fähigkeiten ohne erreichbare Sender"
L["Lock Containers"] = "Sperre Container"
L["Nameplate"] = "Namensplakete"
L["Properties will be changed to match the selected theme. Continue?"] = "Container Eigenschaften werden geändert um zum ausgewählten Theme zu passen. Fortfahren?"
L["Size and Position"] = "Größe und Position"
L["Theme"] = true

