-- English localization file for enUS
local AceLocale = LibStub:GetLibrary("AceLocale-3.0")

local debug = false
--[===[@debug@
debug = true
--@end-debug@]===]

local L = AceLocale:NewLocale("Hermes-LegacyUI", "enUS", true, debug)
if not L then return end

L["Add"] = true
L["Alive"] = true
L["Anchor Point"] = true
L["Available Bar Color"] = true
L["Available Font Color"] = true
L["Background"] = true
L["Bar Direction"] = true
L["Bars"] = true
L["Bars to Show"] = true
L["Behavior"] = true
L["Bottom Left"] = true
L["Bottom Right"] = true
L["Bottom to Top"] = true
L["Cell Padding"] = true
L["Class Colored Borders"] = true
L["Color"] = true
L["Configure"] = true
L["Conn"] = true
L["Container"] = true
L["Cooldown Style"] = true
L["Default"] = true
L["Delete"] = true
L["Drop Shadow"] = true
L["Enabled"] = true
L["Font"] = true
L["Font Size"] = true
L["Foreground"] = true
L["Gap Between Bars"] = true
L["Height"] = true
L["Hide"] = true
L["Hide Abilities without Senders"] = true
L["Hide Self"] = true
L["Icon"] = true
L["Inner Padding"] = true
L["Layout"] = true
L["Left"] = true
L["Left to Right"] = true
L["Lock Window"] = true
L["Merge Spells"] = true
L["Name on Right"] = true
L["None"] = true
L["None found"] = true
L["On Cooldown Bar Color"] = true
L["On Cooldown Font Color"] = true
L["Only show bar when spell is on cooldown"] = true
L["Outline"] = true
L["Padding"] = true
L["Player/Duration Width Ratio (%)"] = true
L["Range"] = true
L["Ready"] = true
L["Requires spell metadata key duration. If such a key exists, an additional timer bar will be displayed based on it's value. For example. you could supply a duration key with a value of 6 for Divine Guardian's 6 second duration."] = true
L["Reset Position"] = true
L["Reverse Direction"] = true
L["Right"] = true
L["Right to Left"] = true
L["Scale"] = true
L["Show"] = true
L["Show Icon"] = true
L["Show Nameplate"] = true
L["Size"] = true
L["Spell Metadata"] = true
L["Spells"] = true
L["Starts Empty"] = true
L["Starts Full"] = true
L["Swap Name and Duration"] = true
L["Texture"] = true
L["Time"] = true
L["Tooltip"] = true
L["Top Left"] = true
L["Top Right"] = true
L["Top to Bottom"] = true
L["Unavailable Bar Color"] = true
L["Unavailable Font Color"] = true
L["Use Class Color"] = true
L["Width"] = true
L["Window"] = true
L["dead"] = true
L["offline"] = true
L["range"] = true

L["Apply Theme"] = true
L["Bars Style"] = true
L["Buttons"] = true
L["Buttons Style"] = true
L["Cell Anchor"] = true
L["Cells"] = true
L["Container will be deleted and its abilities placed into the Default container. Continue?"] = true
L["Display Style"] = true
L["From"] = true
L["Hide Abilities without available Senders"] = true
L["Lock Containers"] = true
L["Nameplate"] = true
L["Properties will be changed to match the selected theme. Continue?"] = true
L["Size and Position"] = true
L["Theme"] = true
