local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Hermes-LegacyUI", "ruRU", false)
if not L then return end

L["Add"] = "Добавить" -- Needs review
L["Alive"] = "Активно" -- Needs review
L["Anchor Point"] = "Якорь" -- Needs review
L["Available Bar Color"] = "Доступный цвет панели" -- Needs review
L["Available Font Color"] = "Доступный цвет фона" -- Needs review
L["Background"] = "Фон" -- Needs review
L["Bar Direction"] = "Направление роста панели" -- Needs review
L["Bars"] = "Панели" -- Needs review
L["Bars to Show"] = "Панели для отображения" -- Needs review
L["Behavior"] = "Поведение" -- Needs review
L["Bottom Left"] = "Слева Внизу" -- Needs review
L["Bottom Right"] = "Справа Внизу" -- Needs review
L["Bottom to Top"] = "Снизу вверх" -- Needs review
L["Cell Padding"] = "Наполнение ячейки" -- Needs review
L["Class Colored Borders"] = "Рамки по цветам классов" -- Needs review
L["Color"] = "Цвет" -- Needs review
L["Configure"] = "Настроить" -- Needs review
L["Conn"] = "Связь" -- Needs review
L["Container"] = "Контейнер" -- Needs review
L["Cooldown Style"] = "Стиль кулдауна" -- Needs review
L["Default"] = "Стандартный" -- Needs review
L["Delete"] = "Удалить" -- Needs review
L["Drop Shadow"] = "Отбрасывать тень" -- Needs review
L["Enabled"] = "Включено" -- Needs review
L["Font"] = "Шрифт" -- Needs review
L["Font Size"] = "Размер шрифта" -- Needs review
L["Foreground"] = "Передний план" -- Needs review
L["Gap Between Bars"] = "Расстояние между панелями" -- Needs review
L["Height"] = "Высота" -- Needs review
L["Hide"] = "Спрятать" -- Needs review
L["Hide Abilities without Senders"] = "Скрыть Заклинания без Отправителей" -- Needs review
L["Hide Self"] = "Прятать себя" -- Needs review
L["Icon"] = "Иконка" -- Needs review
L["Inner Padding"] = "Внутреннее наполнение" -- Needs review
L["Layout"] = "Расположение" -- Needs review
L["Left"] = "Лево" -- Needs review
L["Left to Right"] = "Слева направо" -- Needs review
L["Lock Window"] = "Заблокировать окно" -- Needs review
L["Merge Spells"] = "Слияние заклинаний" -- Needs review
L["Name on Right"] = "Имя справа" -- Needs review
L["None"] = "Нет" -- Needs review
L["None found"] = "Не найдено" -- Needs review
L["On Cooldown Bar Color"] = "Цвет панели отсчета" -- Needs review
L["On Cooldown Font Color"] = "Цвет шрифта отсчета" -- Needs review
L["Only show bar when spell is on cooldown"] = "Показывать только полосу, когда заклинание на кулдауне" -- Needs review
L["Outline"] = "Контур" -- Needs review
L["Padding"] = "Заполнение" -- Needs review
L["Player/Duration Width Ratio (%)"] = "Соотношение ширины Игрок/Длительность (%)" -- Needs review
L["Range"] = "Расстояние" -- Needs review
L["Ready"] = "Готово" -- Needs review
L["Requires spell metadata key duration. If such a key exists, an additional timer bar will be displayed based on it's value. For example. you could supply a duration key with a value of 6 for Divine Guardian's 6 second duration."] = "Требуется ключевая длительность метаданных заклинания. Если такое значение существует, дополнительный панель-таймер будет показан основываясь на значении. Например: можно установить ключевую длительность значением 6 для заклинания Божественный защитник, длительность которого 6 секунд." -- Needs review
L["Reset Position"] = "Сбросить Позицию" -- Needs review
L["Reverse Direction"] = "Обратное направление" -- Needs review
L["Right"] = "Право" -- Needs review
L["Right to Left"] = "Справа налево" -- Needs review
L["Scale"] = "Масштаб" -- Needs review
L["Show"] = "Показать" -- Needs review
L["Show Icon"] = "Показать иконку" -- Needs review
L["Show Nameplate"] = "Показать панель имени" -- Needs review
L["Size"] = "Размер" -- Needs review
L["Spell Metadata"] = "Метаданные заклинания" -- Needs review
L["Spells"] = "Заклинания" -- Needs review
L["Starts Empty"] = "Стартовать пустым" -- Needs review
L["Starts Full"] = "Стартовать заполненным" -- Needs review
L["Swap Name and Duration"] = "Поменять Имя и Длительность" -- Needs review
L["Texture"] = "Текстуры" -- Needs review
L["Time"] = "Время" -- Needs review
L["Tooltip"] = "Подсказка" -- Needs review
L["Top Left"] = "Слева Вверху" -- Needs review
L["Top Right"] = "Справа Вверху" -- Needs review
L["Top to Bottom"] = "Сверху вниз" -- Needs review
L["Unavailable Bar Color"] = "Недоступный цвет панели" -- Needs review
L["Unavailable Font Color"] = "Недоступный цвет шрифта" -- Needs review
L["Use Class Color"] = "Использовать цвет класса" -- Needs review
L["Width"] = "Ширина" -- Needs review
L["Window"] = "Окно" -- Needs review
L["dead"] = "мёртв" -- Needs review
L["offline"] = "оффлайн" -- Needs review
L["range"] = "расстояние" -- Needs review

L["Apply Theme"] = "Применить тему" -- Needs review
L["Bars Style"] = "Стиль панелей" -- Needs review
L["Buttons"] = "Кнопки" -- Needs review
L["Buttons Style"] = "Стиль кнопок" -- Needs review
L["Cell Anchor"] = "Якорь ячейки" -- Needs review
L["Cells"] = "Ячейки" -- Needs review
L["Container will be deleted and its abilities placed into the Default container. Continue?"] = "Контейнер будет удален а его кнопки будут помещены на стандартный контейнер. Продолжить?" -- Needs review
L["Display Style"] = "Стиль отображения" -- Needs review
L["From"] = "От" -- Needs review
L["Hide Abilities without available Senders"] = "Скрыть Заклинания без возможных Отправителей" -- Needs review
L["Lock Containers"] = "Заблокировать контейнеры" -- Needs review
L["Nameplate"] = "Панель имени" -- Needs review
L["Properties will be changed to match the selected theme. Continue?"] = "Свойства будут изменены для соответствия выбранной теме. Продолжить?" -- Needs review
L["Size and Position"] = "Размер и Позиция" -- Needs review
L["Theme"] = "Тема" -- Needs review

