local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Hermes-LegacyUI", "zhTW", false)
if not L then return end

L["Add"] = "加入" -- Needs review
L["Alive"] = "存活" -- Needs review
-- L["Anchor Point"] = "Anchor Point"
-- L["Available Bar Color"] = "Available Bar Color"
-- L["Available Font Color"] = "Available Font Color"
-- L["Background"] = "Background"
-- L["Bar Direction"] = "Bar Direction"
-- L["Bars"] = "Bars"
-- L["Bars to Show"] = "Bars to Show"
-- L["Behavior"] = "Behavior"
L["Bottom Left"] = "左下" -- Needs review
L["Bottom Right"] = "右下" -- Needs review
-- L["Bottom to Top"] = "Bottom to Top"
-- L["Cell Padding"] = "Cell Padding"
L["Class Colored Borders"] = "職業顏色邊框" -- Needs review
L["Color"] = "顏色" -- Needs review
-- L["Configure"] = "Configure"
-- L["Conn"] = "Conn"
-- L["Container"] = "Container"
-- L["Cooldown Style"] = "Cooldown Style"
L["Default"] = "預設" -- Needs review
L["Delete"] = "刪除" -- Needs review
-- L["Drop Shadow"] = "Drop Shadow"
-- L["Enabled"] = "Enabled"
L["Font"] = "字型" -- Needs review
-- L["Font Size"] = "Font Size"
-- L["Foreground"] = "Foreground"
-- L["Gap Between Bars"] = "Gap Between Bars"
L["Height"] = "高度" -- Needs review
-- L["Hide"] = "Hide"
-- L["Hide Abilities without Senders"] = "Hide Abilities without Senders"
-- L["Hide Self"] = "Hide Self"
-- L["Icon"] = "Icon"
-- L["Inner Padding"] = "Inner Padding"
-- L["Layout"] = "Layout"
-- L["Left"] = "Left"
L["Left to Right"] = "左到右" -- Needs review
-- L["Lock Window"] = "Lock Window"
-- L["Merge Spells"] = "Merge Spells"
-- L["Name on Right"] = "Name on Right"
-- L["None"] = "None"
L["None found"] = "沒有找到" -- Needs review
-- L["On Cooldown Bar Color"] = "On Cooldown Bar Color"
-- L["On Cooldown Font Color"] = "On Cooldown Font Color"
-- L["Only show bar when spell is on cooldown"] = "Only show bar when spell is on cooldown"
-- L["Outline"] = "Outline"
L["Padding"] = "填充" -- Needs review
-- L["Player/Duration Width Ratio (%)"] = "Player/Duration Width Ratio (%)"
-- L["Range"] = "Range"
-- L["Ready"] = "Ready"
-- L["Requires spell metadata key duration. If such a key exists, an additional timer bar will be displayed based on it's value. For example. you could supply a duration key with a value of 6 for Divine Guardian's 6 second duration."] = "Requires spell metadata key duration. If such a key exists, an additional timer bar will be displayed based on it's value. For example. you could supply a duration key with a value of 6 for Divine Guardian's 6 second duration."
L["Reset Position"] = "重設位置" -- Needs review
-- L["Reverse Direction"] = "Reverse Direction"
-- L["Right"] = "Right"
-- L["Right to Left"] = "Right to Left"
L["Scale"] = "縮放" -- Needs review
-- L["Show"] = "Show"
-- L["Show Icon"] = "Show Icon"
-- L["Show Nameplate"] = "Show Nameplate"
-- L["Size"] = "Size"
-- L["Spell Metadata"] = "Spell Metadata"
L["Spells"] = "法術" -- Needs review
-- L["Starts Empty"] = "Starts Empty"
-- L["Starts Full"] = "Starts Full"
-- L["Swap Name and Duration"] = "Swap Name and Duration"
-- L["Texture"] = "Texture"
L["Time"] = "時間" -- Needs review
-- L["Tooltip"] = "Tooltip"
L["Top Left"] = "左上" -- Needs review
L["Top Right"] = "右上" -- Needs review
-- L["Top to Bottom"] = "Top to Bottom"
-- L["Unavailable Bar Color"] = "Unavailable Bar Color"
-- L["Unavailable Font Color"] = "Unavailable Font Color"
-- L["Use Class Color"] = "Use Class Color"
L["Width"] = "寬度" -- Needs review
-- L["Window"] = "Window"
-- L["dead"] = "dead"
-- L["offline"] = "offline"
-- L["range"] = "range"

-- L["Apply Theme"] = "Apply Theme"
-- L["Bars Style"] = "Bars Style"
L["Buttons"] = "按鈕" -- Needs review
L["Buttons Style"] = "按鈕風格" -- Needs review
-- L["Cell Anchor"] = "Cell Anchor"
-- L["Cells"] = "Cells"
-- L["Container will be deleted and its abilities placed into the Default container. Continue?"] = "Container will be deleted and its abilities placed into the Default container. Continue?"
L["Display Style"] = "顯示風格" -- Needs review
L["From"] = "從" -- Needs review
-- L["Hide Abilities without available Senders"] = "Hide Abilities without available Senders"
-- L["Lock Containers"] = "Lock Containers"
L["Nameplate"] = "姓名板" -- Needs review
-- L["Properties will be changed to match the selected theme. Continue?"] = "Properties will be changed to match the selected theme. Continue?"
L["Size and Position"] = "尺寸和位置" -- Needs review
-- L["Theme"] = "Theme"

