if (GetLocale() ~= "deDE") then
	return;
end
-- New Options
-- @EXACT = false
VUHDO_I18N_SCANNERS = "Scanner";
VUHDO_I18N_RESURRECT_SHORT = "Wiederbel.";
VUHDO_I18N_GENERAL = "Allgemein";
VUHDO_I18N_CONFIG = "Konfig";
VUHDO_I18N_REBUFF = "Re-Buff";
VUHDO_I18N_FORMAT = "Format";
VUHDO_I18N_BUFF_NAMES = "Buff Namen";
VUHDO_I18N_STATES = "Zustände";
VUHDO_I18N_CD_FLASHING = "CD-Blinken";
VUHDO_I18N_TIMERS = "Timers";
VUHDO_I18N_WHATEVER_FIRST = "...oder...(was zuerst kommt)";
VUHDO_I18N_MODES = "Modus";
VUHDO_I18N_EMERGENCY_MODE = "Notfallmodus";
VUHDO_I18N_NORMAL_MODE = "Normalmodus";
VUHDO_I18N_RANGE = "Reichweite";
VUHDO_I18N_ADD_NEW_PANEL = "Neues Fenster";
VUHDO_I18N_HOLD_TO_TEST = "Gedrückt halten";
VUHDO_I18N_OWN_HOTS = "Eigene HoTs";
VUHDO_I18N_LOSE = "frei";
VUHDO_I18N_ORDERING = "Anordnung";
VUHDO_I18N_HIDE_EMPTY = "Keine leeren";
VUHDO_I18N_ANCHOR = "Ankerpunkt";
VUHDO_I18N_UNIT_ID = "Unit ID";
VUHDO_I18N_HEADER_TEXT = "Spaltentext";
VUHDO_I18N_TOOLTIPS = "Tooltips";
VUHDO_I18N_SIZING = "Größeneinst.";
VUHDO_I18N_BUTTON_SIZE = "Buttongröße";
VUHDO_I18N_PERCENT = "Prozent";
VUHDO_I18N_MISSING = "Fehlend";
VUHDO_I18N_REMAINING = "Verbleibend";
VUHDO_I18N_HITPOINTS = "Hitpoints";
VUHDO_I18N_BAR_TEXT = "Balkentext";
VUHDO_I18N_MAX_BUFFS_PER_ROW = "Max.Buffs/Spalte";
VUHDO_I18N_REFRESH_RATE = "Aktualisierungsrate";
VUHDO_I18N_INDICATE_REBUFF_BELOW = "Neu buffen unter";
VUHDO_I18N_SIZE = "Größe";
VUHDO_I18N_TEXTURE_NUM = "Textur #";
VUHDO_I18N_TEXT_SIZE = "Textgröße";
VUHDO_I18N_X_SPACING = "Abstand X";
VUHDO_I18N_Y_SPACING = "Abstand Y";
VUHDO_I18N_X_GAP = "Rand X";
VUHDO_I18N_Y_GAP = "Rand Y";
-- General Labels
-- @EXACT = false
VUHDO_I18N_CANCEL = "Abbruch";
VUHDO_I18N_SHOW = "Anzeigen";
VUHDO_I18N_BARS = "Balken"
VUHDO_I18N_COLOR = "Farbe";
VUHDO_I18N_COLORS = "Farben";
VUHDO_I18N_GENERAL_SHORT = "Allgem.";
VUHDO_I18N_CUSTOM = "Eigene";
VUHDO_I18N_MOUSE = "Maus";
VUHDO_I18N_STANDARD = "Standard";
VUHDO_I18N_POSITION = "Position";
VUHDO_I18N_SCALE = "Größe";
VUHDO_I18N_ENABLE = "Aktiviert";
VUHDO_I18N_BACKGROUND = "Hintergrund";
VUHDO_I18N_GROUPED = "ordnen";
VUHDO_I18N_SORT_BY = "Sortierung...";
VUHDO_I18N_NAME = "Name";
VUHDO_I18N_MAX_HP = "Max HP";
VUHDO_I18N_MAX_COLUMNS = "max. Spalten";
VUHDO_I18N_MAX_ROWS = "max. Zeilen";
VUHDO_I18N_CLEAR_PANELS_CONFIRM = "Modelle des Panels leeren!\nYA'RLY?";
VUHDO_I18N_BUFF_NAME = "Buff-Name";
VUHDO_I18N_BUFF_ON_PLAYER = "auf Spieler mit Namen:";
VUHDO_I18N_ALWAYS = "Immer";
VUHDO_I18N_BUFF_PANEL_BG = "Fenster";
-- VuhDoOptionsGeneral.lua
-- @EXACT = false
VUHDO_I18N_CLEANSE = "Reinigen";
VUHDO_I18N_RESURRECT = "Wiederbeleben";
VUHDO_I18N_SMART_CAST_OO_COMBAT = "Smart Cast";
VUHDO_I18N_IGNORE_IRRELEVANT = "Ignoriere bedeutungslose ...";
VUHDO_I18N_BY_CLASS = "Klasse";
VUHDO_I18N_MOVEMENT_IMPAIRING = "Bewegung";
VUHDO_I18N_BY_DURATION = "Dauer";
VUHDO_I18N_BY_NON_HARMFUL = "unschädlich";
VUHDO_I18N_REMOVABLE_ONLY = "nur\nentfernbare";
VUHOD_I18N_BY_SPELL = "Spruch";
VUHDO_I18N_SHOW_INC = "Eingehende Heilung";
VUHDO_I18N_SHOW_OWN_HEAL = "Eigene";
VUHDO_I18N_SHOW_OVERHEAL = "Überheilung";
VUHDO_I18N_OPERATION_MODE = "Betriebsmodus";
VUHDO_I18N_MAX_EMERGENCIES = "max. # Notfälle";
VUHDO_I18N_RELVEVANCE = "Irrelevant über";
VUHDO_I18N_NEUTRAL_HEALBOT = "Neutral";
VUHDO_I18N_EMERGENCY_PERCENT = "Notfall - HP %";
VUHDO_I18N_EMERGENCY_MOST_MISSING = "Meiste HP fehlend";
VUHDO_I18N_EMERGENCY_LEAST_LEFT = "Wenigste HP übrig";
-- VuhDoFormButtonColor.lua
-- @EXACT = false
-- Labels
VUHDO_I18N_TEXT = "Text";
VUHDO_I18N_ANOMALIES = "Anomalien";
VUHDO_I18N_OPACITY = "Opazität";
-- VuhDoFormButtonSize.lua
-- @EXACT = false
VUHDO_I18N_PANEL = "Panel";
VUHDO_I18N_SPACING = "Abstand";
VUHDO_I18N_BAR_HEIGHT = "Balkenhöhe";
VUHDO_I18N_TARGETS = "Ziele";
VUHDO_I18N_BAR_TEXTURE = "Balken-Textur";
VUHDO_I18N_BAR_WIDTH = "Balkenbreite";
VUHDO_I18N_WIDTH = "Breite";
VUHDO_I18N_HEADERS = "Titel";
VUHDO_I18N_CLASS_COL = "Klassenf.";
--
-- VuhDoOptionsSpell.lua
-- @EXACT = false
VUHDO_I18N_KEY_MODIFIES = "Modifikationstaste";
VUHDO_I18N_KEY_NONE = "keine";
VUHDO_I18N_ALT = "Alt";
VUHDO_I18N_CTRL = "Strg";
VUHDO_I18N_SHIFT = "Umschalt";
VUHDO_I18N_LEFT_BUTTON = "Linke Taste";
VUHDO_I18N_RIGHT_BUTTON = "Rechte Taste";
VUHDO_I18N_MIDDLE_BUTTON = "Mittlere Taste";
VUHDO_I18N_BUTTON_4 = "Taste 4";
VUHDO_I18N_BUTTON_5 = "Taste 5";
VUHDO_I18N_MOUSE_KEY = "Maustaste";
VUHDO_I18N_IN_MACROS_USE = "(in Makros \"vuhdo\" statt Spielernamen)";
VUHDO_I18N_SPELL_STATIC = "oder target/focus/assist/menu/tell/dropdown";
VUHDO_I18N_NAME_TIP = "Name eines Zaubers, Makros or Items,";
VUHDO_I18N_PLUS_SHIFT = "+Umschalt";
VUHDO_I18N_PLUS_CTRL_SHIFT = "+Strg+Umsch";
VUHDO_I18N_PLUS_CTRL = "+Strg";
-- VuhDoTooltipConfig.lua
-- @EXACT = false
VUHDO_I18N_AROUND_PANEL = "Um Panel";
VUHDO_I18N_SHOW_IN_FIGHT = "im Kampf";
-- New Options - Tooltips
-- @EXACT = false
VUHDO_I18N_TT.K001 = "Konfigurieren Sie, welche Buffs durch VuhDo verwaltet werden sollen.";
VUHDO_I18N_TT.K002 = "Bestimmen Sie das generelle Aussehen der Buffanzeige.";
VUHDO_I18N_TT.K003 = "Wählen Sie die Farben Ihrer Buffanzeige.";
VUHDO_I18N_TT.K004 = "Nehmen Sie die Buff-Timer-Einstellungen vor und bestimmen Sie, wie gebufft werden soll.";
VUHDO_I18N_TT.K005 = "Wählen Sie die Gesamtgrösse ihrer Buffanzeige.";
VUHDO_I18N_TT.K007 = "Stellen Sie die maximale Zahl von angezeigten Buffs pro spalte ein.";
VUHDO_I18N_TT.K008 = "Wählen Sie die Aktualisierungsrate der Buffanzeige.";
VUHDO_I18N_TT.K009 = "Markieren Sie diese Option, um die Buff-Namen im Titel der Buffanzeige einzublenden.";
VUHDO_I18N_TT.K011 = "Wenn Sie dieses Feld markieren, aktivieren Sie die VuhDo Buff-Anzeige.";
VUHDO_I18N_TT.K012 = "Wählen Sie eine Farbe für ausreichende Restdauer eines Buffs.";
VUHDO_I18N_TT.K013 = "Wählen Sie eine Farbe für bald auslaufende Buffs.";
VUHDO_I18N_TT.K014 = "Wählen Sie eine Farbe für (teilweise) fehlende Buffs.";
VUHDO_I18N_TT.K015 = "Wählen Sie eine Farbe für den Fall, dass alle Buff-Ziele ausser Reichweite sind.";
VUHDO_I18N_TT.K016 = "Wählen Sie eine Farbe, um anzuzeigen, dass der Buff aktuell Cooldown hat.";
VUHDO_I18N_TT.K017 = "Wählen Sie eine Farbe, die anzeigt, dass die Buff-Gruppe derzeit leer ist.";
VUHDO_I18N_TT.K018 = "Wählen Sie eine Farbe für den Fensterhintergrund.";
VUHDO_I18N_TT.K019 = "Wählen Sie eine Farbe für den Rahmen der Buff-Kästchen.";
VUHDO_I18N_TT.K020 = "Wählen Sie eine Farbe für den Rahmen des Buff-Fensters.";
VUHDO_I18N_TT.K021 = "Wenn Sie dieses Feld aktivieren, werden Ihnen auslaufende Cooldowns durch mehrmaliges Blinken angezeigt.";
VUHDO_I18N_TT.K022 = "Wählen Sie aus, bei welcher Buff-Restlaufzeit in Prozent, die Buff-Anzeige von \"grün\" auf \"gelb\" springen soll";
VUHDO_I18N_TT.K023 = "Wählen Sie aus, bei welcher Buff-Restlaufzeit in Minuten, die Buff-Anzeige von \"grün\" auf \"gelb\" springen soll";
VUHDO_I18N_TT.K028 = "Wählen Sie alle Farben, die den Zustand eines Spielers widergeben.";
VUHDO_I18N_TT.K029 = "Wählen Sie Farben zum aktivierten Anzeigemodus.";
VUHDO_I18N_TT.K031 = "Wählen Sie eine Farbe, die einen Notfall symbolisiert. (Hinweis: Wirkt nur bei aktiviertem Betriebsmodus \"Notfall\")";
VUHDO_I18N_TT.K032 = "Wählen Sie eine Farbe, die einen NICHT-Notfall symbolisiert. (Hinweis: Wirkt nur bei aktiviertem Betriebsmodus \"Notfall\").";
VUHDO_I18N_TT.K033 = "Wählen Sie eine Farbe für Spieler, die als irrelevant für Heilung gelten, weil sie noch zu viele Lebenspunkte haben. (Beachte: \"Irrelevant\"-Schieberegler in den generellen Fenster-Einstellungen)";
VUHDO_I18N_TT.K034 = "Wählen Sie eine Farbe für eingehende Heilung. (Hinweis: Die Anzeige eingehender Heilung muss aktiviert sein.)";
VUHDO_I18N_TT.K035 = "Wählen Sie eine Farbe für Spieler, die sich nicht in Reichweite befinden. (Hinweis: Die Reichweitenprüfung muss aktiviert sein.)";
VUHDO_I18N_TT.K036 = "Wählen Sie eine Farbe, um anzuzeigen, dass die Spielfigur verschieden ist.";
VUHDO_I18N_TT.K037 = "Wählen Sie eine Farbe für Spieler, die aktuell offline sind.";
VUHDO_I18N_TT.K038 = "Wählen Sie eine Farbe für übernommene, d.h. fremdgesteuerte Spieler.";
VUHDO_I18N_TT.K040 = "Wählen Sie eine Farbe für vergiftete Spieler.";
VUHDO_I18N_TT.K041 = "Wählen Sie eine Farbe für Spieler, die von einem Krankheit-Debuff betroffen sind.";
VUHDO_I18N_TT.K042 = "Wählen Sie eine Farbe für verfluchte Spieler.";
VUHDO_I18N_TT.K043 = "Wählen Sie eine Farbe für Spieler, die an einem Magie-Debuff leiden.";
VUHDO_I18N_TT.K044 = "Nehmen Sie grundsätzliche VuhDo-Einstellungen vor.";
VUHDO_I18N_TT.K045 = "Wählen Sie aus, welche besonderen Spielsituationen von VuhDo geprüft werden sollen.";
VUHDO_I18N_TT.K048 = "Automatisches Reinigen ausserhalb des Kampfes (Gift, Fluch etc.).";
VUHDO_I18N_TT.K049 = "Automatische Wiederbelebung toter Spielfiguren ausserhalb des Kampfes.";
VUHDO_I18N_TT.K053 = "Wählen Sie den generellen Anzeigemodus aus. Es sollte \"neutral\" ausgewählt sein, solange sie keine Quer-Heilung in grossen Schlatzügen oder im PvP betreiben wollen.";
VUHDO_I18N_TT.K054 = "Wählen Sie die maximal gleichzeitig anzuzeigende Anzahl von Notfällen. Irrelevant, wenn der Modus auf \"neutral\" eingestellt ist.";
VUHDO_I18N_TT.K055 = "Stellen Sie den maximalen Prozentsatz an Lebensenergie ein, bis zu dem ein Spieler als gesund, d.h. irrelevant für Heilung erachtet wird. Wenn Sie keine Präferenz haben, sollten Sie 100% einstellen.";
VUHDO_I18N_TT.K056 = "Wählen Sie diese Option, um Debuffs zu ignorieren, die per se nicht schädlich sind.";
VUHDO_I18N_TT.K057 = "Wählen Sie diese Option, wenn Sie Debuffs ignorieren wollen, die lediglich das Bewegungstempo einschränken.";
VUHDO_I18N_TT.K058 = "Wählen Sie diese Option, um Debuffs mit sehr niedriger Gesamtdauer zu ignorieren.";
VUHDO_I18N_TT.K059 = "Wählen Sie diese Option, um Debuffs zu ignorieren, die für die jeweilige Klasse irrelevant sind (z.B. Manabrand auf Krieger).";
VUHDO_I18N_TT.K060 = "Wenn Sie diese Option wählen, werden Ihnen farblich nur die Buffs angezeigt, die sie auch selbst in der Lage sind zu entfernen. Anderenfalls werden alle Debuffs angezeigt.";
VUHDO_I18N_TT.K062 = "Wählen Sie diese Option, um die Überheilung durch Aufhellen des Balkens anzuzeigen.";
VUHDO_I18N_TT.K063 = "Wählen Sie diese Option, wenn Sie eingehende Heilung auch anzeigen wollen, wenn diese von Ihnen stammt. Manche Spieler finden dies irritierend, andere mögen es.";
VUHDO_I18N_TT.K065 = "Wählen Sie die Aktualisierungsrate für die Reichweitenprüfung. Achtung: Sehr schnelle Aktualisierungsraten können die Systemleistung beeinträchtigen.";
VUHDO_I18N_TT.K066 = "Wählen Sie diese Option, um die Reichweitenprüfung pauschal durchzuführen. Dies ist sinnvoll, wenn Ihre Klasse nicht über Heilsprüche verfügt.";
VUHDO_I18N_TT.K067 = "Tragen Sie den Namen desjenigen Ihrer Heilsprüche ein, der für die Reichweitenprüfung verwendet werden soll.";
VUHDO_I18N_TT.K068 = "Wählen Sie diese Option, um die Reichweitenprüfung gemäß der Reichweite des rechts im Eingabeld eingetragenen Spruchs durchzuführen.";
VUHDO_I18N_TT.K070 = "Wählen Sie einen Prozentsatz des Balkenhöhe, die das HoT-Symbol gross sein soll";
VUHDO_I18N_TT.K071 = "Auswählen, um das HoT-Symbol RECHTS INNEN im Heilbalken anzuzeigen";
VUHDO_I18N_TT.K072 = "Auswählen, um das HoT-Symbol LINKS INNEN im Heilbalken anzuzeigen";
VUHDO_I18N_TT.K073 = "Auswählen, um das HoT-Symbol LINKS AUSSEN neben dem Heilbalken anzuzeigen";
VUHDO_I18N_TT.K074 = "Auswählen, um das HoT-Symbol RECHTS AUSSEN neben dem Heilbalken anzuzeigen";
VUHDO_I18N_TT.K076 = "Wählen Sie Ihre bevorzugte Balken-Textur.";
VUHDO_I18N_TT.K077 = "Bewegen Sie den Knopf, um die Balkentextur zu wechseln.";
VUHDO_I18N_TT.K078 = "Wählen Sie eine Farbe für den Heilfenster-Hintergrund.";
VUHDO_I18N_TT.K079 = "Wählen Sie eine Farbe für den Rahmen des Heilfensters.";
VUHDO_I18N_TT.K081 = "Bewegen Sie den Knopf, um die Grösse des Mana-Balkens zu verändern.";
VUHDO_I18N_TT.K083 = "Stellen Sie die max. Anzahl der Gruppen pro Zeile ein, wenn \"gruppiert\" angewählt ist.";
VUHDO_I18N_TT.K084 = "Wählen Sie diese Option um die Spieler im Fenster lose, d.h. ohne Gruppierung in Gruppen oder Klassen anzuzeigen. Durch Auswahl dieser Option werden die Gruppenüberschriften automatisch ausgeblendet.";
VUHDO_I18N_TT.K085 = "Durch Auswahl dieser Option werden die Spieler des Fenster gruppiert nach Klassen, Gruppen etc. angezeigt.";
VUHDO_I18N_TT.K086 = "Wenn angewählt werden leere Gruppen des Fensters ausgeblendet. (funktioniert nur, wenn \"gruppiert\" angewählt ist).";
VUHDO_I18N_TT.K087 = "Wählen Sie die maximale Zahl an Heilbalken pro Spalte, bevor eine neue Spalte begonnen wird.";
VUHDO_I18N_TT.K088 = "Setzt den Ankerpunkt des Fensters in die linke obere Ecke.";
VUHDO_I18N_TT.K089 = "Setzt den Ankerpunkt des Fensters in die rechte obere Ecke.";
VUHDO_I18N_TT.K090 = "Setzt den Ankerpunkt des Fensters in die linke untere Ecke.";
VUHDO_I18N_TT.K091 = "Setzt den Ankerpunkt des Fensters in die rechte untere Ecke.";
VUHDO_I18N_TT.K092 = "Zeigt die Spieler in einer Gruppe in der Reihenfolge an, wie sie in der Blizzard-Schlachtzuganzeige erscheinen.";
VUHDO_I18N_TT.K094 = "Sortiert die Spieler einer Gruppe alphabetisch nach Namen.";
VUHDO_I18N_TT.K095 = "Bewegen Sie den Knopf, um die Höhe der Spaltenüberschriften zu ändern.";
VUHDO_I18N_TT.K096 = "Bewegen Sie den Knopf, um den Abstand zwischen Spaltenüberschriften un Balken zu justieren.";
VUHDO_I18N_TT.K097 = "Wählen Sie diese Option, um die Spaltenüberschriften zu aktivieren. (Note: \"Basic\"=>\"grouped\" must be selected.)";
VUHDO_I18N_TT.K098 = "Bewegen Sie den Knopf, um die Hintergrundtextur für die Spaltenüberschriften einzustellen.";
VUHDO_I18N_TT.K099 = "Wählen Sie eine Hintergrundtextur für die Spaltenüberschriften.";
VUHDO_I18N_TT.K100 = "Stellen Sie die Breite der Spaltenüberschriftentextur als Prozentsatz der Balkenbreite ein.";
VUHDO_I18N_TT.K101 = "Stellen Sie die Textgrösse für die Spaltenüberschriften ein.";
VUHDO_I18N_TT.K102 = "Wählen Sie diese Option, um die Spaltenüberschriften in Klassenfarben anzuzeigen. (Hinweis: Wirkt sich nur aus, wenn die Spalte eine Klasse repräsentiert)";
VUHDO_I18N_TT.K103 = "Wählen Sie eine Farbe für Text und Hintergrund der Spaltenüberschriften.";
VUHDO_I18N_TT.K104 = "Passen Sie das Aussehen der Spaltenüberschriften an.";
VUHDO_I18N_TT.K105 = "Nehmen Sie grundsätzliche Einstellungen zum Erscheinungsbild der Fenster vor.";
VUHDO_I18N_TT.K106 = "Stellen Sie ein, wie die Tooltips aussehen sollen.";
VUHDO_I18N_TT.K107 = "Konfigurieren Sie Inhalt und Erscheinung der Balkenbeschriftungen.";
VUHDO_I18N_TT.K108 = "Stellen Sie ein, ob und wie die Ziele der Spieler in einem Fenster angezeigt  werden.";
VUHDO_I18N_TT.K109 = "Stellen Sie Grössen und Abstände der Balken ein.";
VUHDO_I18N_TT.K110 = "Verändern Sie das Aussehen der Balken sowie des Fensterhintergrunds und -rahmens.";
VUHDO_I18N_TT.K111 = "Klicken Sie diesen Button, um die Einstellungen des aktuell sichtbaren Untermenüs für alle Fenster zu übernehmen";
VUHDO_I18N_TT.K112 = "Stellen Sie die horizontalen Abstände zwischen den Balken ein.";
VUHDO_I18N_TT.K113 = "Stellen Sie die vertikalen Abstände zwischen den Balken ein.";
VUHDO_I18N_TT.K114 = "Stellen Sie den horizontalen Abstand zum Fensterrand ein.";
VUHDO_I18N_TT.K115 = "Stellen Sie den vertikalen Abstand zum Fensterrand ein.";
VUHDO_I18N_TT.K116 = "Stellen Sie die Höhe der Gesundheitsbalken ein.";
VUHDO_I18N_TT.K117 = "Stellen Sie die Breite der Gesundheitsbalken ein.";
VUHDO_I18N_TT.K118 = "Stellen Sie den Abstand zwischen Lebensbalken und Zielbalken ein.";
VUHDO_I18N_TT.K119 = "Wählen Sie diese Option um die Spielerziele im aktuellen Fenster einzublenden.";
VUHDO_I18N_TT.K120 = "Verändern Sie die Breite des Zielbalkens.";
VUHDO_I18N_TT.K126 = "Wählen Sie diese Option, um die Lebenspunkte als PROZENTZAHL anzuzeigen.";
VUHDO_I18N_TT.K127 = "Wählen Sie diese Option, um die FEHLENDEN Lebenspunkte als absolute Zahl anzuzeigen.";
VUHDO_I18N_TT.K128 = "Wählen Sie diese Option, um die VERBLEIBENDEN Lebenspunkte als absolute Zahl anzuzeigen.";
VUHDO_I18N_TT.K129 = "Diese Option zeigt die Lebenspunkte RECHTS vom Spielernamen";
VUHDO_I18N_TT.K130 = "Diese Option zeigt die Lebenspunkte LINKS vom Spielernamen";
VUHDO_I18N_TT.K131 = "Diese Option zeigt die Lebenspunkte UNTERHALB des Spielernamens.";
VUHDO_I18N_TT.K132 = "Diese Option zeigt die Lebenspunkte OBERHALB des Spielernamens.";
VUHDO_I18N_TT.K133 = "Wählen Sie diese Option, um die Lebenspunkte im aktuellen Fenster auf den Gesundheitsbalken anzuzeigen.";
VUHDO_I18N_TT.K134 = "Stellen Sie die Textgrösse auf dem Gesundheitsbalken ein.";
VUHDO_I18N_TT.K135 = "Wählen Sie diese Option, um den Spielernamen in Klassenfarben anzuzeigen.";
VUHDO_I18N_TT.K136 = "Wählen Sie die Textfarbe für den Spielernamen auf den Gesundheitsbalken.";
VUHDO_I18N_TT.K138 = "Diese Option erlaubt Ihnen, die Position der Tooltips frei zu bestimmen. Klicken Sie auf den Demo-Tooltip, um ihn zu verschieben.";
VUHDO_I18N_TT.K139 = "Diese Option zeigt die Tooltips immer am Mouse-Cursor an. Achtung: Möglich Auswirkungen auf die Systemleistung!";
VUHDO_I18N_TT.K140 = "Diese Option zeigt die Tooltips an der von Blizzard vorgesehenen Standardposition an.";
VUHDO_I18N_TT.K141 = "Wählen Sie diese Option, um die Tooltips zu aktivieren.";
VUHDO_I18N_TT.K142 = "Wählen Sie diese Option, um Tooltips auch während des Kampfes anzuzeigen.";
VUHDO_I18N_TT.K143 = "Justieren Sie die Gesamtgrösse der Tooltips";
VUHDO_I18N_TT.K144 = "Wählen Sie eine Hintergrundfarbe für die Tooltips.";
VUHDO_I18N_TT.K145 = "Wählen Sie eine Rahmenfabre für die Tooltips.";
VUHDO_I18N_TT.K146 = "Wählen Sie diese Option, um die Einstellungen der Tastenkombination \"ALT+UMSCHALT\" zu verändern.";
VUHDO_I18N_TT.K147 = "Wählen Sie diese Option, um die Einstellungen der Tastenkombination \"STRG\" zu verändern.";
VUHDO_I18N_TT.K148 = "Wählen Sie diese Option, um die Einstellungen der Tastenkombination \"STRG+UMSCHALT\" zu verändern.";
VUHDO_I18N_TT.K149 = "Wählen Sie diese Option, um die Einstellungen der Tastenkombination \"ALT+STRG+UMSCHALT\" zu verändern.";
VUHDO_I18N_TT.K150 = "Wählen Sie diese Option, um die Einstellungen zu verändern, wenn keine Kombinationstaste gedrückt ist.";
VUHDO_I18N_TT.K151 = "Wählen Sie diese Option, um die Einstellungen der Tastenkombination \"ALT\" zu verändern.";
VUHDO_I18N_TT.K152 = "Wählen Sie diese Option, um die Einstellungen der Tastenkombination \"UMSCHALT\" zu verändern.";
VUHDO_I18N_TT.K153 = "Wählen Sie diese Option, um die Einstellungen der Tastenkombination \"ALT+STRG\" zu verändern.";
VUHDO_I18N_TT.K154 = "Klicken Sie hier, um alle Einstellungen zu übernehmen und der Optionsbildschirm zu verlassen.";
VUHDO_I18N_TT.K155 = "Klicken Sie hier, um den Optionsbildschirm abzubrechen und alle gemachten Änderungen zu verwerfen.";
VUHDO_I18N_TT.K156 = "Wählen Sie diese Option, wenn Sie keinen Zähler für die Anzahl der restlichen Aufladungen eines Buffs sehen möchten.";
VUHDO_I18N_TT.K157 = "Wählen Sie dieses Menü, um die Farben der Manabalken zu verändern."
VUHDO_I18N_TT.K158 = "Wählen Sie eine Farbe für Mana."
VUHDO_I18N_TT.K159 = "Wählen Sie eine Farbe für Wut."
VUHDO_I18N_TT.K160 = "Wählen Sie eine Farbe für Energie."
VUHDO_I18N_TT.K161 = "Wählen Sie eine Farbe für Runenmacht."
VUHDO_I18N_TT.K162 = "In diesem Untermenü können Sie Einstellung bzgl. Aggro/Bedrohung vornehmen."
VUHDO_I18N_TT.K163 = "Konfigurieren Sie einige zusätzliche Einstellungen."
VUHDO_I18N_TT.K164 = "Laden und Speichern der optischen Einstellungen sowie der Fensteranordnung."
VUHDO_I18N_TT.K165 = "Wählen Sie diese Option, um die gesetzten Main Tanks aus den übrigen Fenstern zu entfernen."
VUHDO_I18N_TT.K166 = "Wählen Sie diese Option, um die gesetzten Zielgeber aus den übrigen Fenstern zu entfernen."
VUHDO_I18N_TT.K167 = "Wählen Sie diese Option, um Ihre jeweils eigene Gruppe nicht als reguläre Gruppe anzuzeigen."
VUHDO_I18N_TT.K168 = "Wählen Sie diese Option´, um Spieler zu markieren, die AFK, tot oder nicht eingelogt sind."
VUHDO_I18N_TT.K169 = "Wählen Sie diese Option, um die Blizzard Standard Gruppenanzeige auszublenden."
VUHDO_I18N_TT.K170 = "Schaltet die Standard-Blizzard Spieleranzeige aus."
VUHDO_I18N_TT.K173 = "Wählen Sie die Aktualisierungsrate für die HoT-Anzeige" -- 173
VUHDO_I18N_TT.K176 = "Geben Sie den Namen eines Arrangements ein."
VUHDO_I18N_TT.K177 = "Wählen Sie ein Arrangement. Arrangements sind alle Einstellungen, die Position, Größe und Aufteilung der Fenster betreffen."
VUHDO_I18N_TT.K179 = "Wählen Sie die Höhe des Bedrohungsbalkens"
VUHDO_I18N_TT.K183 = "Wählen Sie eine Aktualisierungsrate für die Aggro-Prüfung"
VUHDO_I18N_TT.K184 = "Text, der links von Aggro-Habenden angezeigt wird."
VUHDO_I18N_TT.K185 = "Zeigt Aggro durch eine Texteinfassung an"
VUHDO_I18N_TT.K188 = "Text, der rechts von Aggro-Habenden angezeigt wird." -- 188
VUHDO_I18N_TT.K189 = "Zeigt den aktuellen Raid als Testeinstellung."
VUHDO_I18N_TT.K190 = "Zeigt eine 5-Manngruppe als als Testeinstellung."
VUHDO_I18N_TT.K191 = "Zeigt einen 10er Raid als Testeinstellung."
VUHDO_I18N_TT.K192 = "Zeigt einen 25er Raid als Testeinstellung."
VUHDO_I18N_TT.K193 = "Zeigt einen 40er Raid als Testeinstellung.." -- 193
VUHDO_I18N_TT.K195 = "Wählen Sie eine Schriftart für die Spaltenüberschriften."
VUHDO_I18N_TT.K196 = "Zeigt den Hintergrund der Überschriften in Klassenfarben."
VUHDO_I18N_TT.K197 = "Wählen Sie eine Textfarbe für den Namen des Ziels." -- 197
VUHDO_I18N_TT.K198 = "Stellen Sie Zauber für die Maustasten ein."
VUHDO_I18N_TT.K199 = "Stellen Sie Zauber für Tastendrücke ein. Es werden Makros erzeugt, die einen Makro-Platz verbrauchen, eine Taste fest binden aber auch mit nicht-VuhDo-Fenstern funktionieren.";
VUHDO_I18N_TT.K200 = "Stellen Sie ein, welche Trinkets und/oder sofort wirkenden Zauber Sie zusammen mit den Heilsprüchen zünden wollen."
VUHDO_I18N_TT.K201 = "Geben Sie den Namen eines Instant-Spruchs ein."
VUHDO_I18N_TT.K202 = "Geben Sie den Namen eines Instant-Spruchs ein."
VUHDO_I18N_TT.K203 = "Zündet automatisch den Instant rechts."
VUHDO_I18N_TT.K204 = "Zündet automatisch den Instant rechts." -- 204
VUHDO_I18N_TT.K205 = "Zündet das untere Trinket in der Charakteransicht."
VUHDO_I18N_TT.K206 = "Zündet das obere Trinket in der Charakteransicht."
VUHDO_I18N_TT.K207 = "Zündet Schmuckstücke auch außerhalb des Kampfes."
VUHDO_I18N_TT.K208 = "Zündet Schmuckstücke auch für HoTs."
VUHDO_I18N_TT.K209 = "Zündet ggf. angelegte Schmuckstücke automatisch sobald diese bereit sind."
VUHDO_I18N_TT.K210 = "Geben Sie einen Text ein, der im Chat ausgegeben wird, wenn Sie eine Wiederbelebung starten. Benutzen Sie \"vuhdo\" als Platzhalter für den Namen.";
VUHDO_I18N_TT.K211 = "Wählen Sie diese Option, um einen Text in den Chat auszugeben, wenn Sie eine Wiederbelebung starten. Benutzen Sie \"vuhdo\" als Platzhalter für den Namen.";
VUHDO_I18N_TT.K212 = "Wählen Sie diese Option, um alle leeren Fenster vollständig zu verbergen.";
VUHDO_I18N_TT.K213 = "Wählen Sie diese Option, um den aktuellen Fokus aus dem Privat-Tank-Fenster zu entfernen.";
VUHDO_I18N_TT.K214 = "Wählen Sie diese Option, damit Assistenten nicht ein zweites Mal in der Gruppen-/Raid-Anzeige erscheinen.";
VUHDO_I18N_TT.K215 = "Wählen Sie diese Option, um Spieler ohne Buffs automatisch nachzubuffen (nur außerhalb des Kampfes).";
VUHDO_I18N_TT.K216 = "Wählen Sie diese Option, um eingehende Heilung anderer Spieler anzeigen zu lassen.";
VUHDO_I18N_TT.K217 = "Wählen Sie diese Option, um eingehende Heilung/Überheilung in den Wert der Lebensanzeige mit einzurechnen.";
VUHDO_I18N_TT.K218 = "Mit diesem Slider können Sie die Textgröße des Textes zur Anzeige der Überheilung anpassen.";
VUHDO_I18N_TT.K219 = "Wählen Sie diese Option, um Überheilung als zusätzlichen Text auf dem Heilbalken anzeigen zu lassen. Dieser Text variiert je nach Höhe der Heilung in seiner Größe.";
VUHDO_I18N_TT.K221 = "Wählen Sie diese Option, um die Farben für fehlende Buffs auch während des Kampfes anzeigen zu lassen.";
VUHDO_I18N_TT.K222 = "Wählen Sie diese Option, um fehlende Buffs durch die jew. definierte Textfarbe anzuzeigen.";
VUHDO_I18N_TT.K223 = "Wählen Sie diese Option, um die Farbe der jew. Begleiterklasse statt der Begleiterfarbe anzuzeigen.";
VUHDO_I18N_TT.K224 = "Wählen Sie dieses Menü, um grundlegene Einstellungen der Balkenfarben vorzunehmen.";
VUHDO_I18N_TT.K225 = "Wählen Sie dieses Menü, um fortgeschrittene Einstellung für die Farben der HoT-Rechtecke vorzunehmen.";
VUHDO_I18N_TT.K226 = "Verändern Sie individuell die Klassenfarben.";
VUHDO_I18N_TT.K228 = "Wählen Sie diese Option, um Begleiter in der Farbe ihrer jeweiligen Klasse und nicht der Begleiterfarbe anzuzeigen.";
VUHDO_I18N_TT.K229 = "Wählen Sie eine Farbe für Krieger";
VUHDO_I18N_TT.K230 = "Wählen Sie eine Farbe für Schurken";
VUHDO_I18N_TT.K231 = "Wählen Sie eine Farbe für Jäger";
VUHDO_I18N_TT.K232 = "Wählen Sie eine Farbe für Paladine";
VUHDO_I18N_TT.K233 = "Wählen Sie eine Farbe für Hexenmeister";
VUHDO_I18N_TT.K234 = "Wählen Sie eine Farbe für Schamanen";
VUHDO_I18N_TT.K235 = "Wählen Sie eine Farbe für Druiden";
VUHDO_I18N_TT.K236 = "Wählen Sie eine Farbe für Priester";
VUHDO_I18N_TT.K237 = "Wählen Sie eine Farbe für Magier";
VUHDO_I18N_TT.K238 = "Wählen Sie eine Farbe für Todesritter";
VUHDO_I18N_TT.K239 = "Wählen Sie eine Farbe für Begleiter";
VUHDO_I18N_TT.K241 = "Zeigt die Anzahl Aufladungen eines HoTs mit der geänderten Textfarbe links an. Die erste Aufladung entspricht der normalen HoT-Farbe";
VUHDO_I18N_TT.K242 = "Zeigt die Anzahl Aufladungen eines HoTs mit der geänderten Hintergrundfarbe links an. Die erste Aufladung entspricht der normalen HoT-Farbe.";
VUHDO_I18N_TT.K243 = "Wählen Sie eine Farbe, wenn der HoT zwei Aufladungen hat.";
VUHDO_I18N_TT.K244 = "Wählen Sie eine Farbe, wenn der HoT drei Aufladungen hat.";
VUHDO_I18N_TT.K245 = "Wählen Sie eine Farbe, wenn der HoT vier oder mehr Aufladungen hat.";
VUHDO_I18N_TT.K246 = "Wählen Sie eine Farbe für den HoT-Balken 1";
VUHDO_I18N_TT.K247 = "Wählen Sie eine Farbe für den HoT-Balken 2";
VUHDO_I18N_TT.K248 = "Wählen Sie eine Farbe für den HoT-Balken 3";
VUHDO_I18N_TT.K249 = "Wählen Sie eine Farbe für das HOT-Farbfeld 1";
VUHDO_I18N_TT.K250 = "Wählen Sie eine Farbe für das HOT-Farbfeld 2";
VUHDO_I18N_TT.K251 = "Wählen Sie eine Farbe für das HOT-Farbfeld 3";
VUHDO_I18N_TT.K252 = "Wählen Sie eine Farbe für das HOT-Farbfeld 4";
VUHDO_I18N_TT.K253 = "Wählen Sie eine Farbe für das HOT-Farbfeld 5";
VUHDO_I18N_TT.K254 = "Wählen Sie eine Warnfarbe für auslaufende HoTs.";
VUHDO_I18N_TT.K255 = "Wählen Sie ab welcher HoT-Restdauer die Warnfarbe und/oder die erhöhte Präzision angezeigt werden sollen.";
VUHDO_I18N_TT.K256 = "Zeigt die HoT-Zähler mit einer Textumrandung an.";
VUHDO_I18N_TT.K257 = "Zeigt die HoT-Zähler mit einem Schatten an.";
VUHDO_I18N_TT.K258 = "Zeigt eine Warnfarbe für HoTs an der Restdauer unter dem links zu definerenden Wert liegt.";
VUHDO_I18N_TT.K260 = "Blendet auslaufende HoTs langsam aus.";
VUHDO_I18N_TT.K261 = "Wählen Sie eine Farbe für die selbstdefinierten (De)Buffs";
VUHDO_I18N_TT.K262 = "Diese Option zeigt reguläre Debuffs - wie selbstefinierte - ebenfalls als Icon an.";
VUHDO_I18N_TT.K263 = "Hier können Sie Einstellungen zu Standard-Debuffs vornehmen.";
VUHDO_I18N_TT.K264 = "Hier können Sie anzuzeigende Debuffs und Buffs selbst definieren.";
VUHDO_I18N_TT.K265 = "Mit dem Fenster-Wizard können Sie die wesentlichen Gruppen-Einstellungen mit wenigen Klicks durchführen.";
VUHDO_I18N_TT.K266 = "Zeigt bei selbstdefinierten (De)Buffs mit einem Icon an.";
VUHDO_I18N_TT.K267 = "Verändert die Balkenfarbe bei selbstdefinierten (De)Buffs.";
VUHDO_I18N_TT.K268 = "Zeigt eine Animation bei selbstdefinierten (De)Buffs an.";
VUHDO_I18N_TT.K269 = "Zeigt die Restdauer auf den Symbolen an.";
VUHDO_I18N_TT.K270 = "Verändern Sie die Größe des Debuff-Symbole.";
VUHDO_I18N_TT.K271 = "Wählen Sie eine Maximalzahl gleichzeitig anzuzeigender Debuff-Icons.";
VUHDO_I18N_TT.K272 = "Wählen Sie einen Klang, um das Auftreten eines selbstdefinierten (De)Buffs zu signalisieren.";
VUHDO_I18N_TT.K273 = "Zeigt die selbstdefinierten (De)Buffs durch ein Symbol an.";
VUHDO_I18N_TT.K274 = "Zeigt die selbstdefinierten (De)Buffs durch Verändern der Balkenfarbe an.";
VUHDO_I18N_TT.K275 = "Zeigt einen Animationseffekt beim Einblenden des Icons.";
VUHDO_I18N_TT.K276 = "Zeigt die Restdauer auf den Icons an.";
VUHDO_I18N_TT.K279 = "Wählen sie einen Klang, der gespielt wird, wenn ein Spieler einen Debuff bekommt.";
VUHDO_I18N_TT.K280 = "Überträgt die gewählten Einstellungen auf Ihre Fenster.";
VUHDO_I18N_TT.K281 = "Zeigt ein extra Fenster für Vehikel an.";
VUHDO_I18N_TT.K282 = "Zeigt ein Extrafenster für Begleiter an.";
VUHDO_I18N_TT.K283 = "Zeigt ein gesondertes Fenster für Ihre Privat-Tanks an.";
VUHDO_I18N_TT.K284 = "Zeigt ein gesondertes Fenster für die Maintanks.";
VUHDO_I18N_TT.K285 = "Zeigt den Schlachtzug unsortiert an.";
VUHDO_I18N_TT.K286 = "Zeigt den Schlachtzug nach wahrnehmender Rolle an: Tanks, Melees, Ranged-DPS bzw. Heiler.";
VUHDO_I18N_TT.K287 = "Zeigt den Schlachtzug klassenweise an.";
VUHDO_I18N_TT.K288 = "Zeigt den Schlachtzug nach Gruppen eingeteilt (1-8).";
VUHDO_I18N_TT.K289 = "Mit dieser Option können Sie die normale Blizzard Begleiter-Anzeige ausblenden.";
VUHDO_I18N_TT.K290 = "Mit dieser Option können Sie die normale Blizzard Spielerziel-Anzeige ausblenden.";
VUHDO_I18N_TT.K291 = "Mit dieser Option werden die Zauber gestartet, wenn Sie die Maustaste loslassen statt wenn Sie sie zu drücken.";
VUHDO_I18N_TT.K292 = "Mit dieser Option werden die normalen statt der VuhDo-eigenen Tooltips angezeigt.";
VUHDO_I18N_TT.K298 = "Mit dieser Option wird das gewählte Arrangement bei automatisch aktiviert, wenn Sie in keiner Gruppe sind.";
VUHDO_I18N_TT.K299 = "Mit dieser Option wird das gewählte Arrangement bei BIS ZU 5 Spielern automatisch aktiviert.";
VUHDO_I18N_TT.K300 = "Mit dieser Option wird das gewählte Arrangement bei BIS ZU 10 Spielern automatisch aktiviert.";
VUHDO_I18N_TT.K301 = "Mit dieser Option wird das gewählte Arrangement bei BIS ZU 25 Spielern automatisch aktiviert.";
VUHDO_I18N_TT.K302 = "Mit dieser Option wird das gewählte Arrangement bei MEHR ALS 25 Spielern automatisch aktiviert.";
VUHDO_I18N_TT.K306 = "Wählen Sie eine feste Farbe für die Gesundheitsbalken.";
VUHDO_I18N_TT.K307 = "Wählen Sie diese Option, damit die Gesundheitsbalken größer statt kleiner werden, wenn ein Spieler Leben verliert.";
VUHDO_I18N_TT.K308 = "Wählen Sie diese Option, damit die Gesundheitsbalken von oben nach unten statt von links nach rechts wachsen.";
VUHDO_I18N_TT.K309 = "Wählen Sie diese Option, um das Schlachtzugsymbol auf dem Gesundheitsbalken anzuzeigen.";
VUHDO_I18N_TT.K310 = "Wählen Sie diese Option, um die Gruppen horizontal statt vertikal auszurichten.";
VUHDO_I18N_TT.K311 = "Wählen Sie diese Option, um sich selbst immer zuoberst in ihrer Gruppe anzeigen zu lassen.";
VUHDO_I18N_TT.K312 = "Setzt den Ankerpunkt des Fensters in der Mitte oben.";
VUHDO_I18N_TT.K313 = "Setzt den Ankerpunkt des Fensters in der Mitte unten.";
VUHDO_I18N_TT.K314 = "Setzt den Ankerpunkt des Fensters links in der Mitte.";
VUHDO_I18N_TT.K315 = "Setzt den Ankerpunkt des Fensters rechts in der Mitte.";
VUHDO_I18N_TT.K316 = "Sortieren Sie die Spieler einer Gruppe nach maximalen Lebenspunkten.";
VUHDO_I18N_TT.K317 = "Wählen Sie diese Option, um die Gruppen nach Klassen zu sortieren.";
VUHDO_I18N_TT.K318 = "Wählen Sie die Breite der Gesundheitsbalken.";
VUHDO_I18N_TT.K325 = "Zeigt die HoT icons links über dem Gesundheitsbalken";
VUHDO_I18N_TT.K326 = "Zeigt die HoT icons rechts unter dem Gesundheitsbalken";
VUHDO_I18N_TT.K327 = "Zeigt die HoT icons links unter dem Gesundheitsbalken";
VUHDO_I18N_TT.K328 = "Zeigt die HoT icons rechts unter dem Gesundheitsbalken";
VUHDO_I18N_TT.K329 = "Zeigt die HoT icons links unter dem Gesundheitsbalken";
VUHDO_I18N_TT.K331 = "Die HoT-Farbquadrate werden durch eine einfache Textur angezeigt.";
VUHDO_I18N_TT.K337 = "Hier finden Sie Einstellungen bzgl. der HoT-Symbole/-Farbquadrate.";
VUHDO_I18N_TT.K338 = "Hier finden Sie Einstellungen bzgl. der HoT-Balken";
VUHDO_I18N_TT.K339 = "Justieren Sie die Gesamtgröße des Fensters.";
VUHDO_I18N_TT.K340 = "Wählen Sie diese Option, um zu verhindern, dass der Lebenstext auf Tausender eingekürzt wird (18437 statt 18.4k).";
VUHDO_I18N_TT.K341 = "Wählen Sie diese Option, um der Spielernamen auf den Lebensbalken anzeigen zu lassen.";
VUHDO_I18N_TT.K342 = "Wählen Sie diese Option, um die Klasse des Spielers als Text auf den Balken anzeigen zu lassen.";
VUHDO_I18N_TT.K343 = "Wählen Sie die maximale Anzahl Zeichen, mit der ein Spielername angezeigt wird.";
VUHDO_I18N_TT.K344 = "Wählen Sie einen Zeichensatz für Spielernamen und Lebenstext.";
VUHDO_I18N_TT.K345 = "Wählen Sie diese Option, um einen unbeabsichtigten Stance-Wechsel bei Auslösen eines Zaubers zu verhindern.";
VUHDO_I18N_TT.K346 = "Mit dieser Option können Sie Informationen über die Click-Cast Spruchbelegung in den Tooltips anzeigen lassen.";
VUHDO_I18N_TT.K347 = "Mit dieser Option empfängt der Fensterhintergrund keine Mausklicks mehr. Das ermöglicht es, Ziele anzuklicken und sich zu bewegen. Es ist dann aber nicht mehr möglich, mit Rechtsklick Raid-Leiter usw. zu ermitteln.";
VUHDO_I18N_TT.K348 = "Diese Option sperrt die Fenster, um unbeabsichtigtes Verschieben zu verhindern.";
VUHDO_I18N_TT.K349 = "Wählen Sie Zaubereinstellungen für gegnerische Ziele";
VUHDO_I18N_TT.K350 = "Wählen Sie diese Option, um die Anzahl Aufladungen eines (De)Buffs anzuzeigen.";
VUHDO_I18N_TT.K351 = "Verankerung der (De)Buffs oben links.";
VUHDO_I18N_TT.K352 = "Verankerung der (De)Buffs oben rechts.";
VUHDO_I18N_TT.K353 = "Verankerung der (De)Buffs unten links.";
VUHDO_I18N_TT.K354 = "Verankerung der (De)Buffs unten rechts.";
VUHDO_I18N_TT.K355 = "Verschieben Sie die (De)Buffs in vertikaler Richtung.";
VUHDO_I18N_TT.K356 = "Verschieben Sie die (De)Buffs in horizontaler Richtung.";
VUHDO_I18N_TT.K357 = "Wählen Sie diese Option, um ggf. den Namen des Tierbesitzers/Vehikel-Fahrers im Lebenstext anzuzeigen.";
VUHDO_I18N_TT.K358 = "Hier können Sie Einstellungen bezüglich automatischer Spruchwahl außerhalb des Kampfes treffen.";
VUHDO_I18N_TT.K359 = "Wählen Sie eine Modifikationstaste, unter der die automatische Spruchwahl ausgelöst werden soll.";
VUHDO_I18N_TT.K360 = "Anwählen, um während des Kampfes tote Spieler auf Mausklick automatisch wiederzubeleben (nur für Druiden).";
VUHDO_I18N_TT.K361 = "Diese Option zeigt die Zielbalken links vom Gesundheitsbalken."
VUHDO_I18N_TT.K362 = "Diese Option zeigt die Zielbalken rechts vom Gesundheitsbalken."
VUHDO_I18N_TT.K363 = "Wählen Sie die Empfindlichkeit des Schadensblitzens. Je größer der Wert desto geringer der Schaden, der nötig ist, um das Blitzen auszulösen.";
VUHDO_I18N_TT.K364 = "Wählen Sie diese Option um den Lebenstext zu verstecken, wenn das Leben überhalb der Irrelevant-Schwelle ist.";
VUHDO_I18N_TT.K365 = "Wählen Sie diese Option, um die HoT-Einstellungen zusammen mit der Tastaturbelegung zu laden.";
VUHDO_I18N_TT.K366 = "Wählen Sie diese Funktion, um beim Heilen den Geheilten auch gleichzeitg ins Ziel zu nehmen.";
VUHDO_I18N_TT.K367 = "In diesem Menü können Sie auswählen, ob und welche Arten eingehender Heilung Sie sehen möchten.";
VUHDO_I18N_TT.K376 = "Wählen Sie diese Option, um die Heilbalken unten innerhalb der Gruppe anzuordnen. (bzw. rechts, wenn \"horizontal\" angewählt ist).";
VUHDO_I18N_TT.K377 = "Wählen Sie eine Textur für den Rahmen des Fensters.";
VUHDO_I18N_TT.K378 = "Wählen Sie die Breite des Rahmens.";
VUHDO_I18N_TT.K379 = "Wählen Sie den Abstand des Hintergrunds zum Rahmen.";
VUHDO_I18N_TT.K380 = "Filtert Ihren eigenen Heilbalken aus der regulären Raidanzeige heraus.";
VUHDO_I18N_TT.K382 = "Zeigt einen Rand (Outline) statt des Schattens um Lebens- und Namenstext.";
VUHDO_I18N_TT.K383 = "Keine Pets bei der Buffverfolgung einbeziehen.";
VUHDO_I18N_TT.K384 = "Sortiert den Raid, wie in \"Move!\" definiert. Macht nur dann Sinn, wenn Anordnung \"frei\" oben gewählt wurde.";
VUHDO_I18N_TT.K385 = "Wählen Sie eine Balkenfarbe für den Fall, dass der Buff fehlt.";
VUHDO_I18N_TT.K386 = "Zeigt das Fehlen des Buffs durch die Balkenfarbe an.";
VUHDO_I18N_TT.K387 = "Erhöht die Priorität des Buffs.";
VUHDO_I18N_TT.K388 = "Verringert die Priorität des Buffs.";
VUHDO_I18N_TT.K389 = "Wählen Sie eine Farbe für HoT 6.";
VUHDO_I18N_TT.K390 = "Kehrt die Sortierreihenfolge um.";
VUHDO_I18N_TT.K391 = "Stellen Sie die Größe der Schlachtzugsymbole ein.";
VUHDO_I18N_TT.K392 = "Setzt den Ankerpunkt oben links.";
VUHDO_I18N_TT.K393 = "Setzt den Ankerpunkt oben rechts.";
VUHDO_I18N_TT.K394 = "Setzt den Ankerpunkt unten links.";
VUHDO_I18N_TT.K395 = "Setzt den Ankerpunkt unten rechts.";
VUHDO_I18N_TT.K396 = "Setzt den Ankerpunkt links.";
VUHDO_I18N_TT.K397 = "Setzt den Ankerpunkt oben.";
VUHDO_I18N_TT.K398 = "Setzt den Ankerpunkt unten.";
VUHDO_I18N_TT.K399 = "Setzt den Ankerpunkt rechts.";
VUHDO_I18N_TT.K400 = "Verändern Sie die horizontale Ausrichtung der Komponente.";
VUHDO_I18N_TT.K401 = "Verändern Sie die vertikale Ausrichtung der Komponente.";
VUHDO_I18N_TT.K402 = "Einstellungen zu Schlachtzugsymbolen und dem Text für Überheilung.";
VUHDO_I18N_TT.K403 = "Speichern sie die aktuelle Tastenbelegung.";
VUHDO_I18N_TT.K404 = "Wählen Sie eine gespeicherte Tastenbelegung.";
VUHDO_I18N_TT.K405 = "Versteckt das Standard-Fokusfenster.";
VUHDO_I18N_TT.K406 = "Die Aufladungen eines HoTs werden nicht angezeigt.";
VUHDO_I18N_TT.K407 = "Die verbleibenden Aufladungen eines HoTs werden als Text angezeigt.";
VUHDO_I18N_TT.K408 = "Die verbleibenden Aufladungen eines HoTs werden als Dreiecke angezeigt.";
VUHDO_I18N_TT.K409 = "Fenster im Solospiel verstecken.";
VUHDO_I18N_TT.K410 = "Fenster in 5er-Gruppen verstecken.";
VUHDO_I18N_TT.K411 = "Legt die Farben für Schlachtugsymbole fest.";
VUHDO_I18N_TT.K412 = "Klicken um die Default-Einstellungen für alle (De)Buffs zu übernehmen.";
VUHDO_I18N_TT.K413 = "Wählen Sie eine Farbe für diesen (De)Buff.";
VUHDO_I18N_TT.K414 = "Wählen Sie, welche Schlachtzugsymbole angezeigt werden sollen.";
VUHDO_I18N_TT.K415 = "Wählen Sie eine Textfarbe für den Überheilung-Text.";
VUHDO_I18N_TT.K416 = "Zeigt die Schlachtzugsymbole durch geänderte Balkenfarbe.";
VUHDO_I18N_TT.K417 = "Zeigt die Farben nur für Symbole die unter Fenster=>Sonstige definiert sind.";
VUHDO_I18N_TT.K418 = "Wählen Sie eine Farbe für dieses Schlachtzugsymbol.";
VUHDO_I18N_TT.K419 = "Tank-Modus zeigt nur Spieler an, deren Bedrohungssituation kritisch ist. Gegner, die andere Spieler zufällig ins Ziel nehmen, werden ignoriert.";
VUHDO_I18N_TT.K420 = "Nur für Priester: Zeigt die verbleibende Absorption von Schilden. Achtung: EXPERIMENTELL.";
VUHDO_I18N_TT.K421 = "Farbe für Spieler bei voller Gesundheit.";
VUHDO_I18N_TT.K422 = "Farbe für Spieler bei mittlerer Gesundheit.";
VUHDO_I18N_TT.K423 = "Farbe für Spieler bei niedriger Gesundheit."
VUHDO_I18N_TT.K425 = "Aktualisierungsrate der Cluster-Prüfung.";
VUHDO_I18N_TT.K426 = "Setzt den max. Abstand, bis zu dem Spieler als in einem Cluster zueinander befindlich gelten.";
VUHDO_I18N_TT.K427 = "Wählt die minimale Gesundheit, ab der Spieler als lohnendes Ziel einer Gruppenheilung gelten.";
VUHDO_I18N_TT.K428 = "Wählt die Minimalzahl an Spielern unter dem Gesundheitslevel, die eine Gruppenheilung als angemessen erscheinen lassen.";
VUHDO_I18N_TT.K429 = "Wählt die Minimalzahl an Spielern unter dem Gesundheitslevel, die eine Gruppenheilung als optimal erscheinen lassen.";
VUHDO_I18N_TT.K430 = "Diese Option wählen, wenn die Gruppenheilung von Ihrem Spieler ausgeht/überspringt (und nicht dem Ziel des Zaubers).";
VUHDO_I18N_TT.K431 = "Diese Option wählen, wenn die Gruppenheilung vom Zauberziel ausgeht/überspringt. (und nicht von Ihnen).";
VUHDO_I18N_TT.K432 = "Diese Option wählen, wenn theoretisch alle Raidmitglieder von der Heilung getroffen werden können.";
VUHDO_I18N_TT.K433 = "Diese Option wählen, wenn nur Ziele getroffen werden können, die sich in der selben Gruppe wie das Zauberziel befinden.";
VUHDO_I18N_TT.K435 = "Diese Option schaltet die Anzeige der Anzahl der im Cluster befindlichen Personen im HoT-Icon an.";
VUHDO_I18N_TT.K436 = "Zeigt die globale Abklingzeit anhand eines Balkens.";
VUHDO_I18N_TT.K437 = "Ermittelt Cluster, die sich kreisförmig um das Ziel befinden.";
VUHDO_I18N_TT.K438 = "Ermittelt Cluster, die von einem Spieler zum nächsten springen."
VUHDO_I18N_TT.K439 = "Maximale Anzahl an Spielern, die von der Gruppenheilung getroffen werden können.";
VUHDO_I18N_TT.K440 = "Wählen Sie eine Farbe für das Cluster-HoT-Icon, wenn das Cluster akzeptabel ist.";
VUHDO_I18N_TT.K441 = "Wählen Sie eine Farbe für das Cluster-HoT-Icon, wenn das Cluster optimal ist.";
VUHDO_I18N_TT.K443 = "Wählen Sie Farbe und Transparenz des Balkens für die globale Abklingzeit."
VUHDO_I18N_TT.K444 = "Diese Options schaltet das Arrangement bei einer Raid-Stärke von bis zu 15 Spielern ein.";
VUHDO_I18N_TT.K446 = "Wählen Sie einen Debuff von der Ignorieren-Liste.";
VUHDO_I18N_TT.K447 = "Behandelt Tanks aus dem Dungeon-Finder-Tool als Main Tanks und zeigt sie in der Liste der Main Tanks an.";
VUHDO_I18N_TT.K448 = "Stellen Sie die Cluster-Erkennung für Ihre Gruppenheilung ein.";
VUHDO_I18N_TT.K451 = "Schaltet das automatische Nachbuffen über das Mausrad ein.";
VUHDO_I18N_TT.K452 = "Wählen Sie ein gespeichertes Bouquet oder geben Sie einen neuen Namen ein.";
VUHDO_I18N_TT.K453 = "Wählen Sie ein Spezial-Ereignis oder geben Sie den Namen ein Buffs oder Debuffs ein.";
VUHDO_I18N_TT.K454 = "Wählen Sie eine Farbe für das Ereignis.";
VUHDO_I18N_TT.K455 = "Wählen Sie ein Icon für das Ereignis. Wählen Sie \"- kein / Default -\" um das Standard-Icon bei Buffs und Debuffs anzuzeigen.";
VUHDO_I18N_TT.K456 = "Stellen Sie Indikatoren wie Statusbalken, Rahmen und Icons ein.";
VUHDO_I18N_TT.K457 = "Konfigurieren Sie Ihre Bouquets. Bouquets sind priorisierte Listen aus Zaubern und/oder Ereignissen";
VUHDO_I18N_TT.K458 = "Zeigt das Buff-Fenster kompakter an.";
VUHDO_I18N_TT.K459 = "Geben Sie hier den Namen für ein neues oder zu kopierendes Bouquet ein.";
VUHDO_I18N_TT.K460 = "Geben Sie den Namen eines Buffs, Debuffs oder HoTs hier ein.";
VUHDO_I18N_TT.K461 = "Wählen Sie eine Farbe für einen leeren Statusbalken.";
VUHDO_I18N_TT.K462 = "Wählen Sie eine Farbe für einen mittleren Statusbalkenwert.";
VUHDO_I18N_TT.K463 = "Wählen Sie eine Farbe für einen vollen Statusbalken.";
VUHDO_I18N_TT.K464 = "Wählen Sie ein Bouquet, das durch diesen Indikator angezeigt werden soll.";
VUHDO_I18N_TT.K465 = "Schaltet \"Clique\"-Spruchzuweisungen ein. Achtung: Lädt nach Änderung die UI neu.";
VUHDO_I18N_TT.K466 = "Überprüft Mitspieler unabhängig von ihrer Entfernung";
VUHDO_I18N_TT.K467 = "Überprüft nur Mitspieler im selben Gebiet.";
VUHDO_I18N_TT.K468 = "Überprüft nur Mitspieler innerhalb von 100 Metern.";
VUHDO_I18N_TT.K469 = "Überprüft nur Mitspieler innerhalb von 40 Metern.";
VUHDO_I18N_TT.K470 = "Prüft die Talentbäume der Mitspieler. Kann Konflikte mit anderen Addons verursachen.";
VUHDO_I18N_TT.K471 = "Ändert die Wachstumsrichtung der Balken auf rechts=>links.";
VUHDO_I18N_TT.K472 = "Zeigt Spieler durch Aufblitzen der Balken an, die gerade schweren Schaden nehmen.";
VUHDO_I18N_TT.K473 = "Zeigt die HoTs mit dem Icon des Zaubers.";
VUHDO_I18N_TT.K474 = "Zeigt die HoTs in einer glänzenden Textur.";
VUHDO_I18N_TT.K475 = "Profil wird automatisch bei Wechsel zu den primären Taltenten aktiviert";
VUHDO_I18N_TT.K476 = "Profil wird automatisch bei Wechsel zu den sekundären Taltenten aktiviert";
VUHDO_I18N_TT.K477 = "In diesem Menü können Sie Teile der Konfiguration zurücksetzen";
VUHDO_I18N_TT.K478 = "Springen Sie in das Menü zurück, aus dem Sie kamen.";
VUHDO_I18N_TT.K479 = "Cluster werden nur angezeigt, wenn der Spruch in dieser Box keinen Cooldown hat. Löschen, um Cluster immer anzuzeigen.";
VUHDO_I18N_TT.K480 = "Verändert die Skalierung des Optionsbildschirms";
VUHDO_I18N_TT.K481 = "Wählen Sie einen Zeichensatz für HoT-Timer und -Zähler";
VUHDO_I18N_TT.K482 = "Stellt die Größe des HoT-Textes ein";
VUHDO_I18N_TT.K483 = "Wählen Sie ein Lebensbalken-Bouquet für dieses Fenster, wenn es vom Allgemeinen (Optionen=> Allg. => Indikatoren) abweichen soll.";
VUHDO_I18N_TT.K485 = "Wählen, um Ihr aktuelles Ziel aus dem Privat-Tank-Fenster zu entfernen.";
VUHDO_I18N_TT.K486 = "Sperrt das Profil, um versehentliches Überschreiben zu verhindern.";
VUHDO_I18N_TT.K487 = "Verhindert den Benutzerdialog vor Überschreiben eines Profils.";
VUHDO_I18N_TT.K488 = "Zeigt den Richtungspfeil nur für tote Spieler.";
VUHDO_I18N_TT.K489 = "Zeigt die Entfernung zu Spielern ausser Reichweite.";
VUHDO_I18N_TT.K490 = "Zeigt die Richtung zu Spielern ausser Reichweite durch einen Pfeil.";
VUHDO_I18N_TT.K491 = "Zeigt den Namen neuer eigener Debuffs für 2 sec über dem Icon.";
VUHDO_I18N_TT.K492 = "Aktivieren um Notfall-Makros zu erzeugen, die nach einem Disconnect in-fight die Raid-Fenster wiederherstellen können. Es werden zwei freie Makro-Slots je Charakter benötigt."
VUHDO_I18N_TT.K493 = "Verändert die Größe des Richtungspfeils."
VUHDO_I18N_TT.K494 = "Zielprofil wählen";
VUHDO_I18N_TT.K495 = "Exportiert alle derzeitig eingestellten eigenen Debuffs in alle Profile dieses Charakters.";
VUHDO_I18N_TT.K496 = "Exportiert alle derzeitig eingestellten eigenen Debuffs in das gewählte Profil.";
VUHDO_I18N_TT.K497 = "Exportiert alle derzeitig eingestellten eigenen Debuffs in alle vorhandenen Profile.";
VUHDO_I18N_TT.K498 = "Bricht einen ggf. gerade angefangenen Zauber ab.";
VUHDO_I18N_TT.K499 = "Wählen die die Zeichen-Ebene der Heil-Fenster.";
VUHDO_I18N_TT.K500 = "Use combined buffing. Currently only Shaman's \"Call of the Elements\".";
VUHDO_I18N_TT.K501 = "Aktiviert Unterstützung für \"Button Facade\".  Achtung: Lädt nach Änderung die UI neu.";
VUHDO_I18N_TT.K502 = "Sperrt die Fensterpositionen in-fight.";
VUHDO_I18N_TT.K503 = "HoTs rechts über den Manabalken";
VUHDO_I18N_TT.K504 = "HoTs links über den Manabalken";
VUHDO_I18N_TT.K505 = "HoTs rechts an der Unterseite";
VUHDO_I18N_TT.K506 = "HoTs links an der Unterseite";
VUHDO_I18N_TT.K507 = "Breite des Seitenbalken rechts.";
VUHDO_I18N_TT.K508 = "Breite des Seitenbalken links.";
VUHDO_I18N_TT.K509 = "Richtungspfeil auch Zeigen, wenn nicht ausser Reichweite.";
VUHDO_I18N_TT.K510 = "Farbe für HoT-Kästchen 7";
VUHDO_I18N_TT.K511 = "Blizz Standard-Raid-Fenster verstecken.";
VUHDO_I18N_TT.K512 = "Erzeugt VuhDo-lokale Tastenzuweisungen. Es wird kein freier Makro-Platz benötigt, Tasten können ausserhalb des VuhDo-Fensters anders belegt werden.";
VUHDO_I18N_TT.K513 = "Makes the HoT icons flash shortly before HoT expires";
VUHDO_I18N_TT.K514 = "Zeigt einen Tooltip für eigene Debuffs";
VUHDO_I18N_TT.K515 = "Zeigt die Gesamtzah Hitpoints.";
VUHDO_I18N_TT.K516 = "Ausschalten um die Standard Blizz UI eingehende Heilung zu deaktivieren, um Runtime-Fehler zu vermeiden. Anschalten, wenn dies auf Ihrem System keine Probleme verursacht.";
VUHDO_I18N_TT.K517 = "Setzt den Ankerpunkt des Textes ins Zentrum.";
VUHDO_I18N_TT.K518 = "Passen Sie die Textgröße an";
VUHDO_I18N_TT.K519 = "Wählen Sie einen Zeichensatz";
VUHDO_I18N_TT.K520 = "Wählen Sie eine Textfarbe und eine Farbe für den Textschatten (= Hintergrund).";
VUHDO_I18N_TT.K521 = "Schaltet den Textschatten ein.";
VUHDO_I18N_TT.K522 = "Schaltet die Umrahmung des Textes ein.";
VUHDO_I18N_TT.K523 = "Zeigt die Sekunden, seitdem der Spieler einen Debuff hat anstatt der verbleibenden Debuff-Dauer";
VUHDO_I18N_TT.K524 = "Wertet das Combat-Log aus. Die Reaktionszeit der Lebensbalken wird dadurch verbessert.";
VUHDO_I18N_TT.K525 = "Laden und Speichern von Tastenbelegungen.";
VUHDO_I18N_TT.K526 = "Exportieren verschiedener Einstellungen zu anderen Profilen.";
VUHDO_I18N_TT.K527 = "Zeigt \"Göttliche Aegis\" initial mit 40% des Lebens der Priesters an, abschalten um den Anfangswert mit 100% anzuzeigen.";
VUHDO_I18N_TT.K528 = "Zeigt die letzten 100 statt 10 Sekunden der Dauer an.";
VUHDO_I18N_TT.K529 = "Legt die Position von Debuffs und den Zeichensatz und Farbe der Zähler fest.";
VUHDO_I18N_TT.K530 = "Handschuhverzauberungen automatisch zünden.";
VUHDO_I18N_TT.K531 = "Schaltet die Kantenglättung ab.";
VUHDO_I18N_TT.K532 = "Farbe je nach Freund/Feind Zieltyp festlegen.";
VUHDO_I18N_TT.K533 = "Zeigt die Klassenfarbe für Ziele.";
VUHDO_I18N_TT.K534 = "Ziele werden einfarbig angezeigt.";
VUHDO_I18N_TT.K535 = "Zeigt einen Farbverlauf je nach HP des Ziels.";
VUHDO_I18N_TT.K536 = "Farbe für gegnerische Ziele, die bereits von einem anderen Spieler angegriffen wurden.";
VUHDO_I18N_TT.K537 = "Einstellungen für die Farbe der Zielbalken";
VUHDO_I18N_TT.K538 = "Wählen Sie die minimale Gesamtheilmenge zur Anzeige der Gruppenheilung";
VUHDO_I18N_TT.K539 = "Zeigt nur Gruppenheilzauber an, die Ihre Klasse beherrscht.";
VUHDO_I18N_TT.K540 = "Zieht eingehende Heilungen von der zu erwartenden Gesamtheilleistung ab.";
VUHDO_I18N_TT.K541 = "Deaktiviert den AOE-Hinweis, wenn der Zauber auf Cooldown ist";
VUHDO_I18N_TT.K543 = "Einstellungen zur Anzeige des Gruppenheilungs-Hinweises";
VUHDO_I18N_TT.K544 = "Gradzahl, in der die Gruppenheilung in einem Konus vor Ihrem Spieler aktiv ist (360 = rundherum). Nützlich für Licht der Morgendämmerung (auf 180 setzen).";
VUHDO_I18N_TT.K545 = "Einstellen der HoT-Icon-Größe. Achtung: Nur aktiv, wenn die Icons um den Balken herum angeordnet sind."
VUHDO_I18N_TT.K546 = "Versteckt der Blizzard Standard-Raid-Manager.";
VUHDO_I18N_TT.K547 = "Eingehende Heilung nur berücksichtigen, wenn der Spruch Zauberzeit hat.";
VUHDO_I18N_TT.K548 = "Versteckt die Einheiten-Buttons für nicht-existente Raid-Mitglieder. (Ziel, Fokus und Raid-Mitglieder, die während des Kampfes den Raid verlassen)";

VUHDO_I18N_APPLY_TO_ALL = "für alle";
VUHDO_I18N_TEST = "Test"; -- nv
VUHDO_I18N_ADD = "Hinzufügen";
VUHDO_I18N_SELECT = "Wählen";
VUHDO_I18N_NEW_COLOR = "Neue Farbe";
VUHDO_I18N_OLD_COLOR = "Alte Farbe";
VUHDO_I18N_HIDE_CHARGES = "Ohne Stacks";
VUHDO_I18N_POWERS = "Mana";
VUHDO_I18N_HOT_COLORS = "HoT-Farben";
VUHDO_I18N_ICONS = "Icons";
VUHDO_I18N_COUNTDOWN = "Countdown";
VUHDO_I18N_APPLIANCES = "Aufladungen";
VUHDO_I18N_FADE_OUT = "Verblassen";
VUHDO_I18N_POWER_TYPES = "Mana-Typen";
VUHDO_I18N_THREAT = "Bedrohung\n/ Eingehend";
VUHDO_I18N_MISC = "Sonstiges";
VUHDO_I18N_PANEL_WIZARD = "Wizard";
VUHDO_I18N_PRIV_TANKS = "Privat-Tank";
VUHDO_I18N_ICON = "Icon";
VUHDO_I18N_ANIMATION = "Animation";
VUHDO_I18N_STORE = "Sichern";
VUHDO_I18N_SAVE = "Speichern";
VUHDO_I18N_DELETE = "Löschen";
VUHDO_I18N_APPLY = "Anwenden";
VUHDO_I18N_ADDITIONAL_PANELS = "Zusätzliche Fenster";
VUHDO_I18N_UNSORT = "Unsortiert";
VUHDO_I18N_ROLES = "Rollen";
VUHDO_I18N_CLASSES = "Klassen";
VUHDO_I18N_GROUPS = "Gruppen";
VUHDO_I18N_MAIN_PANEL = "Hauptfenster";
VUHDO_I18N_PARTY = "Gruppe";
VUHDO_I18N_PET = "Begleiter";
VUHDO_I18N_TARGET = "Ziel";
VUHDO_I18N_HIDE_STANDARD = "Standard verstecken...";
VUHDO_I18N_HOT_TARGETING = "Globaler Scanner";
VUHDO_I18N_OR_ENTER_PROFILE_NAME = "... oder einen neuen Namen eingeben";
VUHDO_I18N_LEFT = "Links";
VUHDO_I18N_RIGHT = "Rechts";
VUHDO_I18N_CHECK_FOR_AGGRO = "Aggro überwachen";
VUHDO_I18N_CURR = "akt.";
VUHDO_I18N_BAR_COLOR = "Balkenfarbe";
VUHDO_I18N_INV_GROWTH = "Umkehren";
VUHDO_I18N_VERTICAL = "Vertikal";
VUHDO_I18N_RAID_ICON = "Raid Icon";
VUHDO_I18N_YOU_FIRST = "Du zuerst";
VUHDO_I18N_IICONSI = "[Icons]";
VUHDO_I18N_ISQUARESI = "[Rechtecke]";
VUHDO_I18N_HOT_ORDER = "HoT Anordnung";
VUHDO_I18N_TEXT_POSITION = "Textposition";
VUHDO_I18N_FLAGS = "Flags";
VUHDO_I18N_SHOW_TEXT = "Text zeigen";
VUHDO_I18N_KEYS = "Tasten";
VUHDO_I18N_SPEC_2 = "Spec 2";
VUHDO_I18N_SPEC_1 = "Spec 1";
VUHDO_I18N_MANAGE_KEYS = "Tastenbel. verwalten";
VUHDO_I18N_INSTANT_2 = "Instant 2";
VUHDO_I18N_INSTANT_1 = "Instant 1";
VUHDO_I18N_TRINKET_2 = "Trinket 2";
VUHDO_I18N_TRINKET_1 = "Trinket 1";
VUHDO_I18N_TRIGGER_WHAT = "Was auslösen...";
VUHDO_I18N_ALSO_OUT_FIGHT = "+ out-fight";
VUHDO_I18N_ALSO_HOTS = "+ HoTs";

VUHDO_I18N_KEEP_STANCE = "Stance-safe";
VUHDO_I18N_AUTO_TRIGGER = "Auto-Auslösen";
VUHDO_I18N_SPELL_ADVICE = "Benutzen Sie die Standard-Tastenbelegung, um die Sprüche unten zuzuweisen. (Scrollen Sie zum Abschnitt 'VuhDo'.)";
VUHDO_I18N_SAVE_AS = "Speichern...";
VUHDO_I18N_MOVE = "Move!";
VUHDO_I18N_SPELLS = "Zauber";
VUHDO_I18N_PANELS = "Fenster";
VUHDO_I18N_BUFFS = "Buffs";
VUHDO_I18N_ICON_SCALE = "Icon-Größe";
VUHDO_I18N_REFRESH_AGGRO = "Aktualisieren";
VUHDO_I18N_PANEL_SCALE = "Gesamtgröße Fenster";
VUHDO_I18N_MAX_CHARS = "Max.Zeichen (0=Alle)";
-- #+v1.178
VUHDO_I18N_HOSTILE = "Gegnerisch";
VUHDO_I18N_HOSTILE_TITLE = "[FEINDLICH]";
VUHDO_I18N_HOSTILE_ADVICE_1 = "Spruchname oder target/focus/assist"
VUHDO_I18N_HOSTILE_ADVICE_2 = "KEINE Makronamen oder andere Konstanten!!!"
VUHDO_I18N_HOSTILE_ADVICE_3 = "Trinkets etc. werden NICHT autom.gezündet!!!"
-- Slider
VUHDO_I18N_WARN_PREC_AT = "Warnung/genau ab";
VUHDO_I18N_MAX_NO_DE_BUFFS = "Max. # (de)buffs";
VUHDO_I18N_BRIGHTNESS = "Helligkeit";
VUHDO_I18N_RAID_ICON_SCALE = "Größe Raid-Icon";
VUHDO_I18N_NAME_TEXT_SIZE = "Größe Text Name";
VUHDO_I18N_LIFE_TEXT_SIZE = "Größe Text Leben";
-- Color swatches
VUHDO_I18N_BUFF_OKAY = "Buff OKAY";
VUHDO_I18N_BUFF_LOW = "Buff NIEDRIG";
VUHDO_I18N_BUFF_MISSING = "Buff FEHLT";
VUHDO_I18N_OUT_OF_RANGE = "Außer Reichweite";
VUHDO_I18N_COOLDOWN = "Cooldown";
VUHDO_I18N_EMPTY_GROUP = "Leere Gruppe";
VUHDO_I18N_PANEL_BACKGROUND = "Fensterhintergrund";
VUHDO_I18N_SWATCH_BORDER = "Fenster";
VUHDO_I18N_PANEL_BORDER = "Rahmen";
VUHDO_I18N_2ND_CHARGE = "2.Aufladung";
VUHDO_I18N_3RD_CHARGE = "3.Aufladung";
VUHDO_I18N_4TH_CHARGE = "4.Aufladung";
VUHDO_I18N_BAR_1 = "Balken 1";
VUHDO_I18N_BAR_2 = "Balken 2";
VUHDO_I18N_BAR_3 = "Balken 3";
VUHDO_I18N_SQUARE_1 = "Rechteck 1";
VUHDO_I18N_SQUARE_2 = "Rechteck 2";
VUHDO_I18N_SQUARE_3 = "Rechteck 3";
VUHDO_I18N_SQUARE_4 = "Rechteck 4";
VUHDO_I18N_SQUARE_5 = "Rechteck 5";
VUHDO_I18N_EMERGENCY = "Notfall";
VUHDO_I18N_NO_EMEGENCY = "Kein Notfall";
VUHDO_I18N_IRRELEVANT = "Irrelevant";
VUHDO_I18N_INCOMING = "Eingehend";
VUHDO_I18N_MANA = "Mana";
VUHDO_I18N_RAGE = "Wut";
VUHDO_I18N_ENERGY = "Energie";
VUHDO_I18N_RUNES = "Runen";
VUHDO_I18N_DEAD = "Tot";
VUHDO_I18N_OFFLINE = "Offline";
VUHDO_I18N_CHARMED = "Charmed";
VUHDO_I18N_AGGRO_BAR = "Aggro-Balken";
VUHDO_I18N_POISON = "Gift";
VUHDO_I18N_DISEASE = "Krankheit";
VUHDO_I18N_CURSE = "Fluch";
VUHDO_I18N_MAGIC = "Magie";
VUHDO_I18N_HEADER = "Titel";
VUHDO_I18N_TARGET_NAME = "Name Ziel";
VUHDO_I18N_BORDER = "Rahmen";
VUHDO_I18N_ANOUNCE_RESURRECTION = "Wiederbelebung ankündigen"; -- nv
VUHDO_I18N_FILTER = "Filter"; -- nv
VUHDO_I18N_FOCUS = "Fokus"; -- nv
VUHDO_I18N_BUFF = "Buff"; -- nv
VUHDO_I18N_OTHERS = "Anderer"; -- nv
VUHDO_I18N_1 = " 1"; -- nv
VUHDO_I18N_2 = " 2"; -- nv
VUHDO_I18N_3 = " 3"; -- nv
VUHDO_I18N_4 = " 4"; -- nv
VUHDO_I18N_5 = " 5"; -- nv
VUHDO_I18N_6 = " 6"; -- nv
VUHDO_I18N_7 = " 7"; -- nv
VUHDO_I18N_8 = " 8"; -- nv
VUHDO_I18N_10 = " 10"; -- nv
VUHDO_I18N_25 = " 25"; -- nv
VUHDO_I18N_40 = " 40"; -- nv
VUHDO_I18N_DEBUFF_DEFAULTS = "(De)Buff Defaults"; -- nv
VUHDO_I18N_ITEXTUREI = "[Textur]"; -- nv
VUHDO_I18N_BAR = "Balken"; -- nv
VUHDO_I18N_HOTS_2 = "HoTs #2"; -- nv
VUHDO_I18N_PET_CLASS = "Pet-Klasse"; -- nv
VUHDO_I18N_CLASS_COLORS = "Klassenfarben"; -- nv
VUHDO_I18N_HOT_CHARGES = "Aufladungen"; -- nv
VUHDO_I18N_TEXT_COLOR = "Textfarbe"; -- nv
VUHDO_I18N_BACK_COLOR = "Hintergrund"; -- nv
VUHDO_I18N_HOT_BARS = "HoT-Balken"; -- nv
VUHDO_I18N_OUTLINE = "Rahmen"; -- nv
VUHDO_I18N_SHADOW = "Schatten"; -- nv
VUHDO_I18N_WARNING = "Warnung"; -- nv
VUHDO_I18N_EXPIRY_WARNING = "Ablaufwarnung"; -- nv
VUHDO_I18N_COUNTDOWN_OFF = "Countdown: Aus"; -- nv
VUHDO_I18N_SECS = "secs"; -- nv
VUHDO_I18N_SECS_10 = "sec/10"; -- nv
VUHDO_I18N_FULL_DURATION = "volle Dauer"; -- nv
VUHDO_I18N_TOOLS = "Tools"; -- nv
VUHDO_I18N_TIMER = "Timer"; -- nv
VUHDO_I18N_SOUND = "Sound"; -- nv
VUHDO_I18N_STORE_DELETE = "Speichern/Löschen"; -- nv
VUHDO_I18N_DEBUFF_SOUND = "Debuff Sound"; -- nv
VUHDO_I18N_MOUSE_UP = "Zauber bei\nMaus hoch"; -- nv
VUHDO_I18N_REACTION_ON = "Reaktion bei"; -- nv
VUHDO_I18N_UNIT = "Einzeln"; -- nv
VUHDO_I18N_SOLIDD = "Einfarbig"; -- nv
VUHDO_I18N_HORIZONTAL = "Horizontal"; -- nv
VUHDO_I18N_FLAT_TEXTURE = "Flach"; -- nv
VUHDO_I18N_HOT_ICONS = "HoT-Icons"; -- nv
VUHDO_I18N_TARGET_OF_TARGET = "Ziel des Ziels"; -- nv
VUHDO_I18N_VERBOSE = "Exakt"; -- nv
VUHDO_I18N_1_DOT = "1."; -- nv
VUHDO_I18N_2_DOT = "2."; -- nv
VUHDO_I18N_3_DOT = "3."; -- nv
VUHDO_I18N_4_DOT = "4."; -- nv
VUHDO_I18N_5_DOT = "5."; -- nv
VUHDO_I18N_6_DOT = "6."; -- nv
VUHDO_I18N_7_DOT = "7."; -- nv
VUHDO_I18N_8_DOT = "8."; -- nv
VUHDO_I18N_9_DOT = "9."; -- nv
VUHDO_I18N_10_DOT = "10."; -- nv
VUHDO_I18N_11_DOT = "11."; -- nv
VUHDO_I18N_12_DOT = "12."; -- nv
VUHDO_I18N_13_DOT = "13."; -- nv
VUHDO_I18N_14_DOT = "14."; -- nv
VUHDO_I18N_15_DOT = "15."; -- nv
VUHDO_I18N_16_DOT = "16."; -- nv
VUHDO_I18N_KEY_BINDINGS = "Tastenbelegung"; -- nv
VUHDO_I18N_MOUSE_WHEEL = "Mausrad"; -- nv
VUHDO_I18N_TOOLTIP_INFO = "Zauber-Info"; -- nv
-- #+1.197
VUHDO_I18N_EDGE_SIZE = "Breite Rand";
VUHDO_I18N_EDGE_INSETS = "Randabstand";
-- #+1.204
VUHDO_I18N_IGNORE_PETS = "Keine Pets";
VUHDO_I18N_PANEL_MODEL = "Modelle";
-- #+1.207
VUHDO_I18N_OVERHEAL_TEXT = "Overheal Text";
-- #+1.210
VUHDO_I18N_NO_STACKS = "Stacks: Aus";
VUHDO_I18N_NUMBER_STACKS = "Text";
VUHDO_I18N_TRIANGLE_STACKS = "Dreiecke";
VUHDO_I18N_HIDE_PANELS = "Ausblenden";
VUHDO_I18N_SOLO = "Solo";
VUHDO_I18N_CLICK_THROUGH = "Kein Klick";
VUHDO_I18N_IHEALTH_BARI = "[Lebensbalken]";
VUHDO_I18N_SQUARE_6 = "Rechteck 6";
VUHDO_I18N_GLOSSY = "Glänzend";
VUHDO_I18N_DAMAGE_FLASH = "Schadenblitz";
VUHDO_I18N_SENSIVITY = "Empfindlichkeit";
VUHDO_I18N_HIDE_IRRELEVANT = "Nur relevant";
VUHDO_I18N_ALGINMENT = "Ausrichtung";
VUHDO_I18N_BOTTOM = "Unten";
VUHDO_I18N_PET_OWNERS = "Tierbesitzer";
VUHDO_I18N_BATTLE_REZ = "Battle Rez";
-- #+1.232
VUHDO_I18N_DEBUFF_LIST = "(De)Buff-Liste";
VUHDO_I18N_DEBUFF_EDIT_BOX = "Name eines neuen Buffs oder Debuffs";
-- #+1.233
VUHDO_I18N_BUTTON = "Taste";
VUHDO_I18N_TANK_MODE = "Tank-Modus";
-- #+1.237
VUHDO_I18N_CLUSTER_SCANNER = "Cluster-Erkennung";
VUHDO_I18N_FAIR_THRESHOLD = "Anzahl akzeptabel";
VUHDO_I18N_GOOD_THRESHOLD = "Anzahl optimal";
VUHDO_I18N_SOURCE_SPELL = "Quelle des Zaubers";
VUHDO_I18N_SOURCE_MINE = "Spieler";
VUHDO_I18N_SOURCE_ALL = "Zauberziel";
VUHDO_I18N_DEST_SPELL = "Ziel des Zaubers";
VUHDO_I18N_DEST_RAID = "Raid";
VUHDO_I18N_DEST_PARTY = "Gruppe";
VUHDO_I18N_CLUSTERS = "Clusters";
VUHDO_I18N_LOW = "Niedrig";
VUHDO_I18N_FAIR = "Mittel";
VUHDO_I18N_GOOD = "Voll";
VUHDO_I18N_HEALTH_LEVEL = "Gesundheit <";
VUHDO_I18N_CLUSTER_FINDER = "Cluster-Erkennung";
VUHDO_I18N_OTHER_HOTS = "HoTs anderer Spieler";
VUHDO_I18N_EMPTY_HOTS = "Leer";
VUHDO_I18N_COUNTER = "Zähler";
VUHDO_I18N_GLOBAL_COOLDOWN = "Globaler\nCooldown";
VUHDO_I18N_GCD = "GCD";
-- #+1.238
VUHDO_I18N_DISPLAY_OPTIONS = "Anzeigeoptionen";
VUHDO_I18N_RADIAL = "Radial";
VUHDO_I18N_CHAINED = "Verkettet";
VUHDO_I18N_CHAINED_MAX_JUMP = "Max.Anzahl Ziele Heilung";
VUHDO_I18N_TIMES = "";
VUHDO_I18N_SOURCE_DESTINATION = "Quelle/Ziel";
VUHDO_I18N_HIGH = "Hoch";
-- #+1.251
VUHDO_I18N_15 = " 15";
VUHDO_I18N_LOAD_HOTS = "Lade HoTs";
VUHDO_I18N_IGNORE_LIST = "Ignorieren";
VUHDO_I18N_FIVE_MAN_MTS = "5-Mann MTs";
VUHDO_I18N_FILTER_ONLY = "nur Filter";
VUHDO_I18N_LIFE_COLORS = "Lebensfarben";
VUHDO_I18N_SMART_WHEEL = "Smart Wheel";
VUHDO_I18N_PASTE = "Einfügen";
VUHDO_I18N_COPY = "Kopieren";
-- #+1.252
VUHDO_I18N_BOUQUETS = "Bouquets";
VUHDO_I18N_SELECT_OR_ENTER_BOUQUET = "Bouquet wählen ...";
VUHDO_I18N_NEW = "Neu";
VUHDO_I18N_BOUQUET_DETAILS = "Bouquet-Details";
VUHDO_I18N_HIGHEST_PRIO = "Höchste Priorität";
VUHDO_I18N_LOWEST_PRIO = "Niedrigste Priorität";
VUHDO_I18N_ENTER_DE_BUFF_OR_SPECIAL = "Ereignis wählen ...";
VUHDO_I18N_ITEM = "Teil";
VUHDO_I18N_SELECT_DEFAULT_ICON = "Icon wählen";
VUHDO_I18N_MINE = "Meine";
VUHDO_I18N_GRADIENT = "Verlauf";
VUHDO_I18N_INDICATORS = "Indikatoren";
VUHDO_I18N_COPIED_BOUQUET = "Bouquet kopiert ";
VUHDO_I18N_BOUQUET_ALREADY_EXISTS = ": Bouquet existiert bereits. Zuerst neuen Namen eingeben.";
VUHDO_I18N_CREATED_NEW_BOUQUET = "Neues Bouquet angelegt: ";
VUHDO_I18N_DELETED_BOUQUET = "Bouquet gelöscht: ";
VUHDO_I18N_BOUQUET_NOT_FOUND = ": Bouquet wurde nicht gefunden.";
VUHDO_I18N_SELECT_STORE_BOUQUET_FIRST = "Wählen Sie zuerst ein Bouquet";
VUHDO_I18N_SELECT_A_PROFILE = "Wählen Sie ein Profil...";
VUHDO_I18N_PROFILES = "Profile";
VUHDO_I18N_EDIT_BUTTON = "Edit...";
VUHDO_I18N_MORE_BUTTON = "Mehr...";
VUHDO_I18N_DONE_BUTTON = "Fertig";
VUHDO_I18N_BASIC = "Basic";
VUHDO_I18N_ADVANCED = "Fortgeschritten";
VUHDO_I18N_EXPERT = "Experte";
VUHDO_I18N_COMPACT = "Kompakt";
VUHDO_I18N_REALLY_DELETE_PROFILE = "Profil wirklich löschen";
VUHDO_I18N_MUST_ENTER_SELECT_PROFILE = "Sie müssen zuerst etwas auswählen.";
VUHDO_I18N_DELETED_PROFILE = "Profil wurde gelöscht";
VUHDO_I18N_TURN_AXIS = "<->Achse";
VUHDO_I18N_DO_NOT_EDIT_BOUQUET = "Generisch: DETAILS NICHT ÄNDERN !";
VUHDO_I18N_OR_NEW_BOUQUET_NAME = "... oder ein neuer Bouquet-Name";
VUHDO_I18N_OR_ENTER_DEBUFF_HOT = "... oder Buff, Debuff oder HoTs";
VUHDO_I18N_TALENT_TREES = "Talentbäume";
VUHDO_I18N_SCAN = "Prüfen";
VUHDO_I18N_INFINITE = "Unbegrenzt";
VUHDO_I18N_SAME_ZONE = "Selbe Zone";
VUHDO_I18N_100_YARDS = "100 Meter";
VUHDO_I18N_40_YARDS = "40 Meter";
VUHDO_I18N_LIFE_TEXT = "Lebenstext";
VUHDO_I18N_BACK = "Zurück";
VUHDO_I18N_CLIQUE_COMPAT_MODE = "Clique verwenden";
VUHDO_I18N_RESET = "Reset";
VUHDO_I18N_DEBUFF_COLORS = "Debuff-Farben";
VUHDO_I18N_BUFFS_HOTS = "Buffs/HoTs";
VUHDO_I18N_BUFF_WATCH = "Buff Watch";
VUHDO_I18N_CUSTOM_DEBUFFS = "Eigene Debuffs";
VUHDO_I18N_DEFAULT_BOUQUETS = "Default Bouquets";
VUHDO_I18N_EVERYTHING = "Alles";
VUHDO_I18N_LANGUAGE = "Sprachwechsel";
VUHDO_I18N_PANEL_POSITIONS = "Fensterpositonen";
VUHDO_I18N_PER_PANEL_SETTINGS = "Einst. je Fenster";
VUHDO_I18N_MINUTE = "min.";
VUHDO_I18N_MSEC = "msec";
VUHDO_I18N_PEOPLE = " Spieler";
VUHDO_I18N_RESET_CLASS_COLORS = "Setzt die Einstellungen für\ndie Klassenfarben zurück. Weiter?" ;
VUHDO_I18N_RESET_DEBUFF_COLORS = "Setzt die Einstellungen für\ndie Debuff-Farben zurück. Weiter?";
VUHDO_I18N_RESET_RAID_ICON_COLORS = "Setzt die Farben für\nSchlachtzugsziele zurück. Weiter?";
VUHDO_I18N_RESET_BUFF_WATCH = "Setzt die Einstellungen für\nBuffWatch zurück. Weiter?";
VUHDO_I18N_RESET_CUSTOM_DEBUFFS = "Setzt alle eigenen Debuffs\nund deren Einstellungen zurück. Weiter?";
VUHDO_I18N_RESET_DEFAULT_BOUQUETS = "Setzt alle Standard-Bouquets\n(keine: eigenen) zurück. Weiter?";
VUHDO_I18N_RESET_INDICATORS = "Setzt die Indikatoren-\nkonfiguration zurück. Weiter?";
VUHDO_I18N_RESET_ALL = "!!!ACHTUNG: Dies setzt VuhDo\nvollständig zurück!!! Weiter?" ;
VUHDO_I18N_RESET_LANGUAGE = "Setzt alle Einstellungen nach\nClient-Sprachwechsel zurück. Weiter?";
VUHDO_I18N_RESET_PANEL_POSITIONS = "Setzt die Fenster-\npositionen zurück. Weiter?";
VUHDO_I18N_RESET_PER_PANEL_SETTINGS = "Setzt alle Fenster-\neinstellungen zurück. Weiter?";
-- 2.17
VUHDO_I18N_LOCK = "Sperren";
VUHDO_I18N_QUIET_MODE = "Quiet Mode";
VUHDO_I18N_SETTINGS = "Einstellungen";
VUHDO_I18N_ACTIVATE_DUE_GRP_SIZE = "Automat. aktivieren";
VUHDO_I18N_CUSTOM_HEALTH_BAR_BOUQUET = "Eigenes Gesundheitsbalken-Bouquet";
VUHDO_I18N_CUSTOM_SETTINGS = "Eigene Einstellungen";
VUHDO_I18N_DISTANCE = "Abstand";
VUHDO_I18N_DEAD_ONLY = "Nur Tote";
VUHDO_I18N_DIRECTION = "Richtung";
VUHDO_I18N_IF_OOR_SHOW = "Wenn Spieler ausser Reichweite, zeige...";
VUHDO_I18N_DEBUFF_NAME = "Debuffname";
-- 2.18
VUHDO_I18N_DISABLE = "Abschalten";
VUHDO_I18N_DC_RESTORE = "d/c-Schild";
VUHDO_I18N_EXPORT_CUSTOM_DEBUFFS = "Export eigene Debuffs";
VUHDO_I18N_EXPORT_TO_PROFILE = "Exportieren zu Profil:";
VUHDO_I18N_THIS_TOONS = "Dieser Char";
VUHDO_I18N_SELECTED = "Gewähltes";
VUHDO_I18N_ALL = "Alle";
VUHDO_I18N_REPLACE = "Ersetzen";
VUHDO_I18N_SLOT = "Slot";
VUHDO_I18N_SWIFTMEND_INDICATOR =  "Spezial-Punkt";
VUHDO_I18N_MOUSEOVER_HIGHLIGHTER =  "Mouseover";
VUHDO_I18N_OUTER_BORDER =  "Äußerer";
VUHDO_I18N_SHIELD_ABSORPTION =  "Schild-Status";
VUHDO_I18N_BACKGROUND_BAR =  "Balkenhintergrund";
VUHDO_I18N_THREAT_MARKS =  "Bedrohungsmarken";
VUHDO_I18N_HEALTH_BAR =  "Lebensbalken";
VUHDO_I18N_UNDEFINED =  "<n/v>";
VUHDO_I18N_DOWN =  "ab";
VUHDO_I18N_THREAT_BAR =  "Bedrohungsbalken";
VUHDO_I18N_O_REALLY =  "O'RLY?";
VUHDO_I18N_BORDER_WIDTH =  "Breite";
VUHDO_I18N_AGGRO_LINE =  "Linie oberhalb";
VUHDO_I18N_YES =  "Ja";
VUHDO_I18N_INNER_BORDER =  "Innerer";
VUHDO_I18N_MANA_BAR =  "Manabalken";
-- 2.65
VUHDO_I18N_LINK_SPELL_COOLDOWN = "An Spruch-Cooldown koppeln";
VUHDO_I18N_RAID = "Raid";
VUHDO_I18N_FRAME_STRATA = "Fenster-Ebene";
VUHDO_I18N_VERY_LOW = "Sehr niedrig";
VUHDO_I18N_LOW = "Niedrig";
VUHDO_I18N_MEDIUM_LOW = "Niedrig-Mittel";
VUHDO_I18N_MEDIUM = "Mittel";
VUHDO_I18N_MEDIUM_HIGH = "Mittel-Hoch";
VUHDO_I18N_HIGH = "Hoch";
VUHDO_I18N_VERY_HIGH = "Sehr hoch";
VUHDO_I18N_ULTRA = "Ultra";
VUHDO_I18N_STOP_CAST = "Stop Cast";
-- 2.67
VUHDO_I18N_COMBINED_BUFF = "Kombiniert";
VUHDO_I18N_OPTIONS = "Optionen";
VUHDO_I18N_CUSTOM_ADDONS = "Fremd-Addons";
VUHDO_I18N_CLIQUE = "Clique";
VUHDO_I18N_BUTTON_FACADE = "Masque";
-- 2.70
VUHDO_I18N_MANA_BAR_HEIGHT = "Höhe des Manabalkens";
VUHDO_I18N_SIDE_LEFT_WIDTH = "Breite des linken Seitenbalkens";
VUHDO_I18N_SIDE_RIGHT_WIDTH = "Breite des rechten Seitenbalkens";

VUHDO_I18N_AMBIGUOUS_MACRO = "WARNUNG: Makro-Name |cffffffff\"%s\"|r is doppeldeutig (=Spruch-Name)! Bitte umbenennen!";
VUHDO_I18N_KEYBOARD_GLOBAL = "Keys global";
VUHDO_I18N_KEYBOARD_LOCAL = "Keys lokal";

VUHDO_I18N_LOCAL_KEY_ASSIGNMENTS = "Lokale Tastenbelegung";
VUHDO_I18N_S_M_C_OR_CONSTANT = "Spruch,Makro oder neuer Name oder target/focus/assist";
VUHDO_I18N_CURRENT_ASSIGNMENT = "Derzeitige Belegung";
VUHDO_I18N_CLEAR_BINDING = "Belegung löschen";
VUHDO_I18N_MACRO_EDITOR = "VuhDo Makro-Editor";
VUHDO_I18N_ACCEPT = "Annehmen";
VUHDO_I18N_DISCARD = "Verwerfen";
VUHDO_I18N_LKA_HINT_1 = "Benutzen sie folgende Platzhalter im Makro: |c00000000vuhdo|r => Spieler, |c00000000vdname|r => Name des Spielers" justifyH="LEFT" inherits="VuDoButtonFontDark";
VUHDO_I18N_LKA_HINT_2 = "|c00000000vdtarget, vdtargettarget|r => Ziel des Spielers/ToT, |c00000000vdpet|r => Pet des Spielers, Bsp: /use [@vuhdo] Blitzheilung" justifyH="LEFT" inherits="VuDoButtonFontDark";
VUHDO_I18N_LKA_CUSTOM_MACRO_DISCARDED = "Eigener Makro-Text wurde verworfen.";
VUHDO_I18N_NAME_CHANGE_DISCARDED = "Die Namensänderung wurde verworfen.";
VUHDO_I18N_LKA_TYPE_CHANGED = "Zuweisung von EIGENEM TEXT zu\nSpruch oder WoW-Makro geändert.\nMakro-Text verwerfen?";
VUHDO_I18N_ASSIGN_ABORTED = "Zuweisung abgebrochen.";
VUHDO_I18N_LKA_PRESS_ASSIGN_KEY = "Drücken Sie die Taste, die Sie zuweisen wollen!";
VUHDO_I18N_LKA_SUCCESS_ASSIGNED = "Taste wurde erfolgreich zugewiesen.";
VUHDO_I18N_LKA_ASSIGNED_CLEARED = "Taste erfolgreich zugewiesen. Zuweisung für \"%s\" gelöscht!";
VUHDO_I18N_LKA_BIND_CLEARED = "Die Zuweisung wurde gelöscht.";
VUHDO_I18N_LKA_NEW_BIND = "<Neue Zuweisung>";
VUHDO_I18N_LKA_EDITED_MACRO = "Bearbeitetes Makro: ";
VUHDO_I18N_FLASH = "Blinken";
VUHDO_I18N_SHOW_TOTAL = "Gesamt-HP";
VUHDO_I18N_ALIVE_TIME = "Dauer\nbisher";
VUHDO_I18N_PARSE = "Parsen";
VUHDO_I18N_TEXT_SHADOW = "Text/Schatten";
VUHDO_I18N_COMBAT_LOG = "Combat-Log";
VUHDO_I18N_ICON_TEXT_SETTINGS = "Text-Optionen:";
VUHDO_I18N_DISCARD_CHANGES_CONFIRM = "Es gibt %d Änderungen der Einstellungen.\nWollen Sie diese verwerfen?";
VUHDO_I18N_PROFILE_NOT_EXISTS = "Fehler: Es existiert kein Profil mit Namen \"%s\".";
VUHDO_I18N_PROFILE_EXPORTED_TO = "Eigene Debuffs wurden nach %s exportiert.";
VUHDO_I18N_ADDED_X_TO_Y = "Hinzufügen von %s zu %s.";
VUHDO_I18N_NOT_SELECTED = "<nichts gewählt>";
VUHDO_I18N_CUDE_EXPORT_DONE = "Export eigener Debuffs abgeschlossen.";
VUHDO_I18N_REALLY_EXPORT_CUDES = "Wirklich in exportieren?";
VUHDO_I18N_KEY_LAYOUTS = "Tasten-\nbelegung";
VUHDO_I18N_EXPORT = "Exportieren";
VUHDO_I18N_LOAD_SAVE = "Laden / Speichern";
VUHDO_I18N_MISCELLANEOUS = "Sonstiges";
VUHDO_I18N_PUMP_AEGIS = "Pump Aegis";
VUHDO_I18N_TEXT_OPTIONS = "Text-Optionen";
VUHDO_I18N_VISUALS = "Visuals";
VUHDO_I18N_SHIELDS = "Schilde";
VUHDO_I18N_RESET_PER_KEY_LAYOUTS = "Dies setzt Ihre Tasten-/Spruch-\nzuweisungen zurück. Weiter?";
VUHDO_I18N_SELECT_KEY_LAYOUT_FIRST = "Bitte wählen Sie zuerst eine Tastenzuweisung.";
VUHDO_I18N_DELETED_KEY_LAYOUT = "Tastenzuweisung \"%s\" wurde gelöscht.";
VUHDO_I18N_OVERWRITE_CURR_KEY_LAYOUT_QUESTION = "Dies überschreibt die aktuelle\nTastenzuweisung. Weiter?";
VUHDO_I18N_DELETE_KEY_LAYOUT_QUESTION = "Tastenwueisung \n\"%s\"\n wirklich löschen?";
VUHDO_I18N_ENTER_KEY_LAYOUT_NAME = "Bitte geben Sie einen Namen ein.";
VUHDO_I18N_OVERWRITE_KEY_LAYOUT_QUESTION = "Tastenzuweisung %s ist\nschon vorhanden. Überschreiben?";
VUHDO_I18N_KEY_LAYOUT_SAVED = "Tastenzuweisung \"%s\" wurde gespeichert.";
VUHDO_I18N_GLOVES = "Hände";
VUHDO_I18N_MONO = "Mono";
VUHDO_I18N_FRIEND_FOE = "Freund/Feind";
VUHDO_I18N_FIENDLY = "Freund";
VUHDO_I18N_NEUTRAL = "Neutral";
VUHDO_I18N_ENEMY = "Feind";
VUHDO_I18N_TAPPED = "Tapped";
VUHDO_I18N_SQUARE_7 = "Rechteck 7";
VUHDO_I18N_HP = "HP";
VUHDO_I18N_KNOWN_ONLY = "nur bekannte";
VUHDO_I18N_MINUS_INCOMING = "- Eingehend";
VUHDO_I18N_AOE_ADVICE = "Gruppen-\nheilung";
VUHDO_I18N_CONE = "Konus";
VUHDO_I18N_DEGREES = "Grad";
VUHDO_I18N_RAID_MANAGER = "Raid-Mgr";
VUHDO_I18N_CAST_TIME_ONLY = "Nur wenn\nZauberzeit";
VUHDO_I18N_EMPTY_BUTTONS = "Leere\nButtons";
VUHDO_I18N_HEALTH_COLOR = "Farbe Leben";

VUHDO_I18N_HIDE = "Verstecken";
VUHDO_I18N_LEAVE_ALONE = "Unverändert";
