-- Tidy Plates Panel reposition frequency



TidyPlatesMeta = {
	"NamePlate1 Frame", -- [1]
	" NamePlate1+NamePlate1UnitFrame Frame", -- [2]
	" NamePlate1+NamePlate1UnitFrame TextureColor-ffffffff", -- [3]
	" NamePlate1+NamePlate1UnitFrame TextureColor-ffffffff", -- [4]
	" NamePlate1+NamePlate1UnitFrame TextureNil", -- [5]
	" NamePlate1+NamePlate1UnitFrame TextureNil", -- [6]
	" NamePlate1+NamePlate1UnitFrame FontStringNil", -- [7]
	" NamePlate1+NamePlate1UnitFrame FontStringNil", -- [8]
	" NamePlate1+NamePlate1UnitFrame TextureNil", -- [9]
	" NamePlate1+NamePlate1UnitFrame TextureNil", -- [10]
	" NamePlate1+NamePlate1UnitFrame TextureNil", -- [11]
	" NamePlate1+NamePlate1UnitFrame TextureNil", -- [12]
	" NamePlate1+NamePlate1UnitFrame TextureNil", -- [13]


	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame1 Frame", -- [14]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame1 TextureColor-333333d9", -- [15]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame1 TextureInterface/TargetingFrame/UI-TargetingFrame-BarFill.blp", -- [16]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame1 TextureNil", -- [17]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame1 TextureNil", -- [18]


	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 Frame", -- [19]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [20]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [21]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [22]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [23]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [24]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [25]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [26]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [27]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [28]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [29]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [30]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [31]


	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame3 Frame", -- [32]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame3 TextureColor-333333d9", -- [33]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame3 FontStringNil", -- [34]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame3 TextureFileData ID 1300837", -- [35]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame3 TextureNil", -- [36]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame3 TextureNil", -- [37]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame3 TextureNil", -- [38]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame3 TextureInterface/TargetingFrame/UI-TargetingFrame-BarFill.blp", -- [39]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame4 Frame", -- [40]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame5 Frame", -- [41]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame5 TextureNil", -- [42]
}

-- Guard Selected

TidyPlatesMeta = {
	"NamePlate1 Frame", -- [1]
	" NamePlate1+NamePlate1UnitFrame Frame", -- [2]
	" NamePlate1+NamePlate1UnitFrame TextureColor-ffffffff", -- [3]
	" NamePlate1+NamePlate1UnitFrame TextureColor-ffffffff", -- [4]
	" NamePlate1+NamePlate1UnitFrame TextureNil", -- [5]
	" NamePlate1+NamePlate1UnitFrame TextureNil", -- [6]
	" NamePlate1+NamePlate1UnitFrame FontStringIronforge Guard", -- [7]
	" NamePlate1+NamePlate1UnitFrame FontStringNil", -- [8]
	" NamePlate1+NamePlate1UnitFrame TextureNil", -- [9]
	" NamePlate1+NamePlate1UnitFrame TextureNil", -- [10]
	" NamePlate1+NamePlate1UnitFrame TextureNil", -- [11]
	" NamePlate1+NamePlate1UnitFrame TextureNil", -- [12]
	" NamePlate1+NamePlate1UnitFrame TextureNil", -- [13]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame1 Frame", -- [14]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame1 TextureColor-333333d9", -- [15]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame1 TextureInterface\\TargetingFrame\\UI-TargetingFrame-BarFill.blp", -- [16]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame1 TextureInterface\\TargetingFrame\\UI-TargetingFrame-BarFill.blp", -- [17]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame1 TextureNil", -- [18]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 Frame", -- [19]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [20]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [21]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [22]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [23]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [24]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [25]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [26]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [27]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [28]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [29]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [30]
	"   NamePlate1+NamePlate1UnitFrame+UnnamedFrame1+UnnamedFrame2 TextureColor-ffffffff", -- [31]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame3 Frame", -- [32]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame3 TextureColor-333333d9", -- [33]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame3 FontStringNil", -- [34]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame3 TextureFileData ID 1300837", -- [35]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame3 TextureNil", -- [36]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame3 TextureNil", -- [37]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame3 TextureNil", -- [38]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame3 TextureInterface\\TargetingFrame\\UI-TargetingFrame-BarFill.blp", -- [39]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame4 Frame", -- [40]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame5 Frame", -- [41]
	"  NamePlate1+NamePlate1UnitFrame+UnnamedFrame5 TextureNil", -- [42]
}