
HandyNotesDB = {
	["profileKeys"] = {
		["Ekkjuice - Beta Leveling Realm 03"] = "Ekkjuice - Beta Leveling Realm 03",
		["Tektonfury - Beta Leveling Realm 03"] = "Tektonfury - Beta Leveling Realm 03",
		["Ekkbomber - Beta Leveling Realm 03"] = "Ekkbomber - Beta Leveling Realm 03",
		["Icyblade - Beta Leveling Realm 03"] = "Icyblade - Beta Leveling Realm 03",
		["Ekkcrazy - Beta Max Level PvP"] = "Ekkcrazy - Beta Max Level PvP",
		["Ekkangry - Beta Leveling Realm 03"] = "Ekkangry - Beta Leveling Realm 03",
		["Ekkangry - Beta Max Level PvP"] = "Ekkangry - Beta Max Level PvP",
		["Ekkcrazy - Beta Leveling Realm 03"] = "Ekkcrazy - Beta Leveling Realm 03",
		["Codesixteen - Beta Leveling Realm 03"] = "Codesixteen - Beta Leveling Realm 03",
	},
	["profiles"] = {
		["Ekkjuice - Beta Leveling Realm 03"] = {
		},
		["Tektonfury - Beta Leveling Realm 03"] = {
		},
		["Ekkbomber - Beta Leveling Realm 03"] = {
		},
		["Icyblade - Beta Leveling Realm 03"] = {
		},
		["Ekkcrazy - Beta Max Level PvP"] = {
		},
		["Ekkangry - Beta Leveling Realm 03"] = {
		},
		["Ekkangry - Beta Max Level PvP"] = {
		},
		["Ekkcrazy - Beta Leveling Realm 03"] = {
		},
		["Codesixteen - Beta Leveling Realm 03"] = {
		},
	},
}
HandyNotes_HandyNotesDB = {
	["profileKeys"] = {
		["Ekkjuice - Beta Leveling Realm 03"] = "Ekkjuice - Beta Leveling Realm 03",
		["Tektonfury - Beta Leveling Realm 03"] = "Tektonfury - Beta Leveling Realm 03",
		["Ekkbomber - Beta Leveling Realm 03"] = "Ekkbomber - Beta Leveling Realm 03",
		["Icyblade - Beta Leveling Realm 03"] = "Icyblade - Beta Leveling Realm 03",
		["Ekkcrazy - Beta Max Level PvP"] = "Ekkcrazy - Beta Max Level PvP",
		["Ekkangry - Beta Leveling Realm 03"] = "Ekkangry - Beta Leveling Realm 03",
		["Ekkangry - Beta Max Level PvP"] = "Ekkangry - Beta Max Level PvP",
		["Ekkcrazy - Beta Leveling Realm 03"] = "Ekkcrazy - Beta Leveling Realm 03",
		["Codesixteen - Beta Leveling Realm 03"] = "Codesixteen - Beta Leveling Realm 03",
	},
	["global"] = {
		["HighMountain"] = {
			[53464356] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[44097630] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "Bitestone Rockbeater",
			},
			[50983880] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[49236224] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[48952717] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "稀有",
				["desc"] = "",
			},
			[52556640] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[53063947] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[45135992] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[49232711] = {
				["title"] = "稀有",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Mellok, Son of Torok",
			},
			[39347427] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[47536435] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[49297320] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[46640742] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Mrrklr",
			},
			[43981097] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Tamed Coralback",
			},
			[40955774] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "",
			},
			[50803504] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[42676171] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[53404869] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "Windmaster Julan",
			},
			[38244557] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Bristlemaul",
			},
			[38376139] = {
				["title"] = "入口",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[43394736] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Dargok Thunderuin",
			},
			[37353381] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
			[45525593] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "稀有",
				["desc"] = "Snarf",
			},
			[50983646] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[41327244] = {
				["icon"] = 1,
				["title"] = "入口",
				["cont"] = true,
				["desc"] = "",
			},
			[41974164] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "",
			},
			[47723025] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "稀有",
				["desc"] = "Majestic Elderhorn",
			},
			[50962570] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "稀有",
				["desc"] = "Shara Felbreath",
			},
			[52023241] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "Crawliac Hagfeather",
			},
			[46763991] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "High Crawliac",
			},
			[42095270] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[36626214] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
			[51094814] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Hartli the Snatcher",
			},
			[38215897] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[39386228] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
			[50665277] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[50013715] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[51473185] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Skullhat",
			},
			[42202730] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
			[42203482] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
			[47037268] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[39297618] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
		},
		["Valsharah"] = {
			[64527665] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "稀有",
				["desc"] = "",
			},
			[61066943] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "稀有",
				["desc"] = "Perrexx",
			},
			[51566789] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
			[52808734] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "稀有",
				["desc"] = "Shivering Ashmaw Cub",
			},
			[42675803] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "Douglas Carrington",
			},
			[43845322] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "稀有",
				["desc"] = "Darkshade",
			},
			[55137308] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "入口",
				["desc"] = "",
			},
			[39584200] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[48607234] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
			[44204770] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[56235730] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[37965281] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "稀有",
				["desc"] = "Theryssia",
			},
			[61832935] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Lyrath Moonfeather",
			},
			[65775359] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Grelda the Hag",
			},
			[62697032] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
			[56407356] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
			[49444885] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "稀有",
				["desc"] = "Eileen the Raven",
			},
			[55567762] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
			[64695126] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "Flameflare",
			},
			[66623711] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Wraithtalon",
			},
			[51878044] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
			[60304426] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Dreadbog",
			},
			[62624742] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Thondrax",
			},
			[40514470] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[67494504] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Filandras Mistcaller",
			},
			[58883398] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Ironbranch",
			},
			[63037696] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
			[41557828] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "稀有",
				["desc"] = "",
			},
			[61203504] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[53516862] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "稀有",
				["desc"] = "Syndrelle",
			},
			[46458631] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
			[37015722] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "Cecily Radcliffe",
			},
		},
		["Helheim"] = {
			[28626186] = {
				["title"] = "稀有",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Soulthirster",
			},
			[60475362] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Bleakwater Helsquid",
			},
		},
		["ThunderTotemInterior"] = {
			[47096132] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[62786785] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
		},
		["ThunderTotem"] = {
			[50587542] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
			[63515912] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
			[13685533] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[32394179] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
		},
		["Stormheim"] = {
			[61404440] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[36415172] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "稀有",
				["desc"] = "Whitewater Typhoon",
			},
			[69064471] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "Bonespeaker Carver",
			},
			[49245108] = {
				["title"] = "稀有",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Tiptog the Lost",
			},
			[45442255] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Apothecary Perez",
			},
			[61044207] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "Tarben",
			},
			[73394173] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "Bonespeaker Runeaxe",
			},
			[42457747] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[72525014] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Mordvigbjorn",
			},
			[53323645] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "Sigrid",
			},
			[27355749] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "Adolescent Storm Drake",
			},
			[64855181] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Urgev the Flayer",
			},
			[78646118] = {
				["title"] = "稀有",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Grrvrgull the Conquerer",
			},
			[61424317] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Tarben",
			},
			[49664726] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[41877580] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "Drekirjar Trapper",
			},
			[45797744] = {
				["title"] = "稀有",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Bladesquall",
			},
			[59816809] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Ivory Sentinel",
			},
			[35725410] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
			[67273986] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "The Nameless King",
			},
			[57994504] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Helmouth Captain",
			},
			[68974184] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
			[67985787] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[31345610] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "箱子",
				["desc"] = "",
			},
			[49767799] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Raging Tempest",
			},
			[46838404] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Fathnyr",
			},
			[54782930] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Starbuck",
			},
			[37824090] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "稀有",
				["desc"] = "Bloodstalker Alpha",
			},
			[49517176] = {
				["title"] = "稀有",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Stormwing Matriarch",
			},
			[55014715] = {
				["icon"] = 1,
				["title"] = "箱子",
				["cont"] = true,
				["desc"] = "",
			},
			[41713397] = {
				["cont"] = true,
				["icon"] = 1,
				["title"] = "稀有",
				["desc"] = "Egyl the Enduring",
			},
			[63092070] = {
				["icon"] = 1,
				["title"] = "稀有",
				["cont"] = true,
				["desc"] = "Eileen the Raven",
			},
			[49794486] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[43698010] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[42035763] = {
				["title"] = "稀有",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Hook",
			},
			[46778041] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[62086047] = {
				["title"] = "稀有",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Isel the Hammer",
			},
			[41556658] = {
				["title"] = "稀有",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Glimar Ironfist",
			},
		},
		["MardumtheShatteredAbyss"] = {
			[74415734] = {
				["title"] = "稀有",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "King Voras",
			},
			[63362312] = {
				["title"] = "稀有",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Count Nefarious",
			},
			[78745044] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Queen's Centurion",
			},
			[73484890] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Fel Weaver",
			},
			[41753760] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[80334818] = {
				["title"] = "入口",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Queen's Centurion",
			},
			[68662741] = {
				["title"] = "稀有",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "General Volroth",
			},
			[63242243] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Vile Soulmaster",
			},
			[34857021] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[82085044] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Demon Hunter",
			},
			[44967811] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Mo'arg Brute",
			},
			[64035845] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Fel Lord Caza",
			},
			[63435415] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[42194918] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Mo'arg Brute",
			},
			[70635399] = {
				["title"] = "入口",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[81324145] = {
				["title"] = "稀有",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Overseer Brutarg",
			},
			[74285454] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "",
			},
			[66622380] = {
				["title"] = "箱子",
				["cont"] = true,
				["icon"] = 1,
				["desc"] = "Burning Soulstalker",
			},
		},
		["VaultOfTheWardensDH"] = {
			[23238159] = {
				["title"] = "箱子",
				["cont"] = true,
				["level"] = 3,
				["icon"] = 1,
				["desc"] = "",
			},
			[41443293] = {
				["title"] = "箱子",
				["cont"] = true,
				["level"] = 2,
				["icon"] = 1,
				["desc"] = "",
			},
			[58683472] = {
				["title"] = "箱子",
				["cont"] = true,
				["level"] = 1,
				["icon"] = 1,
				["desc"] = "Wrath-Lord Lekos",
			},
			[41466354] = {
				["title"] = "箱子",
				["cont"] = true,
				["level"] = 2,
				["icon"] = 1,
				["desc"] = "",
			},
			[49753275] = {
				["title"] = "稀有",
				["cont"] = true,
				["level"] = 1,
				["icon"] = 1,
				["desc"] = "Kethrazor",
			},
			[24440985] = {
				["title"] = "箱子",
				["cont"] = true,
				["level"] = 3,
				["icon"] = 1,
				["desc"] = "",
			},
			[48365374] = {
				["title"] = "箱子",
				["cont"] = true,
				["level"] = 1,
				["icon"] = 1,
				["desc"] = "Kayn Sunfury",
			},
			[69002738] = {
				["title"] = "稀有",
				["cont"] = true,
				["level"] = 1,
				["icon"] = 1,
				["desc"] = "Wrath-Lord Lekos",
			},
			[32114815] = {
				["title"] = "箱子",
				["cont"] = true,
				["level"] = 2,
				["icon"] = 1,
				["desc"] = "",
			},
		},
	},
	["profiles"] = {
		["Ekkjuice - Beta Leveling Realm 03"] = {
		},
		["Tektonfury - Beta Leveling Realm 03"] = {
		},
		["Ekkbomber - Beta Leveling Realm 03"] = {
		},
		["Icyblade - Beta Leveling Realm 03"] = {
		},
		["Ekkcrazy - Beta Max Level PvP"] = {
		},
		["Ekkangry - Beta Leveling Realm 03"] = {
		},
		["Ekkangry - Beta Max Level PvP"] = {
		},
		["Ekkcrazy - Beta Leveling Realm 03"] = {
		},
		["Codesixteen - Beta Leveling Realm 03"] = {
		},
	},
}
