if GetLocale() == "deDE" then
qcLocalize = {
	ABYSSALDEPTHS = "Abyssische Tiefen", -- Needs review
	AHNKAHETTHEOLDKINGDOM = "Ahn'kahet: The Old Kingdom", -- Requires localization
	AHNQIRAJ = "Ahn'Qiraj", -- Requires localization
	AHNQIRAJTHEFALLENKINGDOM = "Ahn'Qiraj: Das Gefallene Königreich", -- Needs review
	ALCHEMY = "Alchemie", -- Needs review
	ALTERACVALLEY = "Alteractal", -- Needs review
	ARATHIBASIN = "Arathibecken", -- Needs review
	ARATHIHIGHLANDS = "Arathihochland", -- Needs review
	ARCHAEOLOGY = "Archäologie", -- Needs review
	ASHENVALE = "Eschental", -- Needs review
	AUCHENAICRYPTS = "Auchenai Crypts", -- Requires localization
	AUCHINDOUN = "Auchindoun", -- Requires localization
	AZJOLNERUB = "Azjol-Nerub", -- Requires localization
	AZSHARA = "Azshara", -- Needs review
	AZUREMYSTISLE = "Azurmythosinsel", -- Needs review
	BADLANDS = "Ödland", -- Needs review
	BARADINHOLD = "Baradin Hold", -- Requires localization
	BATTLEGROUNDS = "Schlachtfelder", -- Needs review
	BLACKFATHOMDEEPS = "Blackfathom Deeps", -- Requires localization
	BLACKROCKCAVERNS = "Blackrock Caverns", -- Requires localization
	BLACKROCKDEPTHS = "Blackrock Depths", -- Requires localization
	BLACKROCKSPIRE = "Blackrock Spire", -- Requires localization
	BLACKSMITHING = "Schmiedekunst", -- Needs review
	BLACKTEMPLE = "Black Temple", -- Requires localization
	BLACKWINGDESCENT = "Blackwing Descent", -- Requires localization
	BLACKWINGLAIR = "Blackwing Lair", -- Requires localization
	BLADESEDGEMOUNTAINS = "Schergrat", -- Needs review
	BLASTEDLANDS = "Verwüstete Lande", -- Needs review
	BLOODMYSTISLE = "Blutmythosinsel", -- Needs review
	BOREANTUNDRA = "Boreanische Tundra", -- Needs review
	BREWFEST = "Braufest", -- Needs review
	BURNINGSTEPPES = "Brennende Steppe", -- Needs review
	CAVERNSOFTIME = "Caverns of Time", -- Requires localization
	CHILDRENSWEEK = "Kinderwoche", -- Needs review
	CLASSES = "Klassen", -- Needs review
	CLASSQUESTS = "Klassenquests", -- Needs review
	CLEARUPDATECACHE = "Lösche und aktualisiere Cache...", -- Needs review
	COILFANGRESERVOIR = "Coilfang Reservoir", -- Requires localization
	COMBINEDMAPANDQUESTFILTERS = "Kombinierte Karten- und Questlisten-Filter", -- Needs review
	CONFIGSUBTITLE = "Diese Option erlaubt Dir die Art und Weise zu ändern, wie Quest Completist seine Daten verwendet und filtert.", -- Needs review
	CONFIGTITLE = "Quest Completist - Konfiguration", -- Needs review
	CONTINENTS = "Kontinente", -- Needs review
	COOKING = "Kochen", -- Needs review
	CRYSTALSONGFOREST = "Kristallsangwald", -- Needs review
	DALARAN = "Dalaran", -- Needs review
	DARKMOONFAIRE = "Dunkelmond-Jahrmarkt", -- Needs review
	DARKSHORE = "Dunkelküste", -- Needs review
	DARNASSUS = "Darnassus", -- Needs review
	DAYOFTHEDEAD = "Tag der Toten", -- Needs review
	DEADWINDPASS = "Gebirgspass der Totenwinde", -- Needs review
	DEATHKNIGHT = "Todesritter", -- Needs review
	DEEPHOLM = "Tiefenheim", -- Needs review
	DEEPRUNTRAM = "Die Tiefenbahn", -- Needs review
	DESOLACE = "Desolace", -- Needs review
	DIREMAUL = "Dire Maul", -- Requires localization
	DRAGONBLIGHT = "Drachenöde", -- Needs review
	DRAGONSOUL = "Dragon Soul", -- Requires localization
	DRAKTHARONKEEP = "Drak'Tharon Keep", -- Requires localization
	DREADWASTES = "Schreckensöde", -- Needs review
	DRUID = "Druide", -- Needs review
	DUNGEONSANDRAIDS = "Dungeons und Schlachtzüge", -- Needs review
	DUNMOROGH = "Dun Morogh", -- Needs review
	DUROTAR = "Durotar", -- Needs review
	DUSKWOOD = "Dämmerwald", -- Needs review
	DUSTWALLOWMARSH = "Düstermarschen", -- Needs review
	EASTERNKINGDOMS = "Östliche Königreiche", -- Needs review
	EASTERNPLAGUELANDS = "Östliche Pestländer", -- Needs review
	ELEMENTALBONDS = "Elementare Bande", -- Needs review
	ELWYNNFOREST = "Wald von Elwynn", -- Needs review
	ENCHANTING = "Verzauberkunst", -- Needs review
	ENDTIME = "End Time", -- Requires localization
	ENGINEERING = "Ingenieurskunst", -- Needs review
	EVERSONGWOODS = "Immersangwald", -- Needs review
	EYEOFTHESTORM = "Auge des Sturms", -- Needs review
	FELWOOD = "Teufelswald", -- Needs review
	FERALAS = "Feralas", -- Needs review
	FIRELANDS = "Firelands", -- Requires localization
	FIRELANDSINVASION = "Die Invasion der Feuerlande", -- Needs review
	FIRSTAID = "Erste Hilfe", -- Needs review
	FISHING = "Angeln", -- Needs review
	GHOSTLANDS = "Geisterlande", -- Needs review
	GILNEAS = "Gilneas", -- Requires localization
	GILNEASCITY = "Gilneas City", -- Requires localization
	GNOMEREGAN = "Gnomeregan", -- Requires localization
	GRIMBATOL = "Grim Batol", -- Requires localization
	GRIZZLYHILLS = "Grizzlyhügel", -- Needs review
	GRUULSLAIR = "Gruul's Lair", -- Requires localization
	GUNDRAK = "Gundrak", -- Requires localization
	HALLOWSEND = "Schlotternächte", -- Needs review
	HALLSOFLIGHTNING = "Halls of Lightning", -- Requires localization
	HALLSOFORIGINATION = "Halls of Origination", -- Requires localization
	HALLSOFREFLECTION = "Halls of Reflection", -- Requires localization
	HALLSOFSTONE = "Halls of Stone", -- Requires localization
	HARVESTFESTIVAL = "Erntedankfest", -- Needs review
	HELLFIRECITADEL = "Hellfire Citadel", -- Requires localization
	HELLFIREPENINSULA = "Höllenfeuerhalbinsel", -- Needs review
	HELLFIRERAMPARTS = "Hellfire Ramparts", -- Requires localization
	HERBALISM = "Kräuterkunde", -- Needs review
	HIDECOMPLETEDQUESTS = "Verstecke abgeschlossene Quests", -- Needs review
	HIDEINPROGRESSQUESTS = "Verstecke laufende Quests", -- Needs review
	HIDELOWLEVELQUESTS = "Verstecke niedrigstufige Quests", -- Needs review
	HIDENONACTIVESEASONALQUESTS = "Verstecke nicht aktive Quests", -- Needs review
	HIDEOTHERFACTIONQUESTS = "Verstecke Quests der anderen Fraktion", -- Needs review
	HIDEOTHERPROFESSIONQUESTS = "Verstecke Quests anderer Berufe", -- Needs review
	HIDEOTHERRACEANDCLASSQUESTS = "Verstecke Quests anderer Rassen und Klassen", -- Needs review
	HILLSBRADFOOTHILLS = "Vorgebirge des Hügellands", -- Needs review
	HOUROFTWILIGHT = "Hour of Twilight", -- Requires localization
	HOWLINGFJORD = "Der Heulende Fjord", -- Needs review
	HROTHGARSLANDING = "Hrothgars Landestelle", -- Needs review
	HUNTER = "Jäger", -- Needs review
	HYJALSUMMIT = "Hyjal Summit", -- Requires localization
	ICECROWN = "Eiskrone", -- Needs review
	ICECROWNCITADEL = "Icecrown Citadel", -- Requires localization
	INSCRIPTION = "Inschriftenkunde", -- Needs review
	IRONFORGE = "Eisenschmiede", -- Needs review
	ISLEOFCONQUEST = "Insel der Eroberung", -- Needs review
	ISLEOFQUELDANAS = "Insel von Quel'Danas", -- Needs review
	JEWELCRAFTING = "Juwelenschleifen", -- Needs review
	KALIMDOR = "Kalimdor", -- Needs review
	KARAZHAN = "Karazhan", -- Requires localization
	KELPTHARFOREST = "Tang'tharwald", -- Needs review
	KEZAN = "Kezan", -- Needs review
	KRASARANGWILDS = "Krasarangwildnis", -- Needs review
	KUNLAISUMMIT = "Gipfel von Kun-Lai", -- Needs review
	LEATHERWORKING = "Lederverarbeitung", -- Needs review
	LEGENDARY = "Legendär", -- Needs review
	LOCHMODAN = "Loch Modan", -- Needs review
	LOSTCITYOFTHETOLVIR = "Lost City of the Tol'vir", -- Requires localization
	LOVEISINTHEAIR = "Liebe liegt in der Luft", -- Needs review
	LUNARFESTIVAL = "Mondfest", -- Needs review
	MAGE = "Magier", -- Needs review
	MAGISTERSTERRACE = "Magisters' Terrace", -- Requires localization
	MAGTHERIDONSLAIR = "Magtheridon's Lair", -- Requires localization
	MANATOMBS = "Mana-Tombs", -- Requires localization
	MAPFILTERS = "Kartenfilter", -- Needs review
	MARAUDON = "Maraudon", -- Requires localization
	MIDSUMMERFIREFESTIVAL = "Sonnenwendfest", -- Needs review
	MINING = "Bergbau", -- Needs review
	MISCELLANEOUS = "Verschiedenes", -- Needs review
	MOGUSHANVAULTS = "Mogu'shan Vaults", -- Requires localization
	MOLTENCORE = "Molten Core", -- Requires localization
	MOLTENFRONT = "Geschmolzene Front", -- Needs review
	MONK = "Mönch", -- Needs review
	MOONGLADE = "Mondlichtung", -- Needs review
	MOUNTHYJAL = "Berg Hyjal", -- Needs review
	MULGORE = "Mulgore", -- Needs review
	NAGRAND = "Nagrand", -- Needs review
	NAXXRAMAS = "Naxxramas", -- Requires localization
	NETHERSTORM = "Nethersturm", -- Needs review
	NEWYEARSEVE = "Silvester", -- Needs review
	NOBLEGARDEN = "Nobelgartenfest", -- Needs review
	NORTHERNBARRENS = "Nördliches Brachland", -- Needs review
	NORTHERNSTRANGLETHORN = "Nördliches Schlingendorntal", -- Needs review
	NORTHREND = "Nordend", -- Needs review
	OLDHILLSBRADFOOTHILLS = "Old Hillsbrad Foothills", -- Requires localization
	ONYXIASLAIR = "Onyxia's Lair", -- Requires localization
	OPTIONS = "Optionen", -- Needs review
	ORGRIMMAR = "Orgrimmar", -- Needs review
	OUTLAND = "Scherbenwelt", -- Needs review
	PALACEOFTHEHEAVENS = "Palace of the Heavens", -- Requires localization
	PALADIN = "Paladin", -- Needs review
	PANDARIA = " Pandaria", -- Needs review
	PERFORMSERVERQUERY = "Server-Abfrage durchführen...", -- Needs review
	PILGRIMSBOUNTY = "Pilgerfreudenfest", -- Needs review
	PITOFSARON = "Pit of Saron", -- Requires localization
	PRIEST = "Priester", -- Needs review
	PROFESSIONS = "Berufe", -- Needs review
	QUERYREQUESTED = "Eine Serverabfrage wird durchgeführt...", -- Needs review
	QUESTLISTFILTERS = "Questlisten-Filter", -- Needs review
	QUESTSFOUND = "%d Gefundene Quests", -- Needs review
	RAGEFIRECHASM = "Ragefire Chasm", -- Requires localization
	RAIDS = "Schlachtzüge", -- Needs review
	RAZORFENDOWNS = "Razorfen Downs", -- Requires localization
	RAZORFENKRAUL = "Razorfen Kraul", -- Requires localization
	REDRIDGEMOUNTAINS = "Rotkammgebirge", -- Needs review
	ROGUE = "Schurke", -- Needs review
	RUINSOFAHNQIRAJ = "Ruins of Ahn'Qiraj", -- Requires localization
	RUINSOFGILNEAS = "Ruinen von Gilneas", -- Needs review
	RUINSOFGILNEASCITY = "Ruinen der Stadt Gilneas", -- Needs review
	SCARLETMONASTERY = "Scarlet Monastery", -- Requires localization
	SCHOLOMANCE = "Scholomance", -- Requires localization
	SEARINGGORGE = "Sengende Schlucht", -- Needs review
	SEASONAL = "Saisonal", -- Needs review
	SERPENTSHRINECAVERN = "Serpentshrine Cavern", -- Requires localization
	SETHEKKHALLS = "Sethekk Halls", -- Requires localization
	SHADOPANMONASTERY = "Shado-pan Monastery", -- Requires localization
	SHADOWFANGKEEP = "Shadowfang Keep", -- Requires localization
	SHADOWLABYRINTH = "Shadow Labyrinth", -- Requires localization
	SHADOWMOONVALLEY = "Schattenmondtal", -- Needs review
	SHAMAN = "Schamane", -- Needs review
	SHATTRATHCITY = "Shattrath", -- Needs review
	SHIMMERINGEXPANSE = "Schimmernde Weiten", -- Needs review
	SHOLAZARBASIN = "Sholazarbecken", -- Needs review
	SHOWMAPICONS = "Zeige Kartensymbole", -- Needs review
	SIEGEOFNIUZAOTEMPLE = "Siege of Niuzao Temple", -- Requires localization
	SILITHUS = "Silithus", -- Needs review
	SILVERMOONCITY = "Silbermond", -- Needs review
	SILVERPINEFOREST = "Silberwald", -- Needs review
	SILVERSHARDMINES = "Silbersplitter Mine", -- Needs review
	SKINNING = "Kürschnerei", -- Needs review
	SORTALPHA = "Sortierung: Alphabetisch", -- Needs review
	SORTLEVEL = "Sortierung: Stufe", -- Needs review
	SOUTHERNBARRENS = "Südliches Brachland", -- Needs review
	SPECIAL = "Besonderes", -- Needs review
	SPECIALS = "Specials", -- Needs review
	STONETALONMOUNTAINS = "Steinkrallengebirge", -- Needs review
	STORMSTOUTBREWERY = "Stormstout Brewery", -- Requires localization
	STORMWINDCITY = "Sturmwind", -- Needs review
	STRANDOFTHEANCIENTS = "Strand der Uralten", -- Needs review
	STRANGLETHORNVALE = "Schlingendorntal", -- Needs review
	STRATHOLME = "Stratholme", -- Requires localization
	SUNKENTEMPLE = "Sunken Temple", -- Requires localization
	SUNWELLPLATEAU = "Sunwell Plateau", -- Requires localization
	SWAMPOFSORROWS = "Sümpfe des Elends", -- Needs review
	TAILORING = "Schneiderei", -- Needs review
	TANARIS = "Tanaris", -- Needs review
	TELDRASSIL = "Teldrassil", -- Needs review
	TEMPESTKEEP = "Tempest Keep", -- Requires localization
	TEMPLEOFAHNQIRAJ = "Temple of Ahn'Qiraj", -- Requires localization
	TEMPLEOFKOTMOGU = "Tempel der Jadeschlange", -- Needs review
	TEMPLEOFTHEREDCRANE = "Temple of the Red Crane", -- Requires localization
	TEROKKARFOREST = "Wälder von Terokkar", -- Needs review
	THEARCATRAZ = "The Arcatraz", -- Requires localization
	THEBASTIONOFTWILIGHT = "The Bastion of Twilight", -- Requires localization
	THEBATTLEFORGILNEAS = "Die Schlacht um Gilneas", -- Needs review
	THEBLACKMORASS = "The Black Morass", -- Requires localization
	THEBLOODFURNACE = "The Blood Furnace", -- Requires localization
	THEBOTANICA = "The Botanica", -- Requires localization
	THECAPEOFSTRANGLETHORN = "Das Schlingendornkap", -- Needs review
	THECULLINGOFSTRATHOLME = "The Culling of Stratholme", -- Requires localization
	THEDEADMINES = "The Deadmines", -- Requires localization
	THEEXODAR = "Die Exodar", -- Needs review
	THEEYE = "The Eye", -- Requires localization
	THEEYEOFETERNITY = "The Eye of Eternity", -- Requires localization
	THEFORGEOFSOULS = "The Forge of Souls", -- Requires localization
	THEGATEOFTHESETTINGSUN = "The Gate of the Setting Sun", -- Requires localization
	THEHINTERLANDS = "Das Hinterland", -- Needs review
	THEJADEFOREST = "Der Jadewald", -- Needs review
	THELOSTISLES = "Die Verlorenen Inseln", -- Needs review
	THEMAELSTROM = "Der Mahlstrom", -- Needs review
	THEMECHANAR = "The Mechanar", -- Requires localization
	THENEXUS = "The Nexus", -- Requires localization
	THEOBSIDIANSANCTUM = "The Obsidian Sanctum", -- Requires localization
	THEOCULUS = "The Oculus", -- Requires localization
	THERUBYSANCTUM = "The Ruby Sanctum", -- Requires localization
	THESHATTEREDHALLS = "The Shattered Halls", -- Requires localization
	THESLAVEPENS = "The Slave Pens", -- Requires localization
	THESTEAMVAULT = "The Steamvault", -- Requires localization
	THESTOCKADE = "The Stockade", -- Requires localization
	THESTONECORE = "The Stonecore", -- Requires localization
	THESTORMPEAKS = "Die Sturmgipfel", -- Needs review
	THETEMPLEOFTHEJADESERPENT = "The Temple of the Jade Serpent", -- Requires localization
	THEUNDERBOG = "The Underbog", -- Requires localization
	THEVIOLETHOLD = "The Violet Hold", -- Requires localization
	THEVORTEXPINNACLE = "The Vortex Pinnacle", -- Requires localization
	THEWANDERINGISLE = "Die Wandernde Insel", -- Needs review
	THEZANDALARI = "Die Zandalari", -- Needs review
	THOUSANDNEEDLES = "Tausend Nadeln", -- Needs review
	THRONEOFTHEFOURWINDS = "Throne of the Four Winds", -- Requires localization
	THRONEOFTHETIDES = "Throne of the Tides", -- Requires localization
	THUNDERBLUFF = "Donnerfels", -- Needs review
	TIRISFALGLADES = "Tirisfal", -- Needs review
	TOLBARAD = "Tol Barad", -- Needs review
	TOLBARADPENINSULA = "Halbinsel von Tol Barad", -- Needs review
	TOURNAMENT = "Turnier", -- Needs review
	TOWNLONGSTEPPES = "Tanglong-Ödnis", -- Needs review
	TRIALOFTHECHAMPION = "Trial of the Champion", -- Requires localization
	TRIALOFTHECRUSADER = "Trial of the Crusader", -- Requires localization
	TWILIGHTHIGHLANDS = "Schattenhochland", -- Needs review
	TWINPEAKS = "Zwillingsgipfel", -- Needs review
	ULDAMAN = "Uldaman", -- Requires localization
	ULDUAR = "Ulduar", -- Requires localization
	ULDUM = "Uldum", -- Needs review
	UNDERCITY = "Unterstadt", -- Needs review
	UNGOROCRATER = "Krater von Un'Goro", -- Needs review
	UTGARDEKEEP = "Utgarde Keep", -- Requires localization
	UTGARDEPINNACLE = "Utgarde Pinnacle", -- Requires localization
	VALEOFETERNALBLOSSOMS = "Tal der Ewigen Blüten", -- Needs review
	VALLEYOFTHEFOURWINDS = "Tal der Vier Winde", -- Needs review
	VASHJIR = "Vashj'ir", -- Needs review
	VAULTOFARCHAVON = "Vault of Archavon", -- Requires localization
	WAILINGCAVERNS = "Wailing Caverns", -- Requires localization
	WARLOCK = "Hexenmeister", -- Needs review
	WARRIOR = "Krieger", -- Needs review
	WARSONGGULCH = "Kriegshymnenschlucht", -- Needs review
	WELLOFETERNITY = "Well of Eternity", -- Requires localization
	WESTERNPLAGUELANDS = "Westliche Pestländer", -- Needs review
	WESTFALL = "Westfall", -- Needs review
	WETLANDS = "Sumpfland", -- Needs review
	WINTERGRASP = "Tausendwintersee", -- Needs review
	WINTERSPRING = "Winterquell", -- Needs review
	WINTERVEIL = "Winterhauchfest", -- Needs review
	WORLDEVENTS = "Weltereignisse", -- Needs review
	ZANGARMARSH = "Zangarmarschen", -- Needs review
	ZULAMAN = "Zul'Aman", -- Requires localization
	ZULDRAK = "Zul'Drak", -- Needs review
	ZULFARRAK = "Zul'Farrak", -- Requires localization
	ZULGURUB = "Zul'Gurub", -- Requires localization
}

end