if GetLocale() == "esMX" then
qcLocalize = {
	ABYSSALDEPTHS = "Abyssal Depths", -- Requires localization
	AHNKAHETTHEOLDKINGDOM = "Ahn'kahet: The Old Kingdom", -- Requires localization
	AHNQIRAJ = "Ahn'Qiraj", -- Requires localization
	AHNQIRAJTHEFALLENKINGDOM = "Ahn'Qiraj: The Fallen Kingdom", -- Requires localization
	ALCHEMY = "Alchemy", -- Requires localization
	ALTERACVALLEY = "Alterac Valley", -- Requires localization
	ARATHIBASIN = "Arathi Basin", -- Requires localization
	ARATHIHIGHLANDS = "Arathi Highlands", -- Requires localization
	ARCHAEOLOGY = "Archaeology", -- Requires localization
	ASHENVALE = "Ashenvale", -- Requires localization
	AUCHENAICRYPTS = "Auchenai Crypts", -- Requires localization
	AUCHINDOUN = "Auchindoun", -- Requires localization
	AZJOLNERUB = "Azjol-Nerub", -- Requires localization
	AZSHARA = "Azshara", -- Requires localization
	AZUREMYSTISLE = "Azuremyst Isle", -- Requires localization
	BADLANDS = "Badlands", -- Requires localization
	BARADINHOLD = "Baradin Hold", -- Requires localization
	BATTLEGROUNDS = "Battlegrounds", -- Requires localization
	BLACKFATHOMDEEPS = "Blackfathom Deeps", -- Requires localization
	BLACKROCKCAVERNS = "Blackrock Caverns", -- Requires localization
	BLACKROCKDEPTHS = "Blackrock Depths", -- Requires localization
	BLACKROCKSPIRE = "Blackrock Spire", -- Requires localization
	BLACKSMITHING = "Blacksmithing", -- Requires localization
	BLACKTEMPLE = "Black Temple", -- Requires localization
	BLACKWINGDESCENT = "Blackwing Descent", -- Requires localization
	BLACKWINGLAIR = "Blackwing Lair", -- Requires localization
	BLADESEDGEMOUNTAINS = "Blade's Edge Mountains", -- Requires localization
	BLASTEDLANDS = "Blasted Lands", -- Requires localization
	BLOODMYSTISLE = "Bloodmyst Isle", -- Requires localization
	BOREANTUNDRA = "Borean Tundra", -- Requires localization
	BREWFEST = "Brewfest", -- Requires localization
	BURNINGSTEPPES = "Burning Steppes", -- Requires localization
	CAVERNSOFTIME = "Caverns of Time", -- Requires localization
	CHILDRENSWEEK = "Children's Week", -- Requires localization
	CLASSES = "Classes", -- Requires localization
	CLASSQUESTS = "Class Quests", -- Requires localization
	CLEARUPDATECACHE = "Clear Update Cache...", -- Requires localization
	COILFANGRESERVOIR = "Coilfang Reservoir", -- Requires localization
	COMBINEDMAPANDQUESTFILTERS = "Combined Map & Quest List Filters", -- Requires localization
	CONFIGSUBTITLE = "These options allow you to change the way that Quest Completist handles and filters its data.", -- Requires localization
	CONFIGTITLE = "Quest Completist - Configuration", -- Requires localization
	CONTINENTS = "Continents", -- Requires localization
	COOKING = "Cooking", -- Requires localization
	CRYSTALSONGFOREST = "Crystalsong Forest", -- Requires localization
	DALARAN = "Dalaran", -- Requires localization
	DARKMOONFAIRE = "Darkmoon Faire", -- Requires localization
	DARKSHORE = "Darkshore", -- Requires localization
	DARNASSUS = "Darnassus", -- Requires localization
	DAYOFTHEDEAD = "Day of the Dead", -- Requires localization
	DEADWINDPASS = "Deadwind Pass", -- Requires localization
	DEATHKNIGHT = "Death Knight", -- Requires localization
	DEEPHOLM = "Deepholm", -- Requires localization
	DEEPRUNTRAM = "Deeprun Tram", -- Requires localization
	DESOLACE = "Desolace", -- Requires localization
	DIREMAUL = "Dire Maul", -- Requires localization
	DRAGONBLIGHT = "Dragonblight", -- Requires localization
	DRAGONSOUL = "Dragon Soul", -- Requires localization
	DRAKTHARONKEEP = "Drak'Tharon Keep", -- Requires localization
	DREADWASTES = "Dread Wastes", -- Requires localization
	DRUID = "Druid", -- Requires localization
	DUNGEONSANDRAIDS = "Dungeons & Raids", -- Requires localization
	DUNMOROGH = "Dun Morogh", -- Requires localization
	DUROTAR = "Durotar", -- Requires localization
	DUSKWOOD = "Duskwood", -- Requires localization
	DUSTWALLOWMARSH = "Dustwallow Marsh", -- Requires localization
	EASTERNKINGDOMS = "Eastern Kingdoms", -- Requires localization
	EASTERNPLAGUELANDS = "Eastern Plaguelands", -- Requires localization
	ELEMENTALBONDS = "Elemental Bonds", -- Requires localization
	ELWYNNFOREST = "Elwynn Forest", -- Requires localization
	ENCHANTING = "Enchanting", -- Requires localization
	ENDTIME = "End Time", -- Requires localization
	ENGINEERING = "Engineering", -- Requires localization
	EVERSONGWOODS = "Eversong Woods", -- Requires localization
	EYEOFTHESTORM = "Eye of the Storm", -- Requires localization
	FELWOOD = "Felwood", -- Requires localization
	FERALAS = "Feralas", -- Requires localization
	FIRELANDS = "Firelands", -- Requires localization
	FIRELANDSINVASION = "Firelands Invasion", -- Requires localization
	FIRSTAID = "First Aid", -- Requires localization
	FISHING = "Fishing", -- Requires localization
	GHOSTLANDS = "Ghostlands", -- Requires localization
	GILNEAS = "Gilneas", -- Requires localization
	GILNEASCITY = "Gilneas City", -- Requires localization
	GNOMEREGAN = "Gnomeregan", -- Requires localization
	GRIMBATOL = "Grim Batol", -- Requires localization
	GRIZZLYHILLS = "Grizzly Hills", -- Requires localization
	GRUULSLAIR = "Gruul's Lair", -- Requires localization
	GUNDRAK = "Gundrak", -- Requires localization
	HALLOWSEND = "Hallow's End", -- Requires localization
	HALLSOFLIGHTNING = "Halls of Lightning", -- Requires localization
	HALLSOFORIGINATION = "Halls of Origination", -- Requires localization
	HALLSOFREFLECTION = "Halls of Reflection", -- Requires localization
	HALLSOFSTONE = "Halls of Stone", -- Requires localization
	HARVESTFESTIVAL = "Harvest Festival", -- Requires localization
	HELLFIRECITADEL = "Hellfire Citadel", -- Requires localization
	HELLFIREPENINSULA = "Hellfire Peninsula", -- Requires localization
	HELLFIRERAMPARTS = "Hellfire Ramparts", -- Requires localization
	HERBALISM = "Herbalism", -- Requires localization
	HIDECOMPLETEDQUESTS = "Hide Completed Quests", -- Requires localization
	HIDEINPROGRESSQUESTS = "Hide In-Progress Quests", -- Requires localization
	HIDELOWLEVELQUESTS = "Hide Low Level Quests", -- Requires localization
	HIDENONACTIVESEASONALQUESTS = "Hide Non-Active Seasonal Quests", -- Requires localization
	HIDEOTHERFACTIONQUESTS = "Hide Other Faction Quests", -- Requires localization
	HIDEOTHERPROFESSIONQUESTS = "Hide Other Profession Quests", -- Requires localization
	HIDEOTHERRACEANDCLASSQUESTS = "Hide Other Race & Class Quests", -- Requires localization
	HILLSBRADFOOTHILLS = "Hillsbrad Foothills", -- Requires localization
	HOUROFTWILIGHT = "Hour of Twilight", -- Requires localization
	HOWLINGFJORD = "Howling Fjord", -- Requires localization
	HROTHGARSLANDING = "Hrothgar's Landing", -- Requires localization
	HUNTER = "Hunter", -- Requires localization
	HYJALSUMMIT = "Hyjal Summit", -- Requires localization
	ICECROWN = "Icecrown", -- Requires localization
	ICECROWNCITADEL = "Icecrown Citadel", -- Requires localization
	INSCRIPTION = "Inscription", -- Requires localization
	IRONFORGE = "Ironforge", -- Requires localization
	ISLEOFCONQUEST = "Isle of Conquest", -- Requires localization
	ISLEOFQUELDANAS = "Isle of Quel'Danas", -- Requires localization
	JEWELCRAFTING = "Jewelcrafting", -- Requires localization
	KALIMDOR = "Kalimdor", -- Requires localization
	KARAZHAN = "Karazhan", -- Requires localization
	KELPTHARFOREST = "Kelp'thar Forest", -- Requires localization
	KEZAN = "Kezan", -- Requires localization
	KRASARANGWILDS = "Krasarang Wilds", -- Requires localization
	KUNLAISUMMIT = "Kun-Lai Summit", -- Requires localization
	LEATHERWORKING = "Leatherworking", -- Requires localization
	LEGENDARY = "Legendary", -- Requires localization
	LOCHMODAN = "Loch Modan", -- Requires localization
	LOSTCITYOFTHETOLVIR = "Lost City of the Tol'vir", -- Requires localization
	LOVEISINTHEAIR = "Love is in the Air", -- Requires localization
	LUNARFESTIVAL = "Lunar Festival", -- Requires localization
	MAGE = "Mage", -- Requires localization
	MAGISTERSTERRACE = "Magisters' Terrace", -- Requires localization
	MAGTHERIDONSLAIR = "Magtheridon's Lair", -- Requires localization
	MANATOMBS = "Mana-Tombs", -- Requires localization
	MAPFILTERS = "Map Filters", -- Requires localization
	MARAUDON = "Maraudon", -- Requires localization
	MIDSUMMERFIREFESTIVAL = "Midsummer Fire Festival", -- Requires localization
	MINING = "Mining", -- Requires localization
	MISCELLANEOUS = "Miscellaneous", -- Requires localization
	MOGUSHANVAULTS = "Mogu'shan Vaults", -- Requires localization
	MOLTENCORE = "Molten Core", -- Requires localization
	MOLTENFRONT = "Molten Front", -- Requires localization
	MONK = "Monk", -- Requires localization
	MOONGLADE = "Moonglade", -- Requires localization
	MOUNTHYJAL = "Mount Hyjal", -- Requires localization
	MULGORE = "Mulgore", -- Requires localization
	NAGRAND = "Nagrand", -- Requires localization
	NAXXRAMAS = "Naxxramas", -- Requires localization
	NETHERSTORM = "Netherstorm", -- Requires localization
	NEWYEARSEVE = "New Year's Eve", -- Requires localization
	NOBLEGARDEN = "Noblegarden", -- Requires localization
	NORTHERNBARRENS = "Northern Barrens", -- Requires localization
	NORTHERNSTRANGLETHORN = "Northern Stranglethorn", -- Requires localization
	NORTHREND = "Northrend", -- Requires localization
	OLDHILLSBRADFOOTHILLS = "Old Hillsbrad Foothills", -- Requires localization
	ONYXIASLAIR = "Onyxia's Lair", -- Requires localization
	OPTIONS = "Options", -- Requires localization
	ORGRIMMAR = "Orgrimmar", -- Requires localization
	OUTLAND = "Outland", -- Requires localization
	PALACEOFTHEHEAVENS = "Palace of the Heavens", -- Requires localization
	PALADIN = "Paladin", -- Requires localization
	PANDARIA = "Pandaria", -- Requires localization
	PERFORMSERVERQUERY = "Perform Server Query...", -- Requires localization
	PILGRIMSBOUNTY = "Pilgrim's Bounty", -- Requires localization
	PITOFSARON = "Pit of Saron", -- Requires localization
	PRIEST = "Priest", -- Requires localization
	PROFESSIONS = "Professions", -- Requires localization
	QUERYREQUESTED = "A server query has been requested...", -- Requires localization
	QUESTLISTFILTERS = "Quest List Filters", -- Requires localization
	QUESTSFOUND = "%d Quests Found", -- Requires localization
	RAGEFIRECHASM = "Ragefire Chasm", -- Requires localization
	RAIDS = "Raids", -- Requires localization
	RAZORFENDOWNS = "Razorfen Downs", -- Requires localization
	RAZORFENKRAUL = "Razorfen Kraul", -- Requires localization
	REDRIDGEMOUNTAINS = "Redridge Mountains", -- Requires localization
	ROGUE = "Rogue", -- Requires localization
	RUINSOFAHNQIRAJ = "Ruins of Ahn'Qiraj", -- Requires localization
	RUINSOFGILNEAS = "Ruins of Gilneas", -- Requires localization
	RUINSOFGILNEASCITY = "Ruins of Gilneas City", -- Requires localization
	SCARLETMONASTERY = "Scarlet Monastery", -- Requires localization
	SCHOLOMANCE = "Scholomance", -- Requires localization
	SEARINGGORGE = "Searing Gorge", -- Requires localization
	SEASONAL = "Seasonal", -- Requires localization
	SERPENTSHRINECAVERN = "Serpentshrine Cavern", -- Requires localization
	SETHEKKHALLS = "Sethekk Halls", -- Requires localization
	SHADOPANMONASTERY = "Shado-pan Monastery", -- Requires localization
	SHADOWFANGKEEP = "Shadowfang Keep", -- Requires localization
	SHADOWLABYRINTH = "Shadow Labyrinth", -- Requires localization
	SHADOWMOONVALLEY = "Shadowmoon Valley", -- Requires localization
	SHAMAN = "Shaman", -- Requires localization
	SHATTRATHCITY = "Shattrath City", -- Requires localization
	SHIMMERINGEXPANSE = "Shimmering Expanse", -- Requires localization
	SHOLAZARBASIN = "Sholazar Basin", -- Requires localization
	SHOWMAPICONS = "Show Map Icons", -- Requires localization
	SIEGEOFNIUZAOTEMPLE = "Siege of Niuzao Temple", -- Requires localization
	SILITHUS = "Silithus", -- Requires localization
	SILVERMOONCITY = "Silvermoon City", -- Requires localization
	SILVERPINEFOREST = "Silverpine Forest", -- Requires localization
	SILVERSHARDMINES = "Silver Shard Mines", -- Requires localization
	SKINNING = "Skinning", -- Requires localization
	SORTALPHA = "Sort: Alphabetically", -- Requires localization
	SORTLEVEL = "Sort: Level", -- Requires localization
	SOUTHERNBARRENS = "Southern Barrens", -- Requires localization
	SPECIAL = "Special", -- Requires localization
	SPECIALS = "Specials", -- Requires localization
	STONETALONMOUNTAINS = "Stonetalon Mountains", -- Requires localization
	STORMSTOUTBREWERY = "Stormstout Brewery", -- Requires localization
	STORMWINDCITY = "Stormwind City", -- Requires localization
	STRANDOFTHEANCIENTS = "Strand of the Ancients", -- Requires localization
	STRANGLETHORNVALE = "Stranglethorn Vale", -- Requires localization
	STRATHOLME = "Stratholme", -- Requires localization
	SUNKENTEMPLE = "Sunken Temple", -- Requires localization
	SUNWELLPLATEAU = "Sunwell Plateau", -- Requires localization
	SWAMPOFSORROWS = "Swamp of Sorrows", -- Requires localization
	TAILORING = "Tailoring", -- Requires localization
	TANARIS = "Tanaris", -- Requires localization
	TELDRASSIL = "Teldrassil", -- Requires localization
	TEMPESTKEEP = "Tempest Keep", -- Requires localization
	TEMPLEOFAHNQIRAJ = "Temple of Ahn'Qiraj", -- Requires localization
	TEMPLEOFKOTMOGU = "Temple of Kotmogu", -- Requires localization
	TEMPLEOFTHEREDCRANE = "Temple of the Red Crane", -- Requires localization
	TEROKKARFOREST = "Terokkar Forest", -- Requires localization
	THEARCATRAZ = "The Arcatraz", -- Requires localization
	THEBASTIONOFTWILIGHT = "The Bastion of Twilight", -- Requires localization
	THEBATTLEFORGILNEAS = "The Battle for Gilneas", -- Requires localization
	THEBLACKMORASS = "The Black Morass", -- Requires localization
	THEBLOODFURNACE = "The Blood Furnace", -- Requires localization
	THEBOTANICA = "The Botanica", -- Requires localization
	THECAPEOFSTRANGLETHORN = "The Cape of Stranglethorn", -- Requires localization
	THECULLINGOFSTRATHOLME = "The Culling of Stratholme", -- Requires localization
	THEDEADMINES = "The Deadmines", -- Requires localization
	THEEXODAR = "The Exodar", -- Requires localization
	THEEYE = "The Eye", -- Requires localization
	THEEYEOFETERNITY = "The Eye of Eternity", -- Requires localization
	THEFORGEOFSOULS = "The Forge of Souls", -- Requires localization
	THEGATEOFTHESETTINGSUN = "The Gate of the Setting Sun", -- Requires localization
	THEHINTERLANDS = "The Hinterlands", -- Requires localization
	THEJADEFOREST = "The Jade Forest", -- Requires localization
	THELOSTISLES = "The Lost Isles", -- Requires localization
	THEMAELSTROM = "The Maelstrom", -- Requires localization
	THEMECHANAR = "The Mechanar", -- Requires localization
	THENEXUS = "The Nexus", -- Requires localization
	THEOBSIDIANSANCTUM = "The Obsidian Sanctum", -- Requires localization
	THEOCULUS = "The Oculus", -- Requires localization
	THERUBYSANCTUM = "The Ruby Sanctum", -- Requires localization
	THESHATTEREDHALLS = "The Shattered Halls", -- Requires localization
	THESLAVEPENS = "The Slave Pens", -- Requires localization
	THESTEAMVAULT = "The Steamvault", -- Requires localization
	THESTOCKADE = "The Stockade", -- Requires localization
	THESTONECORE = "The Stonecore", -- Requires localization
	THESTORMPEAKS = "The Storm Peaks", -- Requires localization
	THETEMPLEOFTHEJADESERPENT = "The Temple of the Jade Serpent", -- Requires localization
	THEUNDERBOG = "The Underbog", -- Requires localization
	THEVIOLETHOLD = "The Violet Hold", -- Requires localization
	THEVORTEXPINNACLE = "The Vortex Pinnacle", -- Requires localization
	THEWANDERINGISLE = "The Wandering Isle", -- Requires localization
	THEZANDALARI = "The Zandalari", -- Requires localization
	THOUSANDNEEDLES = "Thousand Needles", -- Requires localization
	THRONEOFTHEFOURWINDS = "Throne of the Four Winds", -- Requires localization
	THRONEOFTHETIDES = "Throne of the Tides", -- Requires localization
	THUNDERBLUFF = "Thunder Bluff", -- Requires localization
	TIRISFALGLADES = "Tirisfal Glades", -- Requires localization
	TOLBARAD = "Tol Barad", -- Requires localization
	TOLBARADPENINSULA = "Tol Barad Peninsula", -- Requires localization
	TOURNAMENT = "Tournament", -- Requires localization
	TOWNLONGSTEPPES = "Townlong Steppes", -- Requires localization
	TRIALOFTHECHAMPION = "Trial of the Champion", -- Requires localization
	TRIALOFTHECRUSADER = "Trial of the Crusader", -- Requires localization
	TWILIGHTHIGHLANDS = "Twilight Highlands", -- Requires localization
	TWINPEAKS = "Twin Peaks", -- Requires localization
	ULDAMAN = "Uldaman", -- Requires localization
	ULDUAR = "Ulduar", -- Requires localization
	ULDUM = "Uldum", -- Requires localization
	UNDERCITY = "Undercity", -- Requires localization
	UNGOROCRATER = "Un'Goro Crater", -- Requires localization
	UTGARDEKEEP = "Utgarde Keep", -- Requires localization
	UTGARDEPINNACLE = "Utgarde Pinnacle", -- Requires localization
	VALEOFETERNALBLOSSOMS = "Vale of Eternal Blossoms", -- Requires localization
	VALLEYOFTHEFOURWINDS = "Valley of the Four Winds", -- Requires localization
	VASHJIR = "Vashj'ir", -- Requires localization
	VAULTOFARCHAVON = "Vault of Archavon", -- Requires localization
	WAILINGCAVERNS = "Wailing Caverns", -- Requires localization
	WARLOCK = "Warlock", -- Requires localization
	WARRIOR = "Warrior", -- Requires localization
	WARSONGGULCH = "Warsong Gulch", -- Requires localization
	WELLOFETERNITY = "Well of Eternity", -- Requires localization
	WESTERNPLAGUELANDS = "Western Plaguelands", -- Requires localization
	WESTFALL = "Westfall", -- Requires localization
	WETLANDS = "Wetlands", -- Requires localization
	WINTERGRASP = "Wintergrasp", -- Requires localization
	WINTERSPRING = "Winterspring", -- Requires localization
	WINTERVEIL = "Winter Veil", -- Requires localization
	WORLDEVENTS = "World Events", -- Requires localization
	ZANGARMARSH = "Zangarmarsh", -- Requires localization
	ZULAMAN = "Zul'Aman", -- Requires localization
	ZULDRAK = "Zul'Drak", -- Requires localization
	ZULFARRAK = "Zul'Farrak", -- Requires localization
	ZULGURUB = "Zul'Gurub", -- Requires localization
}

end