if GetLocale() == "frFR" then
qcLocalize = {
	ABYSSALDEPTHS = "Profondeurs Abyssales",
	AHNKAHETTHEOLDKINGDOM = "Ahn'kahet: The Old Kingdom", -- Requires localization
	AHNQIRAJ = "Ahn'Qiraj", -- Requires localization
	AHNQIRAJTHEFALLENKINGDOM = "Ahn'Qiraj : le royaume Déchu",
	ALCHEMY = "Alchimie",
	ALTERACVALLEY = "Vallée d'Alterac",
	ARATHIBASIN = "Bassin Arathi",
	ARATHIHIGHLANDS = "Hautes-terres Arathies",
	ARCHAEOLOGY = "Archéologie",
	ASHENVALE = "Orneval",
	AUCHENAICRYPTS = "Auchenai Crypts", -- Requires localization
	AUCHINDOUN = "Auchindoun", -- Requires localization
	AZJOLNERUB = "Azjol-Nerub", -- Requires localization
	AZSHARA = "Azshara",
	AZUREMYSTISLE = "Île de Brume-Azur",
	BADLANDS = "Terres Ingrates",
	BARADINHOLD = "Baradin Hold", -- Requires localization
	BATTLEGROUNDS = "Champs de bataille",
	BLACKFATHOMDEEPS = "Blackfathom Deeps", -- Requires localization
	BLACKROCKCAVERNS = "Blackrock Caverns", -- Requires localization
	BLACKROCKDEPTHS = "Blackrock Depths", -- Requires localization
	BLACKROCKSPIRE = "Blackrock Spire", -- Requires localization
	BLACKSMITHING = "Forge",
	BLACKTEMPLE = "Black Temple", -- Requires localization
	BLACKWINGDESCENT = "Blackwing Descent", -- Requires localization
	BLACKWINGLAIR = "Blackwing Lair", -- Requires localization
	BLADESEDGEMOUNTAINS = "Les Tranchantes",
	BLASTEDLANDS = "Terres Foudroyées",
	BLOODMYSTISLE = "Île de Brume-Sang",
	BOREANTUNDRA = "Toundra Boréenne",
	BREWFEST = "Fête des Brasseurs",
	BURNINGSTEPPES = "Steppes Ardentes",
	CAVERNSOFTIME = "Caverns of Time", -- Requires localization
	CHILDRENSWEEK = "Semaine des enfants",
	CLASSES = "Classes",
	CLASSQUESTS = "Quêtes de classe",
	CLEARUPDATECACHE = "Clear Update Cache...", -- Needs review
	COILFANGRESERVOIR = "Coilfang Reservoir", -- Requires localization
	COMBINEDMAPANDQUESTFILTERS = "Combined Map & Quest List Filters", -- Needs review
	CONFIGSUBTITLE = "Ces options vous permettent de changer la façon dont Quest Completist gère et filtre les données.",
	CONFIGTITLE = "Quest Completist - Configuration",
	CONTINENTS = "Continents",
	COOKING = "Cuisine",
	CRYSTALSONGFOREST = "Forêt du Chant de cristal",
	DALARAN = "Dalaran",
	DARKMOONFAIRE = "Foire de Sombrelune",
	DARKSHORE = "Sombrivage",
	DARNASSUS = "Darnassus",
	DAYOFTHEDEAD = "Jour des morts",
	DEADWINDPASS = "Défilé de Deuillevent",
	DEATHKNIGHT = "Chevalier de la mort",
	DEEPHOLM = "Le Tréfonds",
	DEEPRUNTRAM = "Tram des profondeurs",
	DESOLACE = "Désolace",
	DIREMAUL = "Dire Maul", -- Requires localization
	DRAGONBLIGHT = "Désolation des dragons",
	DRAGONSOUL = "Dragon Soul", -- Requires localization
	DRAKTHARONKEEP = "Drak'Tharon Keep", -- Requires localization
	DREADWASTES = "Terres de l'Angoisse",
	DRUID = "Druide",
	DUNGEONSANDRAIDS = "Donjons et raids",
	DUNMOROGH = "Dun Morogh",
	DUROTAR = "Durotar",
	DUSKWOOD = "Bois de la Pénombre",
	DUSTWALLOWMARSH = "Marécage d'Âprefange",
	EASTERNKINGDOMS = "Royaumes de l'Est",
	EASTERNPLAGUELANDS = "Maleterres de l'Est",
	ELEMENTALBONDS = "Liens élémentaires", -- Needs review
	ELWYNNFOREST = "Forêt d'Elwynn",
	ENCHANTING = "Enchantement",
	ENDTIME = "End Time", -- Requires localization
	ENGINEERING = "Ingénierie",
	EVERSONGWOODS = "Bois des Chants éternels",
	EYEOFTHESTORM = "L'Œil du cyclone",
	FELWOOD = "Gangrebois",
	FERALAS = "Féralas",
	FIRELANDS = "Firelands", -- Requires localization
	FIRELANDSINVASION = "Invasion des terres de Feu",
	FIRSTAID = "Secourisme",
	FISHING = "Pêche",
	GHOSTLANDS = "Les terres Fantômes",
	GILNEAS = "Gilneas", -- Requires localization
	GILNEASCITY = "Gilneas City", -- Requires localization
	GNOMEREGAN = "Gnomeregan", -- Requires localization
	GRIMBATOL = "Grim Batol", -- Requires localization
	GRIZZLYHILLS = "Les Grisonnes",
	GRUULSLAIR = "Gruul's Lair", -- Requires localization
	GUNDRAK = "Gundrak", -- Requires localization
	HALLOWSEND = "Sanssaint",
	HALLSOFLIGHTNING = "Halls of Lightning", -- Requires localization
	HALLSOFORIGINATION = "Halls of Origination", -- Requires localization
	HALLSOFREFLECTION = "Halls of Reflection", -- Requires localization
	HALLSOFSTONE = "Halls of Stone", -- Requires localization
	HARVESTFESTIVAL = "Fête des moissons",
	HELLFIRECITADEL = "Hellfire Citadel", -- Requires localization
	HELLFIREPENINSULA = "Péninsule des Flammes infernales",
	HELLFIRERAMPARTS = "Hellfire Ramparts", -- Requires localization
	HERBALISM = "Herboristerie",
	HIDECOMPLETEDQUESTS = "Masquer les quêtes achevées",
	HIDEINPROGRESSQUESTS = "Masquer les quêtes en cours",
	HIDELOWLEVELQUESTS = "Masquer les quêtes de bas niveau",
	HIDENONACTIVESEASONALQUESTS = [=[Masquer les quêtes non-saisonnière 
]=],
	HIDEOTHERFACTIONQUESTS = "Masquer les quêtes des autres faction",
	HIDEOTHERPROFESSIONQUESTS = "Masquer les quêtes des autres métiers ",
	HIDEOTHERRACEANDCLASSQUESTS = "Masquer les quêtes des autres race & classe",
	HILLSBRADFOOTHILLS = "Contreforts de Hautebrande",
	HOUROFTWILIGHT = "Hour of Twilight", -- Requires localization
	HOWLINGFJORD = "Fjord Hurlant",
	HROTHGARSLANDING = "Accostage de Hrothgar",
	HUNTER = "Chasseur",
	HYJALSUMMIT = "Hyjal Summit", -- Requires localization
	ICECROWN = "La Couronne de glace",
	ICECROWNCITADEL = "Icecrown Citadel", -- Requires localization
	INSCRIPTION = "Inscription",
	IRONFORGE = "Forgefer",
	ISLEOFCONQUEST = "Île des Conquérants",
	ISLEOFQUELDANAS = "Île de Quel'Danas",
	JEWELCRAFTING = "Joaillerie",
	KALIMDOR = "Kalimdor",
	KARAZHAN = "Karazhan", -- Requires localization
	KELPTHARFOREST = "Forêt de Varech'thar",
	KEZAN = "Kezan",
	KRASARANGWILDS = "Étendues sauvages de Krasarang",
	KUNLAISUMMIT = "Le sommet Kun-Lai",
	LEATHERWORKING = "Travail du cuir",
	LEGENDARY = "Légendaire",
	LOCHMODAN = "Loch Modan",
	LOSTCITYOFTHETOLVIR = "Lost City of the Tol'vir", -- Requires localization
	LOVEISINTHEAIR = "De l'amour dans l'air",
	LUNARFESTIVAL = "Fête lunaire",
	MAGE = "Mage",
	MAGISTERSTERRACE = "Magisters' Terrace", -- Requires localization
	MAGTHERIDONSLAIR = "Magtheridon's Lair", -- Requires localization
	MANATOMBS = "Mana-Tombs", -- Requires localization
	MAPFILTERS = "Filtres - Carte",
	MARAUDON = "Maraudon", -- Requires localization
	MIDSUMMERFIREFESTIVAL = "Fête du Feu du solstice d'été",
	MINING = "Minage",
	MISCELLANEOUS = "Divers",
	MOGUSHANVAULTS = "Mogu'shan Vaults", -- Requires localization
	MOLTENCORE = "Molten Core", -- Requires localization
	MOLTENFRONT = "Front du Magma",
	MONK = "Moine",
	MOONGLADE = "Reflet-de-Lune",
	MOUNTHYJAL = "Mont Hyjal",
	MULGORE = "Mulgore",
	NAGRAND = "Nagrand",
	NAXXRAMAS = "Naxxramas", -- Requires localization
	NETHERSTORM = "Raz-de-Néant",
	NEWYEARSEVE = "Saint-Sylvestre", -- Needs review
	NOBLEGARDEN = "Le Jardin des nobles",
	NORTHERNBARRENS = "Tarides du Nord",
	NORTHERNSTRANGLETHORN = "Strangleronce septentrionale",
	NORTHREND = "Norfendre",
	OLDHILLSBRADFOOTHILLS = "Old Hillsbrad Foothills", -- Requires localization
	ONYXIASLAIR = "Onyxia's Lair", -- Requires localization
	OPTIONS = "Options",
	ORGRIMMAR = "Orgrimmar",
	OUTLAND = "Outreterre",
	PALACEOFTHEHEAVENS = "Palace of the Heavens", -- Requires localization
	PALADIN = "Paladin",
	PANDARIA = "Pandarie",
	PERFORMSERVERQUERY = "Requêtes serveur en cours...", -- Needs review
	PILGRIMSBOUNTY = "Les Bienfaits du pèlerin",
	PITOFSARON = "Pit of Saron", -- Requires localization
	PRIEST = "Prêtre",
	PROFESSIONS = "Métiers",
	QUERYREQUESTED = "Une requête du serveur a été demandé ...",
	QUESTLISTFILTERS = "Filtres - liste de quêtes",
	QUESTSFOUND = "%d Quêtes trouvé",
	RAGEFIRECHASM = "Ragefire Chasm", -- Requires localization
	RAIDS = "Raids",
	RAZORFENDOWNS = "Razorfen Downs", -- Requires localization
	RAZORFENKRAUL = "Razorfen Kraul", -- Requires localization
	REDRIDGEMOUNTAINS = "Les Carmines",
	ROGUE = "Voleur",
	RUINSOFAHNQIRAJ = "Ruins of Ahn'Qiraj", -- Requires localization
	RUINSOFGILNEAS = "Ruines de Gilnéas",
	RUINSOFGILNEASCITY = "Ruines de Gilnéas",
	SCARLETMONASTERY = "Scarlet Monastery", -- Requires localization
	SCHOLOMANCE = "Scholomance", -- Requires localization
	SEARINGGORGE = "Gorge des Vents brûlants",
	SEASONAL = "Saisonnier",
	SERPENTSHRINECAVERN = "Serpentshrine Cavern", -- Requires localization
	SETHEKKHALLS = "Sethekk Halls", -- Requires localization
	SHADOPANMONASTERY = "Shado-pan Monastery", -- Requires localization
	SHADOWFANGKEEP = "Shadowfang Keep", -- Requires localization
	SHADOWLABYRINTH = "Shadow Labyrinth", -- Requires localization
	SHADOWMOONVALLEY = "Vallée d'Ombrelune",
	SHAMAN = "Chaman",
	SHATTRATHCITY = "Shattrath",
	SHIMMERINGEXPANSE = "Étendues Chatoyantes",
	SHOLAZARBASIN = "Bassin de Sholazar",
	SHOWMAPICONS = "Show Map Icons", -- Needs review
	SIEGEOFNIUZAOTEMPLE = "Siege of Niuzao Temple", -- Requires localization
	SILITHUS = "Silithus",
	SILVERMOONCITY = "Lune-d'argent",
	SILVERPINEFOREST = "Forêt des Pins-Argentés",
	SILVERSHARDMINES = "Silver Shard Mines", -- Needs review
	SKINNING = "Dépeçage",
	SORTALPHA = "Trier: Par ordre alphabétique",
	SORTLEVEL = "Trier: Par niveau",
	SOUTHERNBARRENS = "Tarides du Sud",
	SPECIAL = "Special",
	SPECIALS = "Specials",
	STONETALONMOUNTAINS = "Les Serres-Rocheuses",
	STORMSTOUTBREWERY = "Stormstout Brewery", -- Requires localization
	STORMWINDCITY = "Hurlevent",
	STRANDOFTHEANCIENTS = "Rivage des Anciens",
	STRANGLETHORNVALE = "Vallée de Strangleronce",
	STRATHOLME = "Stratholme", -- Requires localization
	SUNKENTEMPLE = "Sunken Temple", -- Requires localization
	SUNWELLPLATEAU = "Sunwell Plateau", -- Requires localization
	SWAMPOFSORROWS = "Marais des Chagrins",
	TAILORING = "Couture",
	TANARIS = "Tanaris",
	TELDRASSIL = "Teldrassil",
	TEMPESTKEEP = "Tempest Keep", -- Requires localization
	TEMPLEOFAHNQIRAJ = "Temple of Ahn'Qiraj", -- Requires localization
	TEMPLEOFKOTMOGU = "Temple de Kotmogu", -- Needs review
	TEMPLEOFTHEREDCRANE = "Temple of the Red Crane", -- Requires localization
	TEROKKARFOREST = "Forêt de Terokkar",
	THEARCATRAZ = "The Arcatraz", -- Requires localization
	THEBASTIONOFTWILIGHT = "The Bastion of Twilight", -- Requires localization
	THEBATTLEFORGILNEAS = "La bataille de Gilnéas",
	THEBLACKMORASS = "The Black Morass", -- Requires localization
	THEBLOODFURNACE = "The Blood Furnace", -- Requires localization
	THEBOTANICA = "The Botanica", -- Requires localization
	THECAPEOFSTRANGLETHORN = "Cap Strangleronce",
	THECULLINGOFSTRATHOLME = "The Culling of Stratholme", -- Requires localization
	THEDEADMINES = "The Deadmines", -- Requires localization
	THEEXODAR = "L'Exodar",
	THEEYE = "The Eye", -- Requires localization
	THEEYEOFETERNITY = "The Eye of Eternity", -- Requires localization
	THEFORGEOFSOULS = "The Forge of Souls", -- Requires localization
	THEGATEOFTHESETTINGSUN = "The Gate of the Setting Sun", -- Requires localization
	THEHINTERLANDS = "Les Hinterlands",
	THEJADEFOREST = "La forêt de Jade",
	THELOSTISLES = "Les îles Perdues",
	THEMAELSTROM = "Le Maelström",
	THEMECHANAR = "The Mechanar", -- Requires localization
	THENEXUS = "The Nexus", -- Requires localization
	THEOBSIDIANSANCTUM = "The Obsidian Sanctum", -- Requires localization
	THEOCULUS = "The Oculus", -- Requires localization
	THERUBYSANCTUM = "The Ruby Sanctum", -- Requires localization
	THESHATTEREDHALLS = "The Shattered Halls", -- Requires localization
	THESLAVEPENS = "The Slave Pens", -- Requires localization
	THESTEAMVAULT = "The Steamvault", -- Requires localization
	THESTOCKADE = "The Stockade", -- Requires localization
	THESTONECORE = "The Stonecore", -- Requires localization
	THESTORMPEAKS = "Les pics Foudroyés",
	THETEMPLEOFTHEJADESERPENT = "The Temple of the Jade Serpent", -- Requires localization
	THEUNDERBOG = "The Underbog", -- Requires localization
	THEVIOLETHOLD = "The Violet Hold", -- Requires localization
	THEVORTEXPINNACLE = "The Vortex Pinnacle", -- Requires localization
	THEWANDERINGISLE = "The Wandering Isle", -- Needs review
	THEZANDALARI = "Les Zandalari",
	THOUSANDNEEDLES = "Mille pointes",
	THRONEOFTHEFOURWINDS = "Throne of the Four Winds", -- Requires localization
	THRONEOFTHETIDES = "Throne of the Tides", -- Requires localization
	THUNDERBLUFF = "Les Pitons-du-Tonnerre",
	TIRISFALGLADES = "Clairières de Tirisfal",
	TOLBARAD = "Tol Barad",
	TOLBARADPENINSULA = "Péninsule de Tol Barad",
	TOURNAMENT = "Tournoi",
	TOWNLONGSTEPPES = "Le désert de Tanglong",
	TRIALOFTHECHAMPION = "Trial of the Champion", -- Requires localization
	TRIALOFTHECRUSADER = "Trial of the Crusader", -- Requires localization
	TWILIGHTHIGHLANDS = "Hautes-terres du Crépuscule",
	TWINPEAKS = "Pics-Jumeaux",
	ULDAMAN = "Uldaman", -- Requires localization
	ULDUAR = "Ulduar", -- Requires localization
	ULDUM = "Uldum",
	UNDERCITY = "Fossoyeuse",
	UNGOROCRATER = "Cratère d'Un'Goro",
	UTGARDEKEEP = "Utgarde Keep", -- Requires localization
	UTGARDEPINNACLE = "Utgarde Pinnacle", -- Requires localization
	VALEOFETERNALBLOSSOMS = "La vallée de l'Éternel printemps",
	VALLEYOFTHEFOURWINDS = "La vallée des Quatre vents",
	VASHJIR = "Vashj'ir",
	VAULTOFARCHAVON = "Vault of Archavon", -- Requires localization
	WAILINGCAVERNS = "Wailing Caverns", -- Requires localization
	WARLOCK = "Démoniste",
	WARRIOR = "Guerrier",
	WARSONGGULCH = "Goulet des Chanteguerres",
	WELLOFETERNITY = "Well of Eternity", -- Requires localization
	WESTERNPLAGUELANDS = "Maleterres de l'Ouest",
	WESTFALL = "Marche de l'Ouest",
	WETLANDS = "Les Paluns",
	WINTERGRASP = "Joug-d'hiver",
	WINTERSPRING = "Berceau-de-l'Hiver",
	WINTERVEIL = "Voile d'hiver",
	WORLDEVENTS = "Evénements Mondiaux",
	ZANGARMARSH = "Marécage de Zangar",
	ZULAMAN = "Zul'Aman", -- Requires localization
	ZULDRAK = "Zul'Drak",
	ZULFARRAK = "Zul'Farrak", -- Requires localization
	ZULGURUB = "Zul'Gurub", -- Requires localization
}

end